# Created with WinGet Releaser using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: max-sixty.worktrunk
PackageVersion: v0.29.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: git-wt.exe
  PortableCommandAlias: git-wt
- RelativeFilePath: wt.exe
  PortableCommandAlias: wt
ReleaseDate: 2026-03-15
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/max-sixty/worktrunk/releases/download/v0.29.4/worktrunk-x86_64-pc-windows-msvc.zip
  InstallerSha256: 10885B58E677054E9FF867FCF9EEFDD6C6DECD0C7032B25ECC52DC5FA7559294
ManifestType: installer
ManifestVersion: 1.12.0
