# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alex313031.Thorium
PackageVersion: 138.0.7204.303
ReleaseDate: 2026-02-18
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerType: exe
  InstallModes:
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Log: --verbose-logging --log-file="<LOGPATH>"
    Custom: --do-not-launch-chrome
  ExpectedReturnCodes:
  - InstallerReturnCode: 4
    ReturnResponse: downgrade
  - InstallerReturnCode: 22
    ReturnResponse: cancelledByUser
  - InstallerReturnCode: 60
    ReturnResponse: installInProgress
  InstallerUrl: https://github.com/Alex313031/Thorium-Win/releases/download/M138.0.7204.303/thorium_SSE3_mini_installer.exe
  InstallerSha256: 7243FD08A4B86568FC07B9CE9B8BAF1DCF3AE40C1FBE75EFDD6EEE043A8DDEB1
- Architecture: x64
  Scope: machine
  InstallerType: exe
  InstallModes:
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Log: --verbose-logging --log-file="<LOGPATH>"
    Custom: --do-not-launch-chrome --system-level
  ExpectedReturnCodes:
  - InstallerReturnCode: 4
    ReturnResponse: downgrade
  - InstallerReturnCode: 22
    ReturnResponse: cancelledByUser
  - InstallerReturnCode: 60
    ReturnResponse: installInProgress
  InstallerUrl: https://github.com/Alex313031/Thorium-Win/releases/download/M138.0.7204.303/thorium_SSE3_mini_installer.exe
  InstallerSha256: 7243FD08A4B86568FC07B9CE9B8BAF1DCF3AE40C1FBE75EFDD6EEE043A8DDEB1
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: BIN\thorium.exe
  ArchiveBinariesDependOnPath: true
  InstallerUrl: https://github.com/Alex313031/Thorium-Win/releases/download/M138.0.7204.303/thorium_SSE3_138.0.7204.303.zip
  InstallerSha256: 931468563186C4FB1D0F4F835A5B1399BE18C3D1C399D7F78FB02D4F1B1A23A8
  AppsAndFeaturesEntries:
  - DisplayName: Thorium (Portable)
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ManifestType: installer
ManifestVersion: 1.12.0
