# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.PowerBIReportServer
PackageVersion: 1.26.9682.1442
InstallerType: burn
Scope: machine
InstallerSwitches:
  Custom: IAcceptLicenseTerms=true
ProductCode: '{97ed8521-7950-48d1-8c38-2b34222466ef}'
ReleaseDate: 2026-07-08
AppsAndFeaturesEntries:
- UpgradeCode: '{FA435246-6E59-4929-9897-26CE834E90CB}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/3/7/5/3754bf6e-e422-46ec-b9f8-fb3dc3993cab/PowerBIReportServer.exe
  InstallerSha256: 5D1DEF7284D3FA6B4D21C34DFD2ED9B4A5A43F1D98E7702ED7E417AAFD1336C5
ManifestType: installer
ManifestVersion: 1.12.0
