PackageIdentifier: nathanpenny520.Nmail
PackageVersion: 0.4.4
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/nathanpenny520/Nmail/releases/download/v0.4.4/nmail-windows-x64.exe
    InstallerSha256: d36fb0e75932e253f50da554b5edb51a3a4c6207deda1e098d5bb2d4a2d5708f
    Commands:
      - nmail
ManifestType: installer
ManifestVersion: 1.6.0
