#
# Module manifest for module 'FileOperations'
#
# Generated by: Trenly
#
# Generated on: 5/27/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'FileOperations.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # ID used to uniquely identify this module
    GUID              = '37c15420-b760-4f80-8c52-a154225b867c'

    # Author of this module
    Author            = 'Microsoft Open Source Community'

    # Company or vendor of this module
    CompanyName       = 'Microsoft Corporation'

    # Copyright statement for this module
    Copyright         = 'Copyright (c) Microsoft Corporation. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Shared folder and file operations for winget-pkgs tooling scripts and modules.'

    # Functions to export from this module
    FunctionsToExport = @(
        'Initialize-Folder'
        'Request-RemoveItem'
        'Invoke-FileCleanup'
    )

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport   = @()

    PrivateData       = @{
        PSData = @{
            LicenseUri = 'https://github.com/microsoft/winget-pkgs/blob/master/LICENSE'
            ProjectUri = 'https://github.com/microsoft/winget-pkgs'
        }
    }
}
