# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: RaijuMounun.intqual
PackageVersion: 1.0.9
PackageLocale: en-US
Publisher: Eren Keskinoğlu
PublisherUrl: https://github.com/RaijuMounun
PublisherSupportUrl: https://github.com/RaijuMounun/intqual/issues
PackageName: Intqual
PackageUrl: https://github.com/RaijuMounun/intqual
License: MIT
LicenseUrl: https://github.com/RaijuMounun/intqual/blob/HEAD/LICENSE
ShortDescription: A dual-layer asynchronous network latency analyzer and observability tool.
Tags:
- network
- ping
- tui
ReleaseNotes: 'Full Changelog: v1.0.8...v1.0.9'
ReleaseNotesUrl: https://github.com/RaijuMounun/intqual/releases/tag/v1.0.9
ManifestType: defaultLocale
ManifestVersion: 1.12.0
