# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Crabby.ModbusConnect
PackageVersion: 0.6.0
PackageLocale: en-US
Publisher: Crabby
PublisherUrl: https://modbusconnect.com
PublisherSupportUrl: https://modbusconnect.com
PackageName: Modbus Connect
PackageUrl: https://modbusconnect.com
License: Proprietary
ShortDescription: Modbus TCP Client, Scanner & Logger
Description: >-
  Modbus Connect is a Modbus TCP client, network scanner, and data logger for
  monitoring and logging data from Modbus TCP/IP devices.
Tags:
  - modbus
  - modbus-tcp
  - plc
  - industrial
  - scada
  - automation
ManifestType: defaultLocale
ManifestVersion: 1.12.0
