# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Lokalize
PackageVersion: 26.03.90
InstallerType: nullsoft
UpgradeBehavior: install
FileExtensions:
- po
- pot
- ts
- xlf
- xliff
ProductCode: Lokalize
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/sdk/lokalize/release-26.04/windows/lokalize-release_26.04-2784-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: F4360FCE7C08DC30A354E4A404A2F26E7B21555E1961EE8AD58B84C342F4363C
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/sdk/lokalize/release-26.04/windows/lokalize-release_26.04-2784-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: F4360FCE7C08DC30A354E4A404A2F26E7B21555E1961EE8AD58B84C342F4363C
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
