# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Yandex.Disk
PackageVersion: 3.2.49.5187
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -silent -norestart
  SilentWithProgress: -silent -norestart
UpgradeBehavior: install
Protocols:
- telemost
- yandex-disk
ProductCode: YandexDisk2
ReleaseDate: 2026-07-28
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://disk.cdn.yandex.net/update/stable/790ac6f48265a855e8a39584eac2b4c2/YandexDisk30Setup_x86.exe
  InstallerSha256: 7C3EBC8733196B1673F5AA7041A1CCEB271900E80818B12F716E5563379FD3E9
- Architecture: x86
  Scope: machine
  InstallerUrl: https://disk.cdn.yandex.net/update/stable/790ac6f48265a855e8a39584eac2b4c2/YandexDisk30Setup_x86.exe
  InstallerSha256: 7C3EBC8733196B1673F5AA7041A1CCEB271900E80818B12F716E5563379FD3E9
  InstallerSwitches:
    Custom: -permachine
- Architecture: x64
  Scope: user
  InstallerUrl: https://disk.cdn.yandex.net/update/stable/dc24b474f0ad029f74fa341beb37b1ea/YandexDisk30Setup_x64.exe
  InstallerSha256: 95E33CCCA1641DEC786B5FF1C74DB6845CBEDBC35740F0E40F71A1367B07224A
- Architecture: x64
  Scope: machine
  InstallerUrl: https://disk.cdn.yandex.net/update/stable/dc24b474f0ad029f74fa341beb37b1ea/YandexDisk30Setup_x64.exe
  InstallerSha256: 95E33CCCA1641DEC786B5FF1C74DB6845CBEDBC35740F0E40F71A1367B07224A
  InstallerSwitches:
    Custom: -permachine
ManifestType: installer
ManifestVersion: 1.12.0
