# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.fy-NL
PackageVersion: 140.12.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-06-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.12.1esr/win32/fy-NL/Thunderbird%20Setup%20140.12.1esr.exe
  InstallerSha256: A7C52EC4342B4D8E3024CF15718B268C2216C7B4BAA853547179D57469A3186C
  ProductCode: Mozilla Thunderbird 140.12.1 (x86 fy-NL)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 fy-NL)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.12.1esr/win64/fy-NL/Thunderbird%20Setup%20140.12.1esr.exe
  InstallerSha256: 480473C334FA69D6FE94FF1BB028C3D643CD21325AC58FE4A7C19BB152631609
  ProductCode: Mozilla Thunderbird 140.12.1 (x64 fy-NL)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 fy-NL)
ManifestType: installer
ManifestVersion: 1.12.0
