# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EligianLabs.PIICrawlerCLI
PackageVersion: 26.0831.2102
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: piicrawler.exe
Commands:
- piicrawler
ReleaseDate: 2026-08-31
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: AD543F2FB9CB06F5A5B3EF31644C0F91B4D579E5319DB1FD894443418104F972
ManifestType: installer
ManifestVersion: 1.12.0
