# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dprint.dprint
PackageVersion: 0.56.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dprint.exe
ReleaseDate: 2026-08-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.56.1/dprint-x86_64-pc-windows-msvc.zip
  InstallerSha256: D2C5EE170FF88C0B16EA1F5F214E4D74877C7EDB9CA701DA5C9851C0C1EF9338
- Architecture: arm64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.56.1/dprint-aarch64-pc-windows-msvc.zip
  InstallerSha256: 11163770683A21283F0F4ADCE645F055295736148308A12B65CE1F8E613BFB66
ManifestType: installer
ManifestVersion: 1.12.0
