# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Vishnuj-n.ForgeCLI
PackageVersion: 1.0.1
PackageLocale: en-US
Publisher: Vishnu J Narayanan
PublisherUrl: https://github.com/Vishnuj-n
PublisherSupportUrl: https://github.com/Vishnuj-n/forge/issues
PackageName: ForgeCLI
PackageUrl: https://github.com/Vishnuj-n/forge
License: MIT
ShortDescription: Forge is a Windows CLI tool for creating new projects from reusable templates by running real ecosystem commands like npm and uv.
Tags:
- automation
- cli
- code-generation
- productivity
- template-engine
- tool
- windows
ReleaseNotesUrl: https://github.com/Vishnuj-n/forge/releases/tag/v1.0.1
InstallationNotes: Restart your terminal to ensure the 'forge' command is available in PATH.
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/Vishnuj-n/forge/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0

