# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sogou.SogouInput
PackageVersion: 16.7.0.4673
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- sgreg
FileExtensions:
- scel
- scpf
- ssf
ProductCode: Sogou Input
ReleaseDate: 2026-08-03
Installers:
- Architecture: x86
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.7.0.4673_0.exe
  InstallerSha256: 7B5917E93E7DA04AD1BBB00615B83C94C9FD49ADE12293152888D0DF434FAE7B
- Architecture: x64
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.7.0.4673_0.exe
  InstallerSha256: 7B5917E93E7DA04AD1BBB00615B83C94C9FD49ADE12293152888D0DF434FAE7B
- Architecture: arm
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.7.0.4673_0.exe
  InstallerSha256: 7B5917E93E7DA04AD1BBB00615B83C94C9FD49ADE12293152888D0DF434FAE7B
- Architecture: arm64
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.7.0.4673_0.exe
  InstallerSha256: 7B5917E93E7DA04AD1BBB00615B83C94C9FD49ADE12293152888D0DF434FAE7B
ManifestType: installer
ManifestVersion: 1.12.0
