# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Oracle.OCI-CLI
PackageVersion: 3.94.0
PackageLocale: en-US
Publisher: Oracle
PublisherUrl: https://github.com/oracle
PublisherSupportUrl: https://github.com/oracle/oci-cli/issues
PackageName: Oracle Cloud Infrastructure CLI
PackageUrl: https://github.com/oracle/oci-cli
License: Dual License (UPL-1.0 / Apache-2.0)
LicenseUrl: https://github.com/oracle/oci-cli/blob/HEAD/LICENSE.txt
Copyright: Copyright (c) 2016, 2021, Oracle and/or its affiliates.  All rights reserved.
CopyrightUrl: https://github.com/oracle/oci-cli/blob/master/LICENSE.txt
ShortDescription: Command Line Interface for Oracle Cloud Infrastructure
Tags:
- bare-metal
- cli
- cloud
- infrastructure
ReleaseNotes: |-
  Added
  - Support for Crypto Posture Assessment lifecycle, reporting, and analysis operations in Data Safe service.
    - oci data-safe crypto-assessment
  - Support for Recurrence Maintenance Windows through new maintenance-window-schedule fields in APM Availability Monitoring service.
    - oci apm-synthetics monitor
  - Marketplace Publisher
    - Support for Administrator Artifact, Administrator Publisher, Customer Instance Report Export, and Marketplace Administrator operations.
      - oci marketplace-publisher administrator-artifact
      - oci marketplace-publisher administrator-publisher
      - oci marketplace-publisher customer-instance-report-export
      - oci marketplace-publisher marketplace-administrator
      - oci marketplace-publisher publisher create
      - oci marketplace-publisher listing-revision update-listing-revision-banner-content
    - Support for new optional parameters --instance-ocid, --listing-id, --package-version, --realm, --region-parameterconflict, --shape, --status, --tenant-admin-domain, --time-instance-creation-from-date, --time-instance-creation-to-date, --time-instance-termination-from-date and --time-instance-termination-to-date for listing customer instance report records.
      - oci marketplace-publisher customer-instance-report-record-collection list-customer-instance-report-records
    - Support for new optional parameters for listing revision and listing revision attachment commands.
      - oci marketplace-publisher listing-revision create-listing-revision-create-oci-listing-revision-details --demo-url --partner-registration-url --self-paced-training-url --term-id
      - oci marketplace-publisher listing-revision update-listing-revision-update-oci-listing-revision-details --demo-url --partner-registration-url --self-paced-training-url --term-id
      - oci marketplace-publisher listing-revision-attachment create-listing-revision-attachment-create-customer-success-attachment --source-type
      - oci marketplace-publisher listing-revision-attachment create-listing-revision-attachment-create-related-document-attachment-details --is-oracle-users-only --source-type --source-url
      - oci marketplace-publisher listing-revision-attachment create-listing-revision-attachment-create-review-support-document-attachment --source-type
      - oci marketplace-publisher listing-revision-attachment create-listing-revision-attachment-create-screen-shot-attachment-details --source-type
      - oci marketplace-publisher listing-revision-attachment create-listing-revision-attachment-create-supported-service-attachment --source-type
  - Functions service
    - Support for source-specific function creation and update commands.
      - oci fn function
    - Support for Functions Runtime resources.
      - oci fn runtime
      - oci fn runtime-version
  - Support for Bring Your Own Reservations for several create and update operations via capacityReservationIds in Data Science service
    - oci data-science compute-target
    - oci data-science job
    - oci data-science job-run
    - oci data-science model-deployment
    - oci data-science notebook-session
    - oci data-science project
    - oci data-science work-request
  - Support for Routing Profiles and Model Discovery in Generative AI service.
    - oci generative-ai routing-profile
    - oci generative-ai routing-profile-collection
    - oci generative-ai model-discovery-collection

  Changed
  - [BREAKING] CLI group renamed from oci distributed-database-v26 to oci distributed-database for Globally Distributed Database service
  - --credentials is now an optional parameter for reactivating a previously deactivated target database in Data Safe service
    - oci data-safe target-database activate
  - [BREAKING] Removed required parameter --date-range for listing customer instance report records in Marketplace Publisher service
    - oci marketplace-publisher customer-instance-report-record-collection list-customer-instance-report-records

  File Checksums (SHA256)
  oci-cli-3.94.0.zip 9c7c4b8b61f303b9adba77d2caa5d31a9e32683a9e181ad0e96a49d4918c764d
  oci-cli-3.94.0-Oracle-Linux-10-Offline.zip 35b468f84bb075b6e33e59fc09f61ed1d3d8fb9590a3e0fb2021bf5da04d38bc
  oci-cli-3.94.0-Windows-Server-2019-Offline.zip 4392f7addcfe26c8103b81518cea9401483146ea8c9d29ffe69a231742416431
  oci-cli-3.94.0-Windows-Server-Installer.msi 78afd1a15b910aad9ad44c29cdc3b4bd61687b46c33b43d3cf142c0e12d7f769
  oci-cli-3.94.0-Ubuntu-22.04-Offline.zip c38eed4235471cbe734e05144adc19aaf1cc4f54c628cb82f0ea558564f6210e
  oci-cli-3.94.0-Ubuntu-20.04-Offline.zip c9dc58d95f3ece8fa56e15404e4691292ddb04d1023a6c2360baaba0c1ef2097
  oci-cli-3.94.0-Oracle-Linux-9-Offline.zip 16ee03489516aa347cb6cab8eb80ef9078a549e288b58db998f8adb6eed28962
  oci-cli-3.94.0-Windows-Server-2016-Offline.zip 0bc2ca15455618d862cb2cfae8155fdba449d1d2174f1586437a78e858825b06
  oci-cli-3.94.0-Oracle-Linux-8-Offline.zip c512d55b5d0eb027a0526c80e93364204dab5c3cc07658b1eeaa2d3cfa2d4424
ReleaseNotesUrl: https://github.com/oracle/oci-cli/releases/tag/v3.94.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
