# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: hrzlgnm.mdns-browser
PackageVersion: 2.3.1
PackageLocale: en-US
Publisher: hrzlgnm
PublisherUrl: https://github.com/hrzlgnm
PublisherSupportUrl: https://github.com/hrzlgnm/mdns-browser/issues
PrivacyUrl: https://github.com/hrzlgnm/mdns-browser/blob/main/PRIVACY.md
Author: hrzlgnm
PackageName: mdns-browser
PackageUrl: https://github.com/hrzlgnm/mdns-browser
License: MIT
LicenseUrl: https://github.com/hrzlgnm/mdns-browser/blob/HEAD/LICENSE
Copyright: Copyright (c) 2024 hrzlgnm
ShortDescription: mDNS Browser
Description: mDNS Browser
Tags:
- auto-update
- mdns
- mdns-sd
- rust
- svelte
- sveltekit
- tauri
ReleaseNotes: |-
  2.3.1 (2026-09-16)
  Bug Fixes
  - detect release-please commits in CI skip check (#2729) (fbd3a9d)
  - exclude tauri packages from release age restrictions (#2722) (bbf321f)
  Dependencies
  - update ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1 docker digest to 5d2ed62 (#2728) (dd379e4)
  - update ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1 docker digest to 715bfd8 (#2726) (de7d844)
  - update tauri monorepo to v2.4.5 (#2721) (1d92af3)
  - update ubuntu:latest docker digest to 5cf058a (#2724) (506cc9b)
  - update ubuntu:latest docker digest to cd21a4f (#2727) (d51369b)
  Continuous Integration
  - skip heavy jobs on release-tag pushes (#2725) (2f0b68c)
ReleaseNotesUrl: https://github.com/hrzlgnm/mdns-browser/releases/tag/v2.3.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
