# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: mikf.gallery-dl.Nightly
PackageVersion: 2026.08.29
InstallerType: portable
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-08-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/gdl-org/builds/releases/download/2026.08.29/gallery-dl_windows_x86.exe
  InstallerSha256: E873629960311FB271B6CEF8A5A73702B627F4E5DF7576709A68566C4932F917
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/gdl-org/builds/releases/download/2026.08.29/gallery-dl_windows.exe
  InstallerSha256: B50724DD8C2B39C9F647F852927F8D8E4E55A475E6BE4F0728C9B093015581F2
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.12.0
