# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: mjishnu.Raven
PackageVersion: "1"
PackageLocale: en-US
Publisher: mjishnu
PackageName: Raven
PackageUrl: https://github.com/mjishnu/Raven
License: Apache-2.0
ShortDescription: A modern, native Windows application that serves as a fully-featured alternative to the Microsoft Store. It can do everything the official store does — search, download, install, and update apps — while also adding powerful capabilities.
Description: A modern, native Windows application that serves as a fully-featured alternative to the Microsoft Store. It can do everything the official store does — search, download, install, and update apps — while also adding powerful capabilities like sideloading external UWP/MSIX packages, exporting Store apps for offline use, and bandwidth-saving delta downloads.
Tags:
- microsoft-store
- microsoftstore
- ms-store
- msstore
- alternate-client
- alternateclient
- alternate-frontend
- alternatefrontend
ManifestType: defaultLocale
ManifestVersion: 1.12.0