# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ChrisRizzitello.BlackChocobo
PackageVersion: continuous
PackageLocale: en-US
Publisher: Chris Rizzitello
PublisherUrl: https://github.com/sithlord48
PublisherSupportUrl: https://github.com/sithlord48/blackchocobo/issues
PackageName: Black Chocobo
PackageUrl: https://github.com/sithlord48/blackchocobo
License: GPL-3.0
ShortDescription: A Save Editor for Final Fantasy 7
Tags:
- c-plus-plus
- cross-platform
- ff7
- final-fantasy-vii
- game-development
- hacktoberfest
- qt
- save-editor
ManifestType: defaultLocale
ManifestVersion: 1.12.0
