# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.KMines
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: kmines
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kmines/master/windows/kmines-master-1012-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 52E95ABDEB47F3BB77AE6A219086633775655C6E5C07F3E84DD05C4CC9525E54
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/kmines/master/windows/kmines-master-1012-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 52E95ABDEB47F3BB77AE6A219086633775655C6E5C07F3E84DD05C4CC9525E54
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
