# Created with YamlCreate.ps1 v2.7.1 $debug=NVS1.CRLF.7-6-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: TraeProxy.TraeProxy
PackageVersion: 2.1.0
PackageLocale: en-US
# Publisher:
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
# PackageName:
# PackageUrl:
License: Freeware
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: As an underlying HTTPS transparent gateway, breaking through single-API lock-in. Fully enabling custom BaseURL freedom without compromising the entire system.
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: locale
ManifestVersion: 1.12.0
