# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: tritant.MiniMediaEdit
PackageVersion: "1.0"
InstallerType: inno
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Gyan.FFmpeg
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tritant/MiniMediaEdit/releases/download/1.0/MiniMediaEdit-1.0-setup.exe
  InstallerSha256: DDCB8D948074ACBA235997E7F5140EB8ED6801604E54BA2B9BA34C0BE2166792
ManifestType: installer
ManifestVersion: 1.12.0
