# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.442
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-03-26
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.442/fabric_Windows_i386.zip
  InstallerSha256: 343BFEE0A6A2A44B4511F65ABD723317676F6BBCC245446A2B1A8E229FFB93DD
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.442/fabric_Windows_x86_64.zip
  InstallerSha256: D1A4751F5BEC7D6A8FF792CB8ABEC270DEB2CA7140FCB60BE7A351E9E4C2F9AA
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.442/fabric_Windows_arm64.zip
  InstallerSha256: F085D2686516453D14AED8DA455146C34B21A2DCE59C5A21C4BE90D66B491750
ManifestType: installer
ManifestVersion: 1.12.0
