# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Proton.ProtonMail
PackageVersion: 1.13.3
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Protocols:
- proton-inbox
ProductCode: proton_mail
ReleaseDate: 2026-06-12
Installers:
- Architecture: x64
  InstallerUrl: https://proton.me/download/mail/windows/1.13.3/ProtonMail-desktop.exe
  InstallerSha256: 2A9B6B1BD09DEBF2BBBEAAF40BC02AD9191126FE08F0C42DC58F32AC6CA770FB
ManifestType: installer
ManifestVersion: 1.12.0
