# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: buchen.portfolio
PackageVersion: 0.83.0
PackageLocale: de-DE
Publisher: Andreas Buchen
PublisherUrl: http://abuchen.name
PublisherSupportUrl: https://github.com/buchen/portfolio/issues
PackageName: Portfolio Performance
PackageUrl: https://github.com/buchen/portfolio
License: EPL-1.0
LicenseUrl: https://github.com/buchen/portfolio/blob/master/LICENSE
ShortDescription: Portfolio Performance berechnet die Gesamtperformance Ihres Anlageportfolios.
ReleaseNotes: |-
  - Neu: Top-Contributors-Widgets im Dashboard hinzugefügt.
  - Neu: Unterschiedliche Ticker für historische und aktuelle Kursquellen konfigurierbar.
  - Neu: Farbschema „Vivid“ hinzugefügt.
  - Neu: Werkzeug zum Nachpflegen der Ex-Daten bestehender Dividendenbuchungen hinzugefügt.
  - Neu: Optionale Anzeige des Datums der letzten Transaktion in Konten und Portfolios.
  - Neu: FIRE-Berechnungs-Widget (Financial Independence, Retire Early) hinzugefügt.
  - Neu: PDF-Importer für Ayvens Bank und Tradegate (Kontoauszüge) hinzugefügt.
  - Verbesserung: Eurostat-HICP-Datenquelle auf den neuen Datensatz umgestellt.
  - Verbesserung: Ex-Daten werden beim PDF-Import neuer Dividendenbuchungen automatisch ermittelt.
  - Verbesserung: PDF-Importer für Trade Republic, ING-DiBa, Scalable Capital, DKB, DZ Bank Gruppe, Gladbacher Bank AG, NIBC Bank, Raiffeisen Bankgruppe, S Broker, Santander Consumer Bank, DAB und Deutsche Bank verbessert.
  - Verbesserung: Die erste Zeile der Treemap-Beschriftungen für bessere Lesbarkeit fett dargestellt.
  - Fehlerbehebung: Importer ermöglicht das erneute Markieren von Einträgen für den Import.
  - Fehlerbehebung: Abdocken des Portfolio-Fensters wird verhindert.
ReleaseNotesUrl: https://github.com/buchen/portfolio/releases/tag/0.83.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
