Id: Helbling.MediaApp
Version: 3.14.1
ManifestType: defaultLocale
ManifestVersion: 1.5.0
Publisher: HELBLING Verlagsgesellschaft m.b.H.
PackageName: HELBLING Media App
ShortDescription: Access multimedia content for HELBLING educational products.
Description: The HELBLING Media App provides fast access to media for textbooks, readers, and sheet music.
