# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 152.1.96.10
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-08-24
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 635A0A6371D6F909BBBC5CA0E2DDEBC6218DD49CE8BF5244A89C086850EA3D7F
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 789E396CED06D0DA99E25F6E35D5BAAAF4BC91C0AD80755E36E3A8BB406D9A8E
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 30D2F9FA8AFB5C83AD1229F5AA8070B1A083EFA5CCEC3B7AC93C596111054288
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 15775DFC8CCBE4596EDCE71DC4E0524222E7101B60E6323071690F7D650E69B8
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 55E037BE2B56B566E7EFA096F3B87BD22F69C917FB2699BF5B23E53B69332F14
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.10/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 5059C1686119341ED413FABED333CF27D2897D80F3D5797B1BECE40961FA0FE8
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
