# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Microsoft.WindowsBatteryLifeTool
PackageVersion: 2.0.19
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
ElevationRequirement: elevationRequired
UpgradeBehavior: install
ReleaseDate: 2026-08-10
AppsAndFeaturesEntries:
- DisplayName: WindowsBatteryLifeTool
  Publisher: Microsoft Corporation
  ProductCode: '{A0CEE8A7-E3D7-4CB5-BAD1-551B3599481A}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/WebBrowsingPowerRelease/releases/download/v2.0.19/WindowsBatteryLifeTool-2.0.19.msi
  InstallerSha256: 6F7BE23D321187F5A4178F714C47E6B0207C3C5C8CF300057E2C38822F634A35
  ProductCode: '{A0CEE8A7-E3D7-4CB5-BAD1-551B3599481A}'
ManifestType: installer
ManifestVersion: 1.10.0
