# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-XChangeLite
PackageVersion: 11.0.1.0
PackageLocale: zh-CN
License: 专有软件
ShortDescription: PDF-XChange Printer Standard 虚拟 PDF 打印机的精简版本。
Description: |-
  PDF-XChange Printer Lite 是 PDF-XChange Printer Standard 的精简版本，用于创建和虚拟打印行业标准的 PDF 文件。PDF-XChange Printer Lite 兼容几乎所有 Windows 应用程序（如 MS Word、Excel 和 AutoCAD）的文件。它拥有优化的混合转换引擎，显著提升了图像及基于图像的文本字符的转换质量，并支持打印到 GDI 和 XPS。PDF-XChange Printer Lite 以虚拟打印机的形式安装，可生成完全兼容、符合行业标准的原生 PDF 文件。其创建的文件包含可搜索的文本，提高了搜索、选择和编辑文件的效率。
  安装 PDF-XChange Printer Lite 后，当您在应用程序中查看文档时，只需使用软件中的打印功能，并选择 PDF-XChange Printer Lite 作为所用打印机。随后，文档将打印为 PDF。如本手册后续章节所述，您可以通过一系列可调设置来确定所打印文档的参数。PDF-XChange Printer Lite 不需要额外的“插件”或软件。不过，我们建议您安装我们的另一款产品 PDF-XChange Editor，以便查看和操作使用 PDF-XChange Printer Lite 创建的文件。该软件完全免费，且两款产品旨在协同工作。
Tags:
- pdf
- 打印
- 打印机
- 转换
Documentations:
- DocumentLabel: 帮助
  DocumentUrl: https://help.pdf-xchange.com/
- DocumentLabel: 知识库
  DocumentUrl: https://www.pdf-xchange.com/knowledgebase
ManifestType: locale
ManifestVersion: 1.12.0
