# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CraftDocs.CraftAgents
PackageVersion: 0.10.1
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- craftagents
ProductCode: 61dc82ee-e3b9-557b-98c4-20b9178a0f78
ReleaseDate: 2026-06-02
Installers:
- Architecture: x64
  InstallerUrl: https://agents.craft.do/electron/0.10.1/Craft-Agents-x64.exe
  InstallerSha256: 1D6C0B03BCFF2615BD4857C25882A43E8A3066EA8765A648ADDABAB1924D6CB0
ManifestType: installer
ManifestVersion: 1.12.0
