# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.nb-NO
PackageVersion: 153.1.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-08-18
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.1.0esr/win32/nb-NO/Thunderbird%20Setup%20153.1.0esr.exe
  InstallerSha256: 28AF968576141394243F08EEDC0FD9881276CCC5AB840A08C187A1327331E208
  ProductCode: Mozilla Thunderbird 153.1.0 (x86 nb-NO)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 nb-NO)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.1.0esr/win64/nb-NO/Thunderbird%20Setup%20153.1.0esr.exe
  InstallerSha256: E924D5B07D0760AB35DAD7C1900650EAAB900DCBB4204D961BE5B2717F2BBC10
  ProductCode: Mozilla Thunderbird 153.1.0 (x64 nb-NO)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 nb-NO)
ManifestType: installer
ManifestVersion: 1.12.0
