# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LucidLink.LucidLink
PackageVersion: 3.7.8641
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: LUCID_INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- lucidlink
ProductCode: '{0351FF4B-B805-4666-80EF-4D76693C1DD9}'
ReleaseDate: 2026-08-17
AppsAndFeaturesEntries:
- UpgradeCode: '{8201A019-C7B9-4DF4-9465-B36A9B9B1D6D}'
Installers:
- Architecture: x64
  InstallerUrl: https://releases.lucidlink.com/prod/win/lucidlink-3.7.8641-x64.msi
  InstallerSha256: F79B1CC1005692D272544B9D9196BDD94F7BF93006EFEF3BB377258348AD7651
ManifestType: installer
ManifestVersion: 1.12.0
