# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Opera.Opera.Dev
PackageVersion: 131.0.5877.0
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- operadeveloper
FileExtensions:
- crx
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup.exe
  InstallerSha256: 10B4F298B6365AFDA7662F24A907D8717118870379CF1FD22B4C89F1E7FFAAAA
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup.exe
  InstallerSha256: 10B4F298B6365AFDA7662F24A907D8717118870379CF1FD22B4C89F1E7FFAAAA
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup_x64.exe
  InstallerSha256: AB4A58BEAA65D0217625AFCC8358E53F9C55DA5729F377A1508ECC3A7644C9F6
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup_x64.exe
  InstallerSha256: AB4A58BEAA65D0217625AFCC8358E53F9C55DA5729F377A1508ECC3A7644C9F6
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup_arm64.exe
  InstallerSha256: 9AD76A2979400B7797444C97EE61335C59177C4FD5827E6CBD0CB58C5221360B
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/131.0.5877.0/win/Opera_Developer_131.0.5877.0_Setup_arm64.exe
  InstallerSha256: 9AD76A2979400B7797444C97EE61335C59177C4FD5827E6CBD0CB58C5221360B
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.12.0
