# Automatically updated by the winget bot at 2026/May/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CCPGames.EVEOnline
PackageVersion: 1.14.1
InstallerType: exe
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://launcher.ccpgames.com/eve-online/release/win32/x64/eve-online-latest+Setup.exe
  InstallerSha256: FF6836D579250CB41E959DF6A4EEFAA87E75C021935AB54E0FCCAD6EA08A3D64
  ProductCode: "eve-online"
ManifestType: installer
ManifestVersion: 1.12.0
