# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SimplyCA.Typeless
PackageVersion: 1.3.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
FileExtensions:
- typeless
ProductCode: 801bda48-0940-5127-a918-a53339b92128
ReleaseDate: 2026-04-30
Installers:
- Architecture: x64
  InstallerUrl: https://typeless-static.com/desktop-release/Typeless-1.3.0-x64-Setup.exe
  InstallerSha256: 6AB95DD126D45343130743467A3BDCCF05425B3120383E365B56A27FD3F1CFDD
ManifestType: installer
ManifestVersion: 1.12.0
