# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.an
PackageVersion: "156.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-15
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/156.0/win32/an/Firefox%20Setup%20156.0.exe
  InstallerSha256: 95B6CA6242EE1FA45527F380ED012D7FA6EFCDD618EB17C79D4E44964B106280
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/156.0/win64/an/Firefox%20Setup%20156.0.exe
  InstallerSha256: D0848E65B3685BA31B345C881DD8C10D1C119CBAC2B82D4AB48E688E40BDC871
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/156.0/win64-aarch64/an/Firefox%20Setup%20156.0.exe
  InstallerSha256: 2C28C47D18AC03E5C8D1A6C6765724B55743DD796A9927C4A9926090A1C7BD30
ManifestType: installer
ManifestVersion: 1.12.0
