# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: UNIkeEN.SJMCL
PackageVersion: 1.1.3
PackageLocale: zh-CN
Publisher: SJMCL
PublisherUrl: https://mc.sjtu.cn/
PublisherSupportUrl: https://github.com/UNIkeEN/SJMCL/issues
Author: 上海交通大学 Minecraft 社
PackageName: SJMCL
PackageUrl: https://mc.sjtu.cn/sjmcl
License: GPL-3.0
LicenseUrl: https://github.com/UNIkeEN/SJMCL/blob/HEAD/LICENSE
Copyright: 2026 © SJMCL Team
ShortDescription: 新一代开源跨平台 Minecraft 启动器
Description: SJMC Launcher 是一款基于 Tauri 框架打造的现代化、跨平台 Minecraft 启动器，由上海交通大学 Minecraft 社的成员自主开发。
Tags:
- mc
- minecraft
- 我的世界
ReleaseNotes: |-
  - 🌟 支持将游戏资源快捷安装到任意实例、快捷安装整合包，优化资源下载的交互体验。#1659 #1677 @UNIkeEN
  - 🌟 支持使用自定义 Authlib Injector 启动游戏。#1664 @UNIkeEN
  - 🐛 修复实例资源包页面前端状态无法更新的问题。#1673 @baiyuansjtu
  - 🛠 调整前端页面折叠面板的响应区域。#1672 @1357310795 @UNIkeEN
  - 📦 终止启动器对 Windows 7 的支持。#1680 @3gf8jv4dv @xunying123
  - 工作流：
    - 修复 Winget 发版工作流。#1667 #1668 @pangbo13
ReleaseNotesUrl: https://github.com/UNIkeEN/SJMCL/releases/tag/v1.1.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
