# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ja
PackageVersion: 153.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-07-28
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win32/ja/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: 43446E70A138EAEA996F75F378EE8012A57AF4CA5297334168F291F7DD0782EF
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win64/ja/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: 46E1F2EAA9CE44E4ED40302EC5FF97F5458A2640304B75ABD41B9264AFA933FA
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win64-aarch64/ja/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: B82AE32DD7A53E3ECE682D62A62EC091CA4A3BA04D2BF6380F6055F364092CE5
ManifestType: installer
ManifestVersion: 1.12.0
