# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.ff
PackageVersion: 140.9.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2026-04-07
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.9.1esr/win32/ff/Firefox%20Setup%20140.9.1esr.exe
  InstallerSha256: 81A150275E5930C4F53B9B84329F1685E4336B0B6F4C2D066566CB7D88B70CA7
  ProductCode: Mozilla Firefox 140.9.1 ESR (x86 ff)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.9.1esr/win64/ff/Firefox%20Setup%20140.9.1esr.exe
  InstallerSha256: F4A60114E97FBCB4BB34462469643BAAC27C59AB278ABF1EB0FCF237D3D78A4A
  ProductCode: Mozilla Firefox 140.9.1 ESR (x64 ff)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.9.1esr/win64-aarch64/ff/Firefox%20Setup%20140.9.1esr.exe
  InstallerSha256: 8FF531533DE0E9A210181935D377774A2DBC1AD0D8B3780147A61CED2C4DACDF
  ProductCode: Mozilla Firefox 140.9.1 ESR (arm64 ff)
ManifestType: installer
ManifestVersion: 1.12.0
