# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Konsole
PackageVersion: 26.07.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Konsole
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/konsole/master/windows/konsole-master-4684-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 24ED15AA4C971AF73AF9AF8C7194114E958DB59218632183857D15C787C35A74
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/konsole/master/windows/konsole-master-4684-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 24ED15AA4C971AF73AF9AF8C7194114E958DB59218632183857D15C787C35A74
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
