# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.fur
PackageVersion: "149.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/149.0b3/win32/fur/Firefox%20Setup%20149.0b3.exe
  InstallerSha256: D2272844670DA34BEF35E92427A171FA31BE87C6F3E4C9FC92F99A49C4CD0370
  ProductCode: Firefox Developer Edition 149.0 (x86 fur)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/149.0b3/win64/fur/Firefox%20Setup%20149.0b3.exe
  InstallerSha256: 2683B74455FC6B0A8CAC0BD6177791229B606163245B4BEBA1A4577B381CBBC2
  ProductCode: Firefox Developer Edition 149.0 (x64 fur)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/149.0b3/win64-aarch64/fur/Firefox%20Setup%20149.0b3.exe
  InstallerSha256: 5C6077C4ECFF7ACE9D9ED286E77C2082CB6D860030CA3C958A14367C6BA611B0
  ProductCode: Firefox Developer Edition 149.0 (arm64 fur)
ManifestType: installer
ManifestVersion: 1.12.0
