# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FeiXiangShi.Rustle
PackageVersion: 0.3.2
InstallerType: portable
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- rustle
FileExtensions:
- flac
- m4a
- mp3
- ogg
- opus
- wav
ReleaseDate: 2026-04-20
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Fei-xiangShi/Rustle/releases/download/v0.3.2/rustle-windows-x86_64.exe
  InstallerSha256: 09FF1D6F5A3069AFF24259FADA656A7B3902FC288EE3543F1AFA350CF385F5F2
ManifestType: installer
ManifestVersion: 1.12.0
