# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GioPalusa.SRTDownloader
PackageVersion: 0.1.1
InstallerType: portable
Commands:
- srt-download
ReleaseDate: 2026-06-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GioPalusa/SRT-downloader/releases/download/v0.1.1/srt-download-windows-x64.exe
  InstallerSha256: CDF595C8D04FBA836B25B40973622339AE8C253FC7FE27A84D34D822E84B7FFF
ManifestType: installer
ManifestVersion: 1.12.0
