# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Multica.MulticaCLI
PackageVersion: 0.4.42
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: multica.exe
Commands:
- multica
ReleaseDate: 2026-09-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/multica-ai/multica/releases/download/v0.4.42/multica-cli-0.4.42-windows-amd64.zip
  InstallerSha256: A3D65A06B66BB68AA86AC20EB350A9432C6A72AFDDC8046BD754A7C36D9C525B
- Architecture: arm64
  InstallerUrl: https://github.com/multica-ai/multica/releases/download/v0.4.42/multica-cli-0.4.42-windows-arm64.zip
  InstallerSha256: 8F11A04AE0B6EC933633ECF44CF5BC7EAC43386BD6D87D376801BC08E7456267
ManifestType: installer
ManifestVersion: 1.12.0
