# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.kab
PackageVersion: 140.9.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-04-07
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.9.1esr/win32/kab/Thunderbird%20Setup%20140.9.1esr.exe
  InstallerSha256: 25F258C8709A25D3E5449DEA27AEAAEB540B3441B9D91BE7FA2CD591EAD395F0
  ProductCode: Mozilla Thunderbird 140.9.1 (x86 kab)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 kab)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.9.1esr/win64/kab/Thunderbird%20Setup%20140.9.1esr.exe
  InstallerSha256: C66BF987CF89EF3599F12F9DF3C27AFC0F0DA1BC3B6447112A85DCCAF9781D37
  ProductCode: Mozilla Thunderbird 140.9.1 (x64 kab)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 kab)
ManifestType: installer
ManifestVersion: 1.12.0
