# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.Agent
PackageVersion: v1.58.0
InstallerType: portable
Commands:
- docker-agent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.58.0/docker-agent-windows-amd64.exe
  InstallerSha256: 0C6D138579EC3B90116711F1B7158384554C2E7BCA5197972DB4A89D74E8B10C
- Architecture: arm64
  InstallerUrl: https://github.com/docker/docker-agent/releases/download/v1.58.0/docker-agent-windows-arm64.exe
  InstallerSha256: 2828A819AB7E62C3F055D1D6F029B5AB6EAEC709D6BC608D705B5A6696DCC64B
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-11
