# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: orbatschow.kontext
PackageVersion: 2.0.0
PackageLocale: en-US
Publisher: Orbatschow
PublisherUrl: https://orbat.sh
Author: Orbatschow
PackageName: kontext
PackageUrl: https://github.com/orbatschow/kontext/
License: Apache-2.0
LicenseUrl: https://github.com/orbatschow/kontext/blob/master/LICENSE
ShortDescription: Declarative kubeconfig management within a single binary.
Description: Kontext is a single binary application, that takes yet another approach on kubeconfig management.
Tags:
- cli
- devops-tools
- golang
- kubernetes
- context
- kubeconfig
- portable
- terminal
ReleaseNotes: |-
  ## Changelog
  * 47335f07415eca220181e1628f988627d4b633f9 Merge pull request #34 from orbatschow/feature/command-descriptions
  * ec01c9c38870bf890b96941869a41e8d69615863 Merge pull request #35 from orbatschow/feature/slog
  * 9fc06fcf18df645588d7161714891c02e1d879f8 Merge pull request #36 from orbatschow/feature/lint
  * b472cf0d58a1ff96d84161151a90bdc3b777270c Merge pull request #37 from orbatschow/fix/tests
  * c5f0da53d81ffa1293e18e251368a1e407ec36f5 WIP: command line completions
  * ad055970bdb4ff0af31968ae68fa7f65e5de306b feat!: merge pull request #33 from orbatschow/feature/shell-completion
  * 1824276d8c67ef31f61700e299d58fbe913244f7 feat!: refactor configuration file, this includes a breaking change for renaming keys
  * 8a60f28303c93d002ad268d55f8ce2d7311385c6 feat: add validation to config file
  * d25db2b1d0b0c2c8fa8597dddb123ad0c8efe16f feat: implement autocomplete
  * f18b8fdd3af89ea987f3988dfd6aaeda38929513 feat: merge
  * 3001d54a6b65385df55bf04220104a9d8f21089f feat: remove backup function, it doesn't make a lot of sense
  * 319d78881df86a1d2042445b4a1649de422a0d5e feat: remove outdated linter
  * 40de46dba775f04923cded62babf691b7d6b4212 feat: rework descriptions, fix build
  * 18d28957759fccb8cb87e2ac308354d112c61175 feat: update gitignore
  * 4ace157a195a21bc722849ead1a5cafc1a8e4773 feat: upgrade to golang 1.25.0
  * a9e344ae54dbdea658a84ac25b157ee437bba920 feat: use slog
  * f7b81ddacfdb3dbc8ccd041b2d179ede50f99849 feat: use slog
  * ffd3f2a44e0810eafa5a58b24ebed9eaf2c74073 fix: outdated linters and linting issues
  * 2929070d3e3552b809fe549272471152f244c67f fix: tests


ReleaseNotesUrl: https://github.com/orbatschow/kontext/releases/tag/v2.0.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
