# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Koyubi.SKK
PackageVersion: 0.1.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ProductCode: '{A7B3C4D5-E6F7-4890-AB12-CD34EF567890}_is1'
ReleaseDate: 2026-03-01
AppsAndFeaturesEntries:
- DisplayVersion: 0.1.1
  ProductCode: '{A7B3C4D5-E6F7-4890-AB12-CD34EF567890}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Koyubi'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/barewalker/koyubi/releases/download/v0.1.2/koyubi-0.1.1-setup.exe
  InstallerSha256: 6D27B5C8539CB961656F952864B5E943566C844DB1691A62610CF4B42A55516C
ManifestType: installer
ManifestVersion: 1.12.0
