# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.kn
PackageVersion: "154.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-08-18
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/154.0/win32/kn/Firefox%20Setup%20154.0.exe
  InstallerSha256: 679130E6B20DB496D114D269C8DAFA5322D4F00345EFB84D5F7E279E40E6CF73
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/154.0/win64/kn/Firefox%20Setup%20154.0.exe
  InstallerSha256: 5D3B44BAFA2C6D0EEB048F2CCD7A865476B29E0E7FF7259608DE84FA04A11FE4
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/154.0/win64-aarch64/kn/Firefox%20Setup%20154.0.exe
  InstallerSha256: F11125045FF946F787BD7B2041A9BB69C31EC0B35593E94A0E7AA7F7BF832AB1
ManifestType: installer
ManifestVersion: 1.12.0
