# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SylvainRougeaux.Metatogger
PackageVersion: 7.7.2.1
InstallerLocale: en-US
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{501C64A8-77D5-4BDB-9962-5DBDA306176F}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://api.luminescence-software.org/download.php?software=metatogger&installer=msi&version=7721
  InstallerSha256: E6893D57D77DEA3F8419E64F192B13CD846FD8D214D1CE71E09FB8244AEC2EF2
ManifestType: installer
ManifestVersion: 1.12.0
