# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: HoshimonoDesign.FullyLocalTranscribe
PackageVersion: 4.5.2
InstallerLocale: ja-JP
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: 完全ローカル文字起こしツール.exe
  PortableCommandAlias: fullylocaltranscribe
Installers:
- Architecture: x64
  InstallerUrl: https://fullylocaltranscribe-dl.fullylocaltranscribe.workers.dev/app/4.5.2/%E5%AE%8C%E5%85%A8%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E6%96%87%E5%AD%97%E8%B5%B7%E3%81%93%E3%81%97%E3%83%84%E3%83%BC%E3%83%AB.zip
  InstallerSha256: 6E37805772D390E4C99B7BB6DFAFA750DFFCB78B8F43EB57F22D702C53127149
ManifestType: installer
ManifestVersion: 1.6.0