# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VoronSoftware.Rafn
PackageVersion: 0.1.5
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rafn.exe
Commands:
- rafn
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/voron-software/rafn/releases/download/v0.1.5/rafn-x86_64-pc-windows-msvc.zip
  InstallerSha256: 177512B4FE84FAB4FAC9334202C356E1B61BC766214939C794FC84DF17200EFE
ManifestType: installer
ManifestVersion: 1.12.0
