# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Digimezzo.Dopamine.3
PackageVersion: 3.0.4
PackageLocale: en-US
Publisher: Digimezzo
PublisherUrl: https://github.com/digimezzo/dopamine
PublisherSupportUrl: https://github.com/digimezzo/dopamine/issues
Author: Digimezzo
PackageName: Dopamine 3
PackageUrl: https://github.com/digimezzo/dopamine
License: GPL-3.0
LicenseUrl: https://github.com/digimezzo/dopamine/blob/HEAD/LICENSE
ShortDescription: Dopamine is an audio player which tries to make organizing and listening to music as simple and pretty as possible.
Description: Dopamine is an elegant audio player which tries to make organizing and listening to music as simple and pretty as possible. This version is written using Electron, Angular and Typescript.
Moniker: dopamine3
Tags:
- dopamine
- music
- player
ReleaseNotes: |-
  Added:
  - Added ability to enlarge the cover image on the Now playing screen
  - Clicking the visualization switches it between the available styles

  Changed:
  - Updated the Portuguese (Brazilian) translation
  - Updated the Swedish translation

  Fixed:
  - Delete button is not visible when folder is not selected in "Manage collection" screen
  - Window size increases when dragging
  - Attempting to delete a song from a smart playlist breaks the playlist
  - Deleting a song from a playlist while filtering via search removes most of the files from the playlist
  - Playback progress bar does not react to touch input
  - The cover image on the Now playing screen has glitches
  - Browsing folders on a NAS gets stuck in an infinite loop
  - Follow the system color does not work on Linux
ReleaseNotesUrl: https://github.com/digimezzo/dopamine/releases/tag/v3.0.4
ManifestType: defaultLocale
ManifestVersion: 1.12.0
