# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GitHub.cli
PackageVersion: 2.90.0
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- gh
ReleaseDate: 2026-04-16
Installers:
- Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_386.msi
  InstallerSha256: 7007F9AA8DE844D63F67DCB37824FE02241B0E68420AA4EF769F5C9FF52B5FC8
  ProductCode: '{6565FF04-A30D-47CF-B992-3665F82F5DF0}'
  AppsAndFeaturesEntries:
  - ProductCode: '{6565FF04-A30D-47CF-B992-3665F82F5DF0}'
    UpgradeCode: '{767EC5D2-C8F0-4912-9901-45E21F59A284}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/GitHub CLI'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_386.zip
  InstallerSha256: C338DDD3CF42C030B46324D78A5583E734075F5D794DF84855EE5294B55DD136
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_amd64.msi
  InstallerSha256: 523777A68D9E5610AC116AE9D90E357B116895E9943A22A10FB9EC1A36077A01
  ProductCode: '{96E3B2F2-77D2-4CCB-B022-D20260B379EA}'
  AppsAndFeaturesEntries:
  - ProductCode: '{96E3B2F2-77D2-4CCB-B022-D20260B379EA}'
    UpgradeCode: '{8CFB9531-B959-4E1B-AA2E-4AF0FFCC4AF4}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub CLI'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_amd64.zip
  InstallerSha256: 73FCAE688EB64AE67828536C9BE90DB1E5BE3F11691A6FA1C1E5418FD24EE10B
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_arm64.msi
  InstallerSha256: 607D802B7219EB03DCF927699BD76F825F954E6399143F33E87EAA1A46571230
  ProductCode: '{3528FE65-684C-41D3-9D4A-85EAB3C12A3E}'
  AppsAndFeaturesEntries:
  - ProductCode: '{3528FE65-684C-41D3-9D4A-85EAB3C12A3E}'
    UpgradeCode: '{5D15E95C-F979-41B0-826C-C33C8CB5A7EB}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub CLI'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin/gh.exe
    PortableCommandAlias: gh
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_windows_arm64.zip
  InstallerSha256: 6C962692EE8285F5B2336455CBE08695AE340DCF433B4B13D8D3D534EBEE8FFE
ManifestType: installer
ManifestVersion: 1.12.0
