# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.uz
PackageVersion: "153.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-07-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0/win32/uz/Thunderbird%20Setup%20153.0.exe
  InstallerSha256: 39C8AF016E8AE39877D4B233E85491E8443A9D92914BCB2D57FB9B0863869307
  ProductCode: Mozilla Thunderbird 153.0 (x86 uz)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0/win64/uz/Thunderbird%20Setup%20153.0.exe
  InstallerSha256: F963A3921A654C3649B3352D1C5022CE8C41A9E672E6A7313DAA71BB977EFADF
  ProductCode: Mozilla Thunderbird 153.0 (x64 uz)
ManifestType: installer
ManifestVersion: 1.12.0
