# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AndVl1.gw
PackageVersion: 0.2.12
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gw.exe
  PortableCommandAlias: gw
Commands:
- gw
ReleaseDate: 2026-05-17
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AndVl1/gw/releases/download/v0.2.12/gw-0.2.12-x86_64-pc-windows-msvc-winget.zip
  InstallerSha256: 84C0C540BF14F6B6652423009F5C39E84C7BD693C8BB0F46477341D42C9E76F3
- Architecture: arm64
  InstallerUrl: https://github.com/AndVl1/gw/releases/download/v0.2.12/gw-0.2.12-aarch64-pc-windows-msvc-winget.zip
  InstallerSha256: 50B723CF077DAFD3EC11973093B018A672BCDE4CB047832B6F91690732ACC56E
ManifestType: installer
ManifestVersion: 1.12.0
