# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: futrime.lip
PackageVersion: 0.33.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lip.exe
  PortableCommandAlias: lip
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/futrime/lip/releases/download/v0.33.3/lip-0.33.3-win-x64.zip
  InstallerSha256: D1AA4C2E5D91671CF584A998D27B005638CB5084360B509F4CD57DCBB52024C5
- Architecture: arm64
  InstallerUrl: https://github.com/futrime/lip/releases/download/v0.33.3/lip-0.33.3-win-arm64.zip
  InstallerSha256: 304CECA690D58915DB22FFAA980D507FEBEB14FF4136B314F1A0F7FA62571449
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-03-03
