# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Netbird.Netbird
PackageVersion: 0.77.0
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-08-13
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.77.0/netbird_installer_0.77.0_windows_amd64.msi
  InstallerSha256: 2F07B4784E4CDBA17277D8A507BE95959450E73F4AEF00A7F8BF82372C94F337
  ProductCode: '{05A8E94C-3F90-4BD7-B0F2-BE34D774AA4A}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.77.0/netbird_installer_0.77.0_windows_amd64.exe
  InstallerSha256: 6509723017BF9FA2A2A9B4EA15B0A1BC0FC602AB90B92471CBE72B1A723DAD6B
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.77.0.31716521366
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.77.0/netbird_installer_0.77.0_windows_arm64.msi
  InstallerSha256: 81D7115C026B64753519F4A218C47D7BC2DF40593EE224B17B66CF8F34647D46
  ProductCode: '{81CFB7C3-60D6-47AF-8CA5-2F9D9DC85DD9}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.77.0/netbird_installer_0.77.0_windows_arm64.exe
  InstallerSha256: 7D0BF85E159D755EA29BC6A2DB5BC5ECE31F269B6772369D811AFED2504B3208
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.77.0.31716521366
ManifestType: installer
ManifestVersion: 1.12.0
