# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: iOfficeAI.AionUi
PackageVersion: 2.1.42
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: f3bfde38-8429-545c-a4e9-a078d87dee6c
ReleaseDate: 2026-07-28
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/iOfficeAI/AionUi/releases/download/v2.1.42/AionUi-2.1.42-win-x64.exe
  InstallerSha256: 8296B7B7E9044E007ED26B5FD5359B11FC3F1ECD2941006462A2258021343C14
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/iOfficeAI/AionUi/releases/download/v2.1.42/AionUi-2.1.42-win-x64.exe
  InstallerSha256: 8296B7B7E9044E007ED26B5FD5359B11FC3F1ECD2941006462A2258021343C14
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/iOfficeAI/AionUi/releases/download/v2.1.42/AionUi-2.1.42-win-arm64.exe
  InstallerSha256: AC9C145575CB7D7E1AF8E65E8E128424CFA90D3A51819E37C8C51DB51848ED73
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.10.0
