# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Winix.Schedule
PackageVersion: 0.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: schedule.exe
  PortableCommandAlias: schedule
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Yortw/winix/releases/download/v0.3.0/schedule-win-x64.zip
  InstallerSha256: B72B6694075F3CD4BEB1B49EBDF6B5F6690B464A510F39D03142B3286BE9AFE8
  UpgradeBehavior: uninstallPrevious
ManifestType: installer
ManifestVersion: 1.12.0
