# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DragonLang.Dragon
PackageVersion: 1.0.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dragon.exe
  PortableCommandAlias: dragon
Scope: user
Installers:
- Architecture: x64
  InstallerUrl: https://dragon-lang.org/Dragon_v1.0.7_Windows_x86_64.zip
  InstallerSha256: 39D6CC3A074A2FDF7A62C7E01C1558B5DB83A15A4BD9C582865B99DA76698097
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://dragon-lang.org/Dragon_v1.0.7_Windows_aarch64.zip
  InstallerSha256: ED543D2F4A071D09D8AEA762917F55A4BE21550C46E21CE92D3FE5496DD39D46
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
