# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PlanetScale.CLI
PackageVersion: 0.331.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pscale.exe
Commands:
- pscale
ReleaseDate: 2026-09-10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.331.0/pscale_0.331.0_windows_386.zip
  InstallerSha256: 4CBEC0D626608CCED90061183C4CB7A07B9F9B40D8CE59B93509156831C4E8DA
- Architecture: x64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.331.0/pscale_0.331.0_windows_amd64.zip
  InstallerSha256: 938B4295B7E494A53E3A828461DE58C1F3D1FE604CD71A6251452F6AB3084190
- Architecture: arm64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.331.0/pscale_0.331.0_windows_arm64.zip
  InstallerSha256: A699A0317332F969EDF65DD09CFE08BEB68B3F2F7D0AE1A3F7B183B29121E572
ManifestType: installer
ManifestVersion: 1.12.0
