# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Vortenia.Overwatch
PackageVersion: 2.0.0
InstallerType: portable
Commands:
  - overwatch
ReleaseDate: 2026-07-04
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/vorteniahq/Overwatch/releases/download/v2.0.0/Overwatch.exe
    InstallerSha256: 7E0C7984009BA91D15272DB21786F884B35E4EBC408A5A122C8B322D5C517C6A
ManifestType: installer
ManifestVersion: 1.6.0
