# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.Shared.8.1
PackageVersion: latest
InstallerType: zip
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-05
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip
  InstallerSha256: 338898286CA4C77D2B1D6BDCA8CB70E726C8C7F8E596F726D81FCC09A026AB29
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
  InstallerSha256: 9734D61383B25391B90186731106DC8068763BAA177C622E57DFAEBDF7C21630
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl-shared.zip
  InstallerSha256: DAE55268E8A4D817752C0A66644672129146E557CF35E1B9CB3605EA8E94294E
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl.zip
  InstallerSha256: FACC12BF578EC3D0128690359D1390A6FB90B9FE53BB1B5BF2E787CC2738C1CE
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-win64-gpl-8.1.zip
  InstallerSha256: 447A39A8D8792B4363666C58BF9BBDA24210547BBB91FCE149A20417F7D439E2
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-win64-lgpl-8.1.zip
  InstallerSha256: BE4097AB8FE1344CC3B187DC2ED1D118D3BAE7CEA5B2D842EE977716DEE4F871
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-win64-lgpl-shared-8.1.zip
  InstallerSha256: BD0A1C303DFD44242D6A85147974A8FD121E2B730608B75C3789A30113975A3E
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-win64-gpl-9.0.zip
  InstallerSha256: 87C4729F3193F3BA562BADA0330A98338C9A858D25B15FC98338A1364667348B
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-win64-gpl-shared-9.0.zip
  InstallerSha256: 4BFF73B052A52FB7BAF7DC49706533439D676B8089041E2EBC3E1F97D8416EFF
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-win64-lgpl-9.0.zip
  InstallerSha256: 514B6B542E84DBBB9A3F7BC64DB670D2B647FA057442C73F69D3C18E2A36D0CA
- Architecture: x64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-win64-lgpl-shared-9.0.zip
  InstallerSha256: 452D6ABF085285C16DA51796AAF9AE61891098A0D198CAB7C6F331A7BB609687
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n8.1-latest-win64-gpl-shared-8.1/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n8.1-latest-win64-gpl-shared-8.1/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n8.1-latest-win64-gpl-shared-8.1/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-win64-gpl-shared-8.1.zip
  InstallerSha256: 25C3D66A22D6B1D60F5AF5EEDE33E0569BB202330ED4E745AB0B2C014B5921F2
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-gpl-shared.zip
  InstallerSha256: 2AAD2CBBFB6C494E6A5611FB6D5196F2FAC941AF819CBF07D0FB14751025ADC9
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-gpl.zip
  InstallerSha256: A03D36EB92D54B6B5F78AACFC0FE25C0EC7DDE7B6303062FEEDFC1154C5E0F45
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-lgpl-shared.zip
  InstallerSha256: 9F51E27C01033C89B5AF6D04877CD1596DEE570B69331145C517BB8476EF12F5
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-lgpl.zip
  InstallerSha256: 47D7652C26E4A3734CB61BF18C15285DCECCE6036A851262B2B01CA51A3D567C
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-winarm64-gpl-8.1.zip
  InstallerSha256: 1EC4D0F297B71D7431B6A666ABBB41F2017C6865AA282363CD4F52E75EE13F25
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-winarm64-lgpl-8.1.zip
  InstallerSha256: 60BBCC7BB2884676B0C3F9E2F02C6B073E854128947DCC9964AB04154C500EEE
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-winarm64-lgpl-shared-8.1.zip
  InstallerSha256: 3861FA135CFE4E057085D1437C6AE246CD2546736EFCEF790F890D923E843EC3
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-winarm64-gpl-9.0.zip
  InstallerSha256: 8942A7F1BAFB85D49D38466568C453377901394C50ED4A0499DE1B988D1883FA
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-winarm64-gpl-shared-9.0.zip
  InstallerSha256: 434C708538C3F8FA18D08FD0A1EBA2E7FB22F50A34EA3C7AFD0383C21C0FFB20
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-winarm64-lgpl-9.0.zip
  InstallerSha256: 308177E038B809748422F4B5E663E5680D576B93AA160053011D5ED4D687B1D4
- Architecture: arm64
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n9.0-latest-winarm64-lgpl-shared-9.0.zip
  InstallerSha256: 8A9615A47CEC780E3BCBA2B3C7ABFE1394D031DC679252764878CD9414D4C980
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n8.1-latest-winarm64-gpl-shared-8.1/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n8.1-latest-winarm64-gpl-shared-8.1/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n8.1-latest-winarm64-gpl-shared-8.1/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-winarm64-gpl-shared-8.1.zip
  InstallerSha256: AC119BAE5BFF93955D7260A3997F82669085E921C47E82CF9419FD01AAC5A511
ManifestType: installer
ManifestVersion: 1.12.0
