# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Jellyfin.FFmpeg
PackageVersion: 7.1.3-5
PackageLocale: en-US
Publisher: The Jellyfin Project
PublisherUrl: https://jellyfin.org/contact
PublisherSupportUrl: https://github.com/jellyfin/jellyfin-ffmpeg/issues
PackageName: Jellyfin FFmpeg
PackageUrl: https://github.com/jellyfin/jellyfin-ffmpeg
License: LGPL-2.1
LicenseUrl: https://github.com/jellyfin/jellyfin-ffmpeg/blob/HEAD/LICENSE.md
Copyright: © Jellyfin Contributors
ShortDescription: FFmpeg for Jellyfin with custom extensions and enhancements.
Tags:
- ffmpeg
- ffprobe
- jellyfin-ffmpeg
ReleaseNotes: |-
  What's Changed
  - ffprobe: avoid runaway only_first_vframe probing by @gnattu in #681
  Full Changelog: v7.1.3-4...v7.1.3-5
ReleaseNotesUrl: https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v7.1.3-5
ManifestType: defaultLocale
ManifestVersion: 1.12.0
