# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Ankama.AnkamaLauncher
PackageVersion: 3.15.2.20509
PackageLocale: en-US
Publisher: Ankama
PackageName: Ankama Launcher
License: https://account.ankama.com/en/tou
Copyright: © 2026 Ankama
ShortDescription: Ankama portal and game launcher.
PackageUrl: https://www.ankama.com/en/games
Moniker: ankamalauncher
Tags:
- ankama-launcher
- game-launcher
- game-client
- abraca
- dofus
- fly'n
- flyn
- krosfighter
- maliki-poison-of-the-past
- malikipoisonofthepast
- mmorpg
- savara
- super-nano-blaster
- supernanoblaster
- wakfu
- waven
ManifestType: defaultLocale
ManifestVersion: 1.12.0