# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jdx.mise
PackageVersion: 2026.7.14
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mise/bin/mise-shim.exe
  PortableCommandAlias: mise-shim
- RelativeFilePath: mise/bin/mise.exe
  PortableCommandAlias: mise
UpgradeBehavior: install
ReleaseDate: 2026-07-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.7.14/mise-v2026.7.14-windows-x64.zip
  InstallerSha256: FDF01891877650BD0F30FF99E493D88F72423B280867CA44062EE2CECD75C78C
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.7.14/mise-v2026.7.14-windows-arm64.zip
  InstallerSha256: 10627EBEDC1E0A53FE669B9E93B1701975F0CBA1165759BC270796A0DE37B691
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
