# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AcaciaAve.HUD
PackageVersion: 1.0.243.8
InstallerLocale: en-US
InstallerType: msi
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{1898ADCA-F957-454D-8A05-40899DF53AF8}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/acaciaavellc/Heads-Up-Display/releases/download/v1.0.243.8/AcaciaAve-HUD-Personal-x64.msi
  InstallerSha256: A1E2D16E4C2328DE321C2E117FD786B32DF1160CA17AAAEB53ECFE52B6CB7176
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-31
