# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SadeghHayeri.GreenTunnel
PackageVersion: 3.0.5
InstallerLocale: en-US
InstallerType: nullsoft
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: green-tunnel-installer.exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: ba1bb1f3-0069-5c64-9a11-479ebc0471d9
ReleaseDate: 2026-07-26
AppsAndFeaturesEntries:
- DisplayName: GreenTunnel 3.0.5
  ProductCode: ba1bb1f3-0069-5c64-9a11-479ebc0471d9
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/SadeghHayeri/GreenTunnel/releases/download/v3.0.5/GreenTunnel.Setup.3.0.5.exe
  InstallerSha256: 77CD4E08ABF2E7A0FC235821AE49BBFDD032616A9A0407902F907C96547D2659
ManifestType: installer
ManifestVersion: 1.10.0
