# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: LuigiElleBalotta.AIUsageNET
PackageVersion: 0.4.1
InstallerType: exe
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-07-22
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
AppsAndFeaturesEntries:
- DisplayName: AIUsage.NET
  DisplayVersion: "0.4.1"
  Publisher: AIUsage.NET
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LuigiElleBalotta/AIUsage.NET/releases/download/v0.4.1/AIUsage.NET-win-Setup.exe
  InstallerSha256: 097E31FFCC89421D18032E11B56B8EA192BFE5F55E067E5FA40B1CE034008A58
ManifestType: installer
ManifestVersion: 1.10.0
