# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Avanquestpdfforge.PDFCreator-Free
PackageVersion: 6.2.2
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /COMPONENTS="MAINPROGRAM,IMAGES2PDF" /SILENT
  SilentWithProgress: /COMPONENTS="MAINPROGRAM,IMAGES2PDF" /SILENT
UpgradeBehavior: install
ReleaseDate: 2026-03-10
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.pdfforge.org/download/pdfcreator/6.2.2/PDFCreator-6_2_2-Setup.exe?file=PDFCreator-6_2_2-Setup.exe&download
  InstallerSha256: 33f67362c61e2db592357155246b338627dbec793c7d4abd5247cfdfb254758f
- Architecture: arm64
  InstallerUrl: https://download.pdfforge.org/download/pdfcreator/6.2.2/PDFCreator-6_2_2-Setup.exe?file=PDFCreator-6_2_2-Setup.exe&download
  InstallerSha256: 33f67362c61e2db592357155246b338627dbec793c7d4abd5247cfdfb254758f
ManifestType: installer
ManifestVersion: 1.9.0

