# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: QualcommTechnologies,Inc.QualcommUSBUserspaceDrivers
PackageVersion: 1.0.2.2
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/qualcomm/qcom-usb-userspace-drivers/releases/download/release-win-v1.0.2.2/qcom_usb_userspace_drivers_x64.exe
  InstallerSha256: 31B148D58BC627C363BE8452E43A9E870958E61FD8B14A2152200B9465C366DC
- Architecture: x86
  InstallerUrl: https://github.com/qualcomm/qcom-usb-userspace-drivers/releases/download/release-win-v1.0.2.2/qcom_usb_userspace_drivers_x86.exe
  InstallerSha256: 9e915d95ea35cb12f250405d3925fc9af8e2be41fc52134b9e3478f0203cba1e
- Architecture: arm64
  InstallerUrl: https://github.com/qualcomm/qcom-usb-userspace-drivers/releases/download/release-win-v1.0.2.2/qcom_usb_userspace_drivers_arm64.exe
  InstallerSha256: 5c7af40811ad3ab47d532563ceb01f5db8b5950774532e5647885214da1c3bf0
ManifestType: installer
ManifestVersion: 1.12.0
