# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: IvanIsCoding.celq
PackageVersion: 0.5.0
PackageLocale: en-US
Publisher: IvanIsCoding
PublisherUrl: https://github.com/IvanIsCoding
PublisherSupportUrl: https://github.com/IvanIsCoding/celq/issues
PackageName: celq
PackageUrl: https://github.com/IvanIsCoding/celq
License: Apache-2.0
ShortDescription: A CEL command-line query tool for JSON data
Tags:
- cel
- cli
- common-expression-language
- jq
- json
- json5
- rust
- yq
ReleaseNotes: |-
  This was a release focusing mostly on trimming dependencies and keeping dependencies up-to-date:

  * Switched XML parsing from `xml2json-rs` to `quick-xml`. `xml2json-rs` was based on an older version of `quick-xml` that was not up-to-date
  * The gron parser and serializer has been completely rewritten using `serde_json`. The `ressa` and `resast` JavaScript parsers were dropped. This leads to smaller binaries.
  * Bumped the YAML parser (`serde-saphyr` -> 0.0.26).
  * Bumped the toml parser (`toml` -> 1.1.2).
ReleaseNotesUrl: https://github.com/IvanIsCoding/celq/releases/tag/v0.5.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
