# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: rvben.rumdl
PackageVersion: 0.2.2
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rumdl.exe
  PortableCommandAlias: rumdl
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/rvben/rumdl/releases/download/v0.2.2/rumdl-v0.2.2-x86_64-pc-windows-msvc.zip
  InstallerSha256: 73F1453B59317CC3423C6C702E84A6F52D63C9E2DBD22B7035AC26D3B720CEDF
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-26
