# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: d4vid87.hookecho
PackageVersion: 0.12.0-alpha.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: hookecho.exe
  PortableCommandAlias: hookecho
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Commands:
- hookecho
Protocols:
- hookecho
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-08-26
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/d4vid87/hookecho/releases/download/latest/hookecho-windows-x86_64.zip
  InstallerSha256: 4BBA9E964AEC43D07B3D4DFA73B83B2EF41F8D223CE3C208C434C48BAC4CC52B
ManifestType: installer
ManifestVersion: 1.12.0
