# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GitHub.Copilot
PackageVersion: v1.0.45
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: copilot.exe
Commands:
- copilot
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.PowerShell
    MinimumVersion: 7.0.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/github/copilot-cli/releases/download/v1.0.45/copilot-win32-x64.zip
  InstallerSha256: 73666F716C2085F1C2B88749F5D122F288C1BFF81A49CC2B5666789D54B8176F
- Architecture: arm64
  InstallerUrl: https://github.com/github/copilot-cli/releases/download/v1.0.45/copilot-win32-arm64.zip
  InstallerSha256: 78A3C55D7C8575E3AF100D722A7498F8631F5627914E78450661F8C44CED8AE7
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-11
