# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ONFStudios.OreNoFusen
PackageVersion: 1.1.7
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ore-no-fusen/ore-no-fusen/releases/download/v1.1.7/ore-no-fusen_1.1.7_x64-setup.exe
  InstallerSha256: D3A218D23BB070F725A219D6D618D000CE7C7B4975DFEB760A8430654E39535A
ManifestType: installer
ManifestVersion: 1.6.0
