# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.ro
PackageVersion: 140.9.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-04-07
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.9.1esr/win32/ro/Thunderbird%20Setup%20140.9.1esr.exe
  InstallerSha256: 3A4E1AB220163A0CEA97D3B7ED1B83471E1D8F37822DA323D80ED73945D147A1
  ProductCode: Mozilla Thunderbird 140.9.1 (x86 ro)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 ro)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.9.1esr/win64/ro/Thunderbird%20Setup%20140.9.1esr.exe
  InstallerSha256: C44BCC62F7B82997C5D9E76E66B2D02A34C83E6B126A140FB07642EB6E5C5E96
  ProductCode: Mozilla Thunderbird 140.9.1 (x64 ro)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 ro)
ManifestType: installer
ManifestVersion: 1.12.0
