# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SparkLabs.openvpn-configuration-generator
PackageVersion: 2.0.2
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{EA74259B-943D-4796-BC84-FE734455C0CE}'
ReleaseDate: 2026-07-03
AppsAndFeaturesEntries:
- DisplayName: OpenVPN Configuration Generator 2.0.2
  ProductCode: '{969EE747-FAD7-48BB-BFF9-75E915E998EB}'
  UpgradeCode: '{5CE19097-E8BB-5087-9C69-8817F64EFE52}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SparkLabs\OpenVPN Configuration Generator'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/thesparklabs/openvpn-configuration-generator/releases/download/2.0.2/ovpngen-2.0.2-windows.exe
  InstallerSha256: E416F0153DA04A3C3534F9326C0AE1B9FFDA7997E2D7FC084B04268123329850
ManifestType: installer
ManifestVersion: 1.12.0
