# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RightNow-AI.OpenFang
PackageVersion: 0.3.17
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: openfang.exe
Commands:
- openfang
ReleaseDate: 2026-03-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RightNow-AI/openfang/releases/download/v0.3.17/openfang-x86_64-pc-windows-msvc.zip
  InstallerSha256: 857BBCDAC8E47C401DC68D21464B959AB710D4BD37B574D79941B6D1D744D20F
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/RightNow-AI/openfang/releases/download/v0.3.17/openfang-aarch64-pc-windows-msvc.zip
  InstallerSha256: D026C6DD0B9FC493952F822207D4DEE815D417AB9E068C0D883BD29C3D10D450
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
