# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.457.67.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-08-08
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.67.0&arch=x86
  InstallerSha256: FD6515136780AE1955EC4E5AE06490D196F582ECFDACA5107A432382F8EAC120
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.67.0&arch=amd64
  InstallerSha256: A60B8B17DD66C7D033F7969D99FA0C5E4E4CCEF73AA399B8FF39154584551C5C
ManifestType: installer
ManifestVersion: 1.12.0
