# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: 0state.scafld
PackageVersion: 2.4.0
InstallerLocale: en-US
InstallerType: portable
Commands:
  - scafld
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nilstate/scafld/releases/download/v2.4.0/scafld_2.4.0_windows_amd64.exe
    InstallerSha256: b2397835a08a4412fc2344b141e6271f578ce6ce2edba77c8c84f50a5fe6457a
  - Architecture: arm64
    InstallerUrl: https://github.com/nilstate/scafld/releases/download/v2.4.0/scafld_2.4.0_windows_arm64.exe
    InstallerSha256: e8f0d7e9c43879dbfed958a03f078ff46ea41c0f98c1af2f9e59aac04ed1d27c
ManifestType: installer
ManifestVersion: 1.9.0
