# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: M2Team.NanaZip
PackageVersion: 6.0.1698.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- '001'
- 7z
- apfs
- arj
- asar
- b64
- br
- bz2
- bzip2
- cab
- cb7
- cbr
- cbz
- cpio
- deb
- dmg
- esd
- fat
- gz
- gzip
- hfs
- hfsx
- iso
- lha
- liz
- lz
- lz4
- lz5
- lzh
- lzma
- lzma2
- ntfs
- nupkg
- rar
- rpm
- squashfs
- swm
- tar
- taz
- tbz
- tbz2
- tgz
- tlz
- tlz4
- tlz5
- tpz
- txz
- tz
- tzst
- tzstd
- vdi
- vhd
- vhdx
- vmdk
- wim
- xar
- xz
- z
- zip
- zipx
- zst
- zstd
PackageFamilyName: 40174MouriNaruto.NanaZip_gnj4mf6z9tkrc
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-04-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/6.0.1698.0/NanaZip_6.0.1698.0.msixbundle
  InstallerSha256: 6E5FEFB3F442737944993BEC459D0FB0945A7CD69EF45CDC26C7C555BDBF177B
  SignatureSha256: E8CFFFBFF694757C4FB5E367B3B8ACB74E97CCFD76C489508B61F538E09483A3
  Commands:
  - nanazip
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/40174MouriNaruto.NanaZip_6.0.1698.0_x64__gnj4mf6z9tkrc'
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: x64\NanaZip.Universal.Console.exe
  - RelativeFilePath: x64\NanaZip.Universal.Windows.exe
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/6.0.1698.0/NanaZip_6.0.1698.0.msixbundle
  InstallerSha256: 6E5FEFB3F442737944993BEC459D0FB0945A7CD69EF45CDC26C7C555BDBF177B
  SignatureSha256: E8CFFFBFF694757C4FB5E367B3B8ACB74E97CCFD76C489508B61F538E09483A3
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/40174MouriNaruto.NanaZip_6.0.1698.0_x64__gnj4mf6z9tkrc'
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/6.0.1698.0/NanaZip_6.0.1698.0.msixbundle
  InstallerSha256: 6E5FEFB3F442737944993BEC459D0FB0945A7CD69EF45CDC26C7C555BDBF177B
  SignatureSha256: E8CFFFBFF694757C4FB5E367B3B8ACB74E97CCFD76C489508B61F538E09483A3
  Commands:
  - nanaziparm64
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/40174MouriNaruto.NanaZip_6.0.1698.0_arm64__gnj4mf6z9tkrc'
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: arm64\NanaZip.Universal.Console.exe
  - RelativeFilePath: arm64\NanaZip.Universal.Windows.exe
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/6.0.1698.0/NanaZip_6.0.1698.0.msixbundle
  InstallerSha256: 6E5FEFB3F442737944993BEC459D0FB0945A7CD69EF45CDC26C7C555BDBF177B
  SignatureSha256: E8CFFFBFF694757C4FB5E367B3B8ACB74E97CCFD76C489508B61F538E09483A3
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/40174MouriNaruto.NanaZip_6.0.1698.0_x64__gnj4mf6z9tkrc'
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
