# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0
PackageIdentifier: amiasea.tfcred
PackageVersion: 1.4.0
InstallerLocale: en-US
Architecture: x64
InstallerType: zip
NestedInstallerType: custom
Scope: user
InstallModes:
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Mode install
  SilentWithProgress: -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Mode install
  Custom: -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Mode install
  Upgrade: -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Mode upgrade
UninstallCommand: powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%USERPROFILE%\AppData\Local\Programs\tfcred\uninstall.ps1"
Commands:
  - tfcred
  - terraform-credentials-tfcred
NestedInstallerFiles:
  - RelativeFilePath: install.ps1
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/amiasea/terraform-credentials-tfcred/releases/download/v1.4.0/terraform-credentials-tfcred_windows_amd64.zip
    InstallerSha256: ef6b8bd8ca0a77875a1b2fafeb77d80c4c6d1ea002f421f173bbcdc611eeee8b
AppsAndFeaturesEntries:
  - DisplayName: tfcred
    Publisher: amiasea
    DisplayVersion: 1.4.0
    ProductCode: tfcred-v1.4.0
ManifestType: installer
ManifestVersion: 1.12.0