# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SagerNet.sing-box
PackageVersion: 1.13.7
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-04-10
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: sing-box-1.13.7-windows-386/sing-box.exe
  InstallerUrl: https://github.com/SagerNet/sing-box/releases/download/v1.13.7/sing-box-1.13.7-windows-386.zip
  InstallerSha256: 8FFDB8221416CAEB441D71E42EFC2653BD2803DC741E0037C3027B4D48A3665B
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: sing-box-1.13.7-windows-amd64/sing-box.exe
  InstallerUrl: https://github.com/SagerNet/sing-box/releases/download/v1.13.7/sing-box-1.13.7-windows-amd64.zip
  InstallerSha256: C14609978B33552AA82DA1351A0377110EF4370F2369FA5CE0D73A94AEB8A53A
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: sing-box-1.13.7-windows-arm64/sing-box.exe
  InstallerUrl: https://github.com/SagerNet/sing-box/releases/download/v1.13.7/sing-box-1.13.7-windows-arm64.zip
  InstallerSha256: 5FDD834E3525FFC715291CD6FFFC509F25CF3C25AD58CA0E9A066106608B87D2
ManifestType: installer
ManifestVersion: 1.12.0
