# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.sl
PackageVersion: 153.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-07-28
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0.1/win32/sl/Thunderbird%20Setup%20153.0.1.exe
  InstallerSha256: A11E7C08B91B5AE52C0C4C1C3A9833A30BF54384C72945E272FD29372883219B
  ProductCode: Mozilla Thunderbird 153.0.1 (x86 sl)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0.1/win64/sl/Thunderbird%20Setup%20153.0.1.exe
  InstallerSha256: FB96CC3BFB4034AC207E64C04A4B79D2543D18EA3E16E0E4B10A599199AB9D72
  ProductCode: Mozilla Thunderbird 153.0.1 (x64 sl)
ManifestType: installer
ManifestVersion: 1.12.0
