# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: RocketChat.RocketChat
PackageVersion: 4.13.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: 9b73a9fb-f1d5-59ee-b41e-e1dd393a748a
AppsAndFeaturesEntries:
- DisplayName: Rocket.Chat 4.12.0
  ProductCode: 9b73a9fb-f1d5-59ee-b41e-e1dd393a748a
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-ia32.exe
  InstallerSha256: D56162E992797AD0C74627BE0460E01119E11155E04856047BDCDF9179B8F23E
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-ia32.exe
  InstallerSha256: D56162E992797AD0C74627BE0460E01119E11155E04856047BDCDF9179B8F23E
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-x64.exe
  InstallerSha256: D88F4551A4AA47BE8B99E20349C07999CC4EBABB7B3A60CBB5112E83B8E3ACEC
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-x64.exe
  InstallerSha256: D88F4551A4AA47BE8B99E20349C07999CC4EBABB7B3A60CBB5112E83B8E3ACEC
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-arm64.exe
  InstallerSha256: 4A422FBCFF8BDC0EB2ADF375D60742E2807648D495C50894550CA235EF2292DF
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.13.0/rocketchat-4.13.0-win-arm64.exe
  InstallerSha256: 4A422FBCFF8BDC0EB2ADF375D60742E2807648D495C50894550CA235EF2292DF
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-03-06
