# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: advancedfx.HLAE
PackageVersion: 2.190.1
InstallerType: burn
Scope: machine
ReleaseDate: 2026-05-19
AppsAndFeaturesEntries:
- DisplayName: HLAE Installer
  ProductCode: '{E840561C-3B7F-41CB-8214-CA77DB343E7C}'
  UpgradeCode: '{35C8D990-6C4F-4639-ADF7-D259B06E070B}'
  InstallerType: burn
- ProductCode: '{ECADAEAD-7680-4C31-8AA4-C10D65070BA7}'
  UpgradeCode: '{33FEF63B-4A17-4D59-ABC9-B7A06BD07F07}'
  InstallerType: wix
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\HLAE'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/advancedfx/advancedfx/releases/download/v2.190.1/HLAE_Setup.exe
  InstallerSha256: 477BF72EB895DD7F896CFE789F6D8FF0E28F65DD4A4CFA83A95EC25CA6B26D74
ManifestType: installer
ManifestVersion: 1.12.0
