# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Purple.PurplePlus
PackageVersion: 7.0.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /silent
ProductCode: 660a8ce1-0b16-5b4c-bad5-065a5d69f45e
ReleaseDate: 2026-08-04
AppsAndFeaturesEntries:
- DisplayName: Purple+ 7.0.0
  ProductCode: 660a8ce1-0b16-5b4c-bad5-065a5d69f45e
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\PurplePlus'
Installers:
- Architecture: x64
  InstallerUrl: https://purpleplusinstaller.blob.core.windows.net/releases/PurplePlus-7.0.0-x64-Setup.exe
  InstallerSha256: 96C6DE096CAC2A9366A0726D34D35551E88C161430ADC9327E5FAA583B087A19
ManifestType: installer
ManifestVersion: 1.12.0
