# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Sky.SkyGo
PackageVersion: 26.2.3.0
PackageLocale: it-IT
PackageUrl: https://skygo.sky.it
ShortDescription: Il meglio della TV in un unica app. I canali si Sky in Streaming e alcuni canali in chiaro di Rai, Mediaset e La7.
Tags:
- piattaformo-di-streaming
- piattaformodistreaming
- sky-go
- sky-italia
- skyitalia
- sky-regno-unito
- sky-germania
- sky-austria
- sky-televisione
- programmi-tv
- sky-originale
- sky-television
- sky-on-demand
- filme
ManifestType: locale
ManifestVersion: 1.12.0
