# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hellodigua.ChatLab
PackageVersion: 0.33.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 5c93c6d5-cfd9-53ea-a37a-26c1e3d35c8d
ReleaseDate: 2026-07-22
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/ChatLab/ChatLab/releases/download/v0.33.0/ChatLab-0.33.0-setup.exe
  InstallerSha256: 1E8D5BE3F937F91FFF2A5C4E968A29EBFE88FCE9B70E59366ACDAB2765FE82F4
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/ChatLab/ChatLab/releases/download/v0.33.0/ChatLab-0.33.0-setup.exe
  InstallerSha256: 1E8D5BE3F937F91FFF2A5C4E968A29EBFE88FCE9B70E59366ACDAB2765FE82F4
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
