# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 153.0.8008.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-08-14
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/hvgmfmr7qkbmvwxbpt76s7i234_153.0.8008.0/153.0.8008.0_chrome_installer_uncompressed.exe
  InstallerSha256: 1A1EE87013E4EBE09EF5C9A2BCB66D26F6DC1187217C57972BF66BD562FC536B
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/nshpkcmhcog3rxp5y3ghuga2ue_153.0.8008.0/153.0.8008.0_chrome_installer_uncompressed.exe
  InstallerSha256: 5C291EEDFC5A01FF63EC7C5ADC859A97707C51549AFDFCA40DD2EEF4AE8CDC42
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/hguyaqzptamxoposahfsfxkgvi_153.0.8008.0/153.0.8008.0_chrome_installer_uncompressed.exe
  InstallerSha256: A29260F4050AEC0D2517AC504F15A21F25D5720F3B5B035B4F4E722D9B8E8955
ManifestType: installer
ManifestVersion: 1.12.0
