# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: o-murphy.ebalistyka
PackageVersion: 0.1.14.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ebalistyka.exe
  PortableCommandAlias: ebalistyka
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/o-murphy/ebalistyka-app/releases/download/v0.1.14/ebalistyka_windows_x86_64.zip
  InstallerSha256: A17AC3D9CB696F059DC58B8469C5E58E0ADC115DFAFC639E9B01EA1E9CD45FED
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-12
