# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: vim.vim.nightly
PackageVersion: 9.2.0992
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- diff
- evim
- gview
- gvim
- gvimdiff
- tee
- view
- vim
- vimdiff
- xxd
ProductCode: Vim (current user)
ReleaseDate: 2026-08-20
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_x86.exe
  InstallerSha256: CDF22C36EC8845CD76AF99C1D69CE12538608DEB5A988CC084E25E074A899AA2
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x86) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_x86.exe
  InstallerSha256: CDF22C36EC8845CD76AF99C1D69CE12538608DEB5A988CC084E25E074A899AA2
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x86) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_x64.exe
  InstallerSha256: 53086F885CE9A6E43EB5665DE96CFA728111556F1585154FC9E86BDAF16BD025
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_x64.exe
  InstallerSha256: 53086F885CE9A6E43EB5665DE96CFA728111556F1585154FC9E86BDAF16BD025
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (x64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_arm64.exe
  InstallerSha256: DD00BA0C8CA4F4ACA31239E961FF58CEF3EF3975A1EBE52AF6FD9FAA35976077
  InstallerSwitches:
    Custom: /currentuser
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (ARM64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.2.0992/gvim_9.2.0992_arm64.exe
  InstallerSha256: DD00BA0C8CA4F4ACA31239E961FF58CEF3EF3975A1EBE52AF6FD9FAA35976077
  InstallerSwitches:
    Custom: /allusers
  AppsAndFeaturesEntries:
  - DisplayName: Vim 9.2 (ARM64) (current user)
    Publisher: The Vim Project
    ProductCode: Vim (current user)
ManifestType: installer
ManifestVersion: 1.12.0
