# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Unibo.Alchemist
PackageVersion: 43.0.31
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{CCF004D3-A7E5-39AC-8080-4C56C8F31D00}'
AppsAndFeaturesEntries:
- DisplayName: alchemist
  Publisher: Unknown
  ProductCode: '{CCF004D3-A7E5-39AC-8080-4C56C8F31D00}'
  UpgradeCode: '{4342BF32-7612-3295-9D0C-A06586CDA5D4}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\alchemist'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AlchemistSimulator/Alchemist/releases/download/43.0.31/alchemist-43.0.31.msi
  InstallerSha256: DA123E85BE4E88E5C5255251487D13247AE702DD96789B644A452A9F2DBEA300
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-04-07
