# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dropbox.Dropbox
PackageVersion: 248.3.3501
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20248.3.3501%20Offline%20Installer.x86.exe
  InstallerSha256: DA45D233717C4333CC0B298E79B48DC9FDD55AF3B20BAA16C05B56984F5E3782
- Architecture: x64
  InstallerUrl: https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20248.3.3501%20Offline%20Installer.x64.exe
  InstallerSha256: F7CB633298EECA9E3F2891E4CDF882A5FBE9101A7CA837C894CAB0D14DED1EE8
ManifestType: installer
ManifestVersion: 1.12.0
