# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RightNow-AI.OpenFang
PackageVersion: 0.5.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: openfang.exe
Commands:
- openfang
ReleaseDate: 2026-03-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RightNow-AI/openfang/releases/download/v0.5.4/openfang-x86_64-pc-windows-msvc.zip
  InstallerSha256: 98DF90B3C2F56E47726A1B4DA1F04ADE886639BC7183ACD15C37E8566AD895A4
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/RightNow-AI/openfang/releases/download/v0.5.4/openfang-aarch64-pc-windows-msvc.zip
  InstallerSha256: 3B2637F2DEA796842E0E4F3155C7F55A770333C738895650307BF71EDDD81585
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
