# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: carlgustavh.WinWeather
PackageVersion: "1"
ReleaseDate: 2024-04-30
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: WinWeather.exe
  PortableCommandAlias: winweather
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/carlgustavh/WinWeather/releases/download/v1.0.0/WinWeather.1.0.0.zip
  InstallerSha256: 0999D6E81112649285CEAD774AF3355759AC0C1CD8DE0534A8634FFEE83D6D3B
ManifestType: installer
ManifestVersion: 1.12.0