# Created with YamlCreate.ps1 v2.7.1 $debug=QUSU.CRLF.7-6-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Podman.CLI
PackageVersion: 5.8.2
InstallerType: wix
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- podman
ReleaseDate: 2026-03-11
AppsAndFeaturesEntries:
- UpgradeCode: '{A6A9DD9C-0732-44BA-9279-FFE22EA50671}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/containers/podman/releases/download/v5.8.2/podman-installer-windows-amd64.msi
  InstallerSha256: EDA54F26F9695D198D9A679FA45AE24BA35B78444F432B5FE0C122C5A3624C57
  ProductCode: '{0A158080-B8AE-48A8-AB30-DE6AB3E7D2AE}'
- Architecture: arm64
  InstallerUrl: https://github.com/containers/podman/releases/download/v5.8.2/podman-installer-windows-arm64.msi
  InstallerSha256: 77E9810E7598EF588B1FE7A850BF6BAF572B30545DDE82879A31638708C97BCD
  ProductCode: '{F8C24418-24BC-42B6-97DD-7ACDFFB33AD9}'
ManifestType: installer
ManifestVersion: 1.12.0
