# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Telegram.TelegramDesktop
PackageVersion: 6.7.2
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- tg
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tsetup-x64.6.7.2.exe
  InstallerSha256: E52F86770430D1A005F067EB6EF65127A19B607A250C4017BDD80970E61C1B3C
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tsetup.6.7.2.exe
  InstallerSha256: 45A1BE266C71F7BC698E6BB6101EF208BE2BD01AEAA87A84BD54EE5A703F88FE
  UpgradeBehavior: install
- Architecture: arm64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tsetup-arm64.6.7.2.exe
  InstallerSha256: E6FBB5758EB31ED3066CD2152DEB471392506CE947B6125E5B913A3FFBAD0F86
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Telegram\Telegram.exe
    PortableCommandAlias: Telegram.exe
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tportable-x64.6.7.2.zip
  InstallerSha256: 9F16145F7C937B1087352A08B12E803D69854C338563B175831EEE2C2F6697B2
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Telegram\Telegram.exe
    PortableCommandAlias: Telegram.exe
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tportable.6.7.2.zip
  InstallerSha256: CABCC0D192D9CC148304641128D30427291242727949CB3636AC40779672F06C
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Telegram\Telegram.exe
    PortableCommandAlias: Telegram.exe
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v6.7.2/tportable-arm64.6.7.2.zip
  InstallerSha256: F39664EFE5C10253972C26B3026BE03BA6CD84D8E80D02D4BA03A1DFD2D300F1
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-04-03
