# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: CDESoftware.BTM-2026
PackageVersion: 2026.61.1150
InstallerType: exe
InstallerSwitches:
  Silent: /exenoui /qn /norestart
Installers:
- Architecture: x86
  InstallerUrl: https://static.cdesoftware.com/btm2026/BTM2026INSTALLER.EXE
  InstallerSha256: 6FA1BB11FB9DCDA38110C1A5F2C0EBADA8E15AE5F22C2B12B921579B913C1041
ManifestType: installer
ManifestVersion: 1.10.0
