# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Namespace.nsc
PackageVersion: 0.0.573
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bazel-credential-nsc.exe
- RelativeFilePath: docker-credential-nsc.exe
- RelativeFilePath: nsc.exe
Commands:
- nsc
ReleaseDate: 2026-09-17
Installers:
- Architecture: x64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.573/nsc_0.0.573_windows_amd64.zip
  InstallerSha256: B2CA1F838CEE338893090D38BFC90FFD6D4234A027B0486D4676A77AD4A7AACC
- Architecture: arm64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.573/nsc_0.0.573_windows_arm64.zip
  InstallerSha256: E9E4A7800DFF07874EB7A0396B927D2777B8C49FD3F7768ABF934EC5C86446C8
ManifestType: installer
ManifestVersion: 1.12.0
