# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1779581864-g6cae00
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1779581864-g6cae00/amp-windows-x64-baseline.exe
  InstallerSha256: 7FBDB281C11E3B87945CA44F1C3532F750844F790C8EDBAF174C174FD3E641EC
ManifestType: installer
ManifestVersion: 1.12.0
