# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dapr.CLI
PackageVersion: 1.18.1
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{6B1D177B-3F2E-44A1-B36D-46CBB7CE37AE}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dapr/cli/releases/download/v1.18.1/dapr.msi
  InstallerSha256: 3877AEBA68DF9826A8E788C7CC8EDA32B106339C6C10736B0C9F744F7F5B1C7F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-11
