# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DevinCook.Flowgorithm
PackageVersion: 4.5.0
InstallerType: zip
FileExtensions:
- fcht
- fclr
- fpgt
- fprg
ReleaseDate: 2024-10-08
Installers:
- Architecture: x86
  NestedInstallerType: msi
  NestedInstallerFiles:
  - RelativeFilePath: Flowgorithm Installer.msi
  InstallerUrl: http://flowgorithm.org/download/files/Flowgorithm-Setup.zip
  InstallerSha256: EF6D3A813F4408157590613877F03686CF0A3F2621391A4DA905A7568C0AD765
  ProductCode: '{EA9DDEFB-655C-4FEC-9BF4-91DDBCE23C8D}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{666565F3-AEB8-45B8-A453-E5576392BCB2}'
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Flowgorithm.exe
  InstallerUrl: http://flowgorithm.org/download/files/Flowgorithm-exe-only.zip
  InstallerSha256: 50A845F5723D011AC606A2235D914EC05C927497191C7993FF44ECCEF524F147
ManifestType: installer
ManifestVersion: 1.9.0
