# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: pyRevit.pyRevit
PackageVersion: 6.5.2.26175
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- pyrevit
- pyrevit-autocomplete
- pyrevit-doctor
- pyrevit-telemetryserver
ProductCode: f2a3da53-6f34-41d5-abbd-389ffa7f4d5f_is1
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pyrevitlabs/pyRevit/releases/download/v6.5.2.26175+2113/pyRevit_6.5.2.26175_admin_signed.exe
  InstallerSha256: 91474D63D229CDC0A301E71EC194209E2090BBE5526E2C43FD1706EFE0A63507
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-06-24
