# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Discord.Discord.Canary.arm64
PackageVersion: 1.0.220
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- discord
ProductCode: DiscordCanary
Installers:
- Architecture: arm64
  InstallerUrl: https://canary.dl2.discordapp.net/distro/app/canary/win/arm64/1.0.220/DiscordCanarySetup.exe
  InstallerSha256: 1FD287AFFFE5F14610BA0105A6BF73FE9FA5FD85537EEB56A6B2F1C0CEA9CB66
ManifestType: installer
ManifestVersion: 1.12.0
