# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: termio.soft-jp.com.TermioWin
PackageVersion: 1.2.21
PackageLocale: en-US
Publisher: termio.soft-jp.com
PackageName: TermioWin
License: Freemium
ShortDescription: A lightweight local web terminal for Windows with AI CLI integration.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
