# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OWASP.ThreatDragon
PackageVersion: 2.6.2
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: 970b2d4f-cdcc-5118-bc8b-330d878ca743
ReleaseDate: 2026-05-10
AppsAndFeaturesEntries:
- DisplayName: Threat-Dragon-ng 2.6.2
  Publisher: OWASP Threat Dragon
  ProductCode: 970b2d4f-cdcc-5118-bc8b-330d878ca743
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/OWASP/threat-dragon/releases/download/v2.6.2/Threat-Dragon-ng-Setup-2.6.2.exe
  InstallerSha256: 880D8AB674844D0EF0BD68035985BB1672AE13274E3B7F614452159205B05710
ManifestType: installer
ManifestVersion: 1.12.0
