# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CreativeForce.Kelvin
PackageVersion: 6.4.0
UpgradeBehavior: install
ReleaseDate: 2026-06-15
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://download.creativeforce.io/released-files.042024/prod/kelvin/win/Kelvin-6.4.0-win.exe
  InstallerSha256: A842ED1B1091643EF674FF45C63A27B80960ACAB68D60B3CB09167BF9BB3CA83
  InstallerSwitches:
    Upgrade: --updated
    Custom: /currentuser
  ProductCode: aae3a3cf-9ee8-53df-bf5e-4c41312da66d
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://download.creativeforce.io/released-files.042024/prod/kelvin/win/Kelvin-6.4.0-win.exe
  InstallerSha256: A842ED1B1091643EF674FF45C63A27B80960ACAB68D60B3CB09167BF9BB3CA83
  InstallerSwitches:
    Upgrade: --updated
    Custom: /allusers
  ProductCode: aae3a3cf-9ee8-53df-bf5e-4c41312da66d
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://download.creativeforce.io/released-files.042024/prod/kelvin/win/Kelvin-6.4.0-win.msi
  InstallerSha256: 5412E2D3FA3877E2CD1A97357A515E7B9557D8DA8E8E2276228D55073EA06FD4
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{122F7D26-5AF8-455C-AEE4-E0BDA51F4641}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{43D5EF01-191A-571C-8483-7EB293F5AA4F}'
ManifestType: installer
ManifestVersion: 1.12.0
