# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Flowersauce.FSClicker
PackageVersion: 1.4.0
PackageLocale: en-US
Publisher: Flowersauce
PublisherUrl: https://github.com/flowersauce
PublisherSupportUrl: https://github.com/flowersauce/Flori-Input/issues
PackageName: Flori Input
PackageUrl: https://github.com/flowersauce/Flori-Input
License: MIT
LicenseUrl: https://github.com/flowersauce/Flori-Input/blob/HEAD/LICENSE
ShortDescription: A Windows keyboard and mouse input automation tool.
Tags:
- input
- automation
- keyboard
- mouse
- windows
ReleaseNotesUrl: https://github.com/flowersauce/Flori-Input/releases/tag/v1.4.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
