# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.Aspire
PackageVersion: 13.5.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: aspire.exe
  PortableCommandAlias: aspire
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
Commands:
- aspire
Installers:
- Architecture: x64
  InstallerUrl: https://ci.dot.net/public/aspire/13.5.0-preview.1.26417.10/aspire-cli-win-x64-13.5.0.zip
  InstallerSha256: 3F660996F5839EDF8D29F72F728F23A64745B4B3A5D3812DFD820DC7405ACC2E
- Architecture: arm64
  InstallerUrl: https://ci.dot.net/public/aspire/13.5.0-preview.1.26417.10/aspire-cli-win-arm64-13.5.0.zip
  InstallerSha256: B64E940E2942CF7E341E79F902D2EB3F468599EEF0975AD1B77F627EC97489BD
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-08-18
