# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: COPASI.COPASI
PackageVersion: Build-309
PackageLocale: en-US
Publisher: copasi.org
PublisherUrl: https://copasi.org/
PublisherSupportUrl: https://copasi.org/Support/
PackageName: COPASI
PackageUrl: https://copasi.org/Download/
License: Artistic-2.0
LicenseUrl: https://github.com/copasi/COPASI/blob/HEAD/license.txt
ShortDescription: Biochemical System Simulator
Description: |-
  COPASI is a software application for simulation and analysis of biochemical networks and their dynamics.
  COPASI is a stand-alone program that supports models in the SBML standard and can simulate their behavior using ODEs, SDEs, or Gillespie's stochastic simulation algorithm. Arbitrary discrete events can be included in such simulations. COPASI provides a set analysis methods and parameter estimation.
Tags:
- analysis
- biochemical
- biochemistry
- simulation
ReleaseNotes: |-
  New Features since COPASI 4.46 (Build 300)
  - Simulation Engine
    - Multi threading for population based optimization methods Differential Evolution, Evolutionary Programming, Evolution Strategy (SRES), Genetic Algorithm, Genetic Algorithm SR, Particle Swarm, and Scatter Search speeding up optimization and parameter estimation tasks.
  - Command Line (CopasiSE)
    - Added option to import and export task settings.
  Bug Fixes and Enhancements since COPASI 4.46 (Build 300)
  - Graphical User Interface (CopasiUI)
    - Opening files from URL when clicking on a link on a website is again functional.
    - Tool Profile Likelihood: This tool now also works with just one parameter.
    - Tool Create Events from Time Series Experiment allows now the selection of the experiment if multiple experiments are specified.
    - Scan Sub Task Output: The tool tips for the check boxes have been corrected.
    - Parameter Estimation: Improved behavior when stopping the process to return complete plots.
  - Simulation Engine
    - Time Course RADAU5: Improved method to properly support multi threading.
    - Optimization Scatter Search: Fixed issue detecting improvements in solution.
    - Increased stack size under Windows to prevent randomly occurring access violations.
ReleaseNotesUrl: https://github.com/copasi/COPASI/releases/tag/Build-309
Documentations:
- DocumentLabel: User Manual
  DocumentUrl: https://copasi.org/Support/User_Manual/
- DocumentLabel: Video Tutorials
  DocumentUrl: https://copasi.org/Support/Video_Tutorials/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
