# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.Corretto.11.JDK
PackageVersion: 11.0.31.11
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ReleaseDate: 2026-04-22
Installers:
- Architecture: x86
  InstallerUrl: https://corretto.aws/downloads/resources/11.0.31.11.1/amazon-corretto-11.0.31.11.1-windows-x86.msi
  InstallerSha256: CA20CC8D55D0C24A049CB05A185528EAE2F51BB351327C190589E406B20F29CB
  ProductCode: '{CD769063-4156-45FF-96A8-AF2AEA13BF82}'
  AppsAndFeaturesEntries:
  - ProductCode: '{CD769063-4156-45FF-96A8-AF2AEA13BF82}'
    UpgradeCode: '{E8E05A52-8ACE-454C-A484-8A0988DE583F}'
- Architecture: x64
  InstallerUrl: https://corretto.aws/downloads/resources/11.0.31.11.1/amazon-corretto-11.0.31.11.1-windows-x64.msi
  InstallerSha256: C941F6D876CDA84E7D7BBAD78DF2F27FCB75F5D68DEC276C38F2408FBE0F1286
  ProductCode: '{5F0877ED-6EE3-4443-9E03-B5AE7704C6FD}'
  AppsAndFeaturesEntries:
  - ProductCode: '{5F0877ED-6EE3-4443-9E03-B5AE7704C6FD}'
    UpgradeCode: '{1A5942C5-BB39-4C51-839B-639CB971E81E}'
ManifestType: installer
ManifestVersion: 1.12.0
