# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Casey.Intermodal
PackageVersion: 0.1.16
PackageLocale: en-US
Publisher: Casey Rodarmor
PublisherUrl: https://github.com/casey
PublisherSupportUrl: https://github.com/casey/intermodal/issues
Author: Casey Rodarmor
PackageName: Intermodal
PackageUrl: https://github.com/casey/intermodal
License: CC0-1.0
LicenseUrl: https://github.com/casey/intermodal/blob/HEAD/LICENSE
ShortDescription: |
  A command-line utility for BitTorrent torrent file creation, verification, and more.
Description: |-
  Intermodal is a user-friendly and featureful command-line BitTorrent metainfo
  utility. The binary is called imdl and runs on Linux, Windows, and macOS.

  At the moment, creation, viewing, and verification of .torrent files is
  supported.
Moniker: imdl
Tags:
- bittorrent
- cli
- rust
ReleaseNotes: |-
  Added
  - Allow passing arguments to run() (#562 by casey)
  Misc
  - Add profile recipe (#560 by casey)
  - Exclude unnecessary files from crate (#558 by casey)
ReleaseNotesUrl: https://github.com/casey/intermodal/releases/tag/v0.1.16
ManifestType: defaultLocale
ManifestVersion: 1.12.0
