# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: cst8t.gitmun
PackageVersion: 0.9.2
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Git.Git
ReleaseDate: 2026-07-26
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/cst8t/gitmun/releases/download/v0.9.2/Gitmun_0.9.2_x64-setup.exe
  InstallerSha256: 7AF802DDFB4D8B996B0E8C97003D38B00E89FD894AEC5CA5E08CFC357C9B204F
  InstallerSwitches:
    Custom: /SkipGitCheck
  ProductCode: Gitmun
  AppsAndFeaturesEntries:
  - ProductCode: Gitmun
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Gitmun'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cst8t/gitmun/releases/download/v0.9.2/Gitmun_0.9.2_x64.msi
  InstallerSha256: B031DB74B621CCB24134142811D519D7AB5155B07D3C7330D34525AD4502ECD7
  ProductCode: '{8F3BA355-9008-433A-9648-CB544D933143}'
  AppsAndFeaturesEntries:
  - ProductCode: '{8F3BA355-9008-433A-9648-CB544D933143}'
    UpgradeCode: '{CFD38D6F-06D8-500B-8162-2815A511EBAF}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Gitmun'
ManifestType: installer
ManifestVersion: 1.12.0
