# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.IntelliJIDEA.Ultimate.EAP
PackageVersion: 261.23567.71
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- groovy
- ipr
- java
- kt
- kts
ProductCode: IntelliJ IDEA 261.23567.71
ReleaseDate: 2026-04-15
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/idea/idea-261.23567.71.exe
  InstallerSha256: E04CF7D6888C888A3628A62721A3A0F0A0A5054DE1EC737A40ED04092132C226
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/idea/idea-261.23567.71.exe
  InstallerSha256: E04CF7D6888C888A3628A62721A3A0F0A0A5054DE1EC737A40ED04092132C226
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/idea/idea-261.23567.71-aarch64.exe
  InstallerSha256: ABBD5FEA1B3B617FE0F05E8108E5B705B849252094039C205631059A01353AFE
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/idea/idea-261.23567.71-aarch64.exe
  InstallerSha256: ABBD5FEA1B3B617FE0F05E8108E5B705B849252094039C205631059A01353AFE
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
