# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixDesktop
PackageVersion: 1.25.4
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: ReasonixReasonix
ReleaseDate: 2026-08-16
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/desktop-v1.25.4/Reasonix-windows-amd64-installer.exe
  InstallerSha256: FA3974911735949884D0665B6F6097FD82B440AC27C02B95238A0CF83058C42F
ManifestType: installer
ManifestVersion: 1.12.0
