# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: HomeOps.wmux
PackageVersion: 0.3.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wmux.exe
  PortableCommandAlias: wmux
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/HomeOps/wmux/releases/download/v0.3.1/wmux-0.3.1-x64.zip
  InstallerSha256: 605F869EF4BDFC43280FD434BA7B0E125A73A5FB56DD16CA3FA73E517BF3B066
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-08-02
