# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tombi-toml.tombi
PackageVersion: 1.5.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tombi.exe
  PortableCommandAlias: tombi
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Microsoft\WinGet\Packages\tombi-toml.tombi__DefaultSource'
  Files:
  - RelativeFilePath: tombi.exe
    FileType: launch
    InvocationParameter: --version
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.5.3/tombi-cli-1.5.3-x86_64-pc-windows-msvc.zip
  InstallerSha256: 9A45EC3DF1DD2693E7ECE01F552B0D1EF1885B8D701F396EBC0236165C554C0E
- Architecture: arm64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.5.3/tombi-cli-1.5.3-aarch64-pc-windows-msvc.zip
  InstallerSha256: 102848B6B57DEC5AF5BB258C1E4937B18338E102AFEE57C4B12A6133A7C49937
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-08
