# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.fi
PackageVersion: "155.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/155.0/win32/fi/Thunderbird%20Setup%20155.0.exe
  InstallerSha256: 49D2B23928334AFBF1044E8E5DA4D6A9B56B7DA7C91EF0F15745A197F13C563B
  ProductCode: Mozilla Thunderbird 155.0 (x86 fi)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/155.0/win64/fi/Thunderbird%20Setup%20155.0.exe
  InstallerSha256: 5CE1CD85A0B78DF55E032B81A8722D3CC2D3008A91B5D8FA604A8A024386DA6A
  ProductCode: Mozilla Thunderbird 155.0 (x64 fi)
ManifestType: installer
ManifestVersion: 1.12.0
