# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MediaHuman.YouTubeToMP3Converter
PackageVersion: 3.9.19
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: MediaHuman YouTube to MP3 Converter_is1
ReleaseDate: 2026-03-18
Installers:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/YouTubeToMP3.exe
  InstallerSha256: 3FC9FA8081804C887196EF082F9E155D5476519569113887BC3C1E1A90BB6B2C
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/YouTubeToMP3-x64.exe
  InstallerSha256: 05C4434FAEC7CA9F32FC27258626A0ADE4245F3E6F1543BDFB412EE9E16505F8
ManifestType: installer
ManifestVersion: 1.12.0
