# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Warp.Warp
PackageVersion: v0.2026.06.03.09.49.stable_03
InstallerType: inno
Protocols:
- warp
ProductCode: warp-terminal-stable_is1
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://app.warp.dev/download/windows?version=v0.2026.06.03.09.49.stable_03&arch=x86_64
  InstallerSha256: 2899E62559A869BF11B0BA0E2F173352BC683B1C0B5865BC9FF2CAE574D881E6
  InstallerSwitches:
    Custom: /CURRENTUSER
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: x64
  Scope: machine
  InstallerUrl: https://app.warp.dev/download/windows?version=v0.2026.06.03.09.49.stable_03&arch=x86_64
  InstallerSha256: 2899E62559A869BF11B0BA0E2F173352BC683B1C0B5865BC9FF2CAE574D881E6
  InstallerSwitches:
    Custom: /ALLUSERS
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  Scope: user
  InstallerUrl: https://app.warp.dev/download/windows?version=v0.2026.06.03.09.49.stable_03&arch=arm64
  InstallerSha256: 7E9DB00B01EF0B725E4DAD82D5D18484B0A78F09262F603E940E17728736F165
  InstallerSwitches:
    Custom: /CURRENTUSER
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://app.warp.dev/download/windows?version=v0.2026.06.03.09.49.stable_03&arch=arm64
  InstallerSha256: 7E9DB00B01EF0B725E4DAD82D5D18484B0A78F09262F603E940E17728736F165
  InstallerSwitches:
    Custom: /ALLUSERS
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
