# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: axpnet.AeroFTP
PackageVersion: 3.7.6
InstallerLocale: en-US
ReleaseDate: 2026-05-08
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/axpdev-lab/aeroftp/releases/download/v3.7.6/AeroFTP_3.7.6_x64-setup.exe
  InstallerSha256: 26318E95247AA5346C0718EC36B3FEEE8CB96E2C025E492026D98C951AB9A67E
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  ProductCode: AeroFTP
  AppsAndFeaturesEntries:
  - Publisher: aeroftp
    ProductCode: AeroFTP
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\AeroFTP'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/axpdev-lab/aeroftp/releases/download/v3.7.6/AeroFTP_3.7.6_x64_en-US.msi
  InstallerSha256: C6B40476747659E84E296943093405A0C9E89E9BE1E9F24E5663CFE3ACC67753
  ProductCode: '{BA8BCDAE-C051-49A2-810B-4883FE4AAD67}'
  AppsAndFeaturesEntries:
  - Publisher: aeroftp
    ProductCode: '{BA8BCDAE-C051-49A2-810B-4883FE4AAD67}'
    UpgradeCode: '{3A660390-AA69-5CCD-A202-013C64158D37}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/AeroFTP'
ManifestType: installer
ManifestVersion: 1.12.0
