# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: KorayOrhun.SesliOkuma
PackageVersion: 1.0.2
InstallerLocale: tr-TR
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/korayorhun/SesliOkuma/releases/download/v1.0.2/SesliOkuma-Setup-1.0.2.exe
  InstallerSha256: CB5A18FBB15AD85E90F6CAB4F692C66971D41F01478E6AD3B0A64C7F38037F0C
ManifestType: installer
ManifestVersion: 1.6.0
