# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LunarWerxs.SageThumbs2K
PackageVersion: 0.4.9
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LunarWerxs/SageThumbs-2k/releases/download/v0.4.9/SageThumbs2K-Setup-0.4.9.exe
  InstallerSha256: E7104789901C68922F6FFF9BFB6986892B4A46F3D30F6D85444983DD8D6B058E
ManifestType: installer
ManifestVersion: 1.6.0
