# Automatically updated by the winget bot at 2026/May/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chrox.Readest
PackageVersion: 0.9.101
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Protocols:
- readest
FileExtensions:
- azw
- azw3
- cbz
- epub
- fb2
- mobi
- pdf
ProductCode: Readest
ReleaseDate: 2026-02-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/readest/readest/releases/download/v0.9.101/Readest_0.9.101_x64-setup.exe
  InstallerSha256: E08F698AB21D01BAA6F5D92A107B2CEE897F75894589D6E966F56C517ED62442
- Architecture: arm64
  InstallerUrl: https://github.com/readest/readest/releases/download/v0.9.101/Readest_0.9.101_arm64-setup.exe
  InstallerSha256: 90D503FC4597E278CABDB45CA2C0CA4A259E11F0DA571A351C320F4239EF2DE0
ManifestType: installer
ManifestVersion: 1.12.0
