# Created with YamlCreate.ps1 v2.7.2 $debug=NVS1.CRLF.7-6-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RyensX.OpenCodex
PackageVersion: 2.0.1
InstallerType: nullsoft # electron-builder
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: ce0e88bf-c4e1-5d5f-bd8c-44770c64a07a
ReleaseDate: 2026-06-17
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/RyensX/OpenCodex/releases/download/2.0.1/OpenCodex-2.0.1-win-x64.exe
  InstallerSha256: E359CD1F87589A414C4468810A55E9BA5651E1091446294CC9FBC3CE7B206FB0
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/RyensX/OpenCodex/releases/download/2.0.1/OpenCodex-2.0.1-win-x64.exe
  InstallerSha256: E359CD1F87589A414C4468810A55E9BA5651E1091446294CC9FBC3CE7B206FB0
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
