# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Databricks.DatabricksCLI
PackageVersion: 0.291.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: databricks.exe
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-03-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/databricks/cli/releases/download/v0.291.0/databricks_cli_0.291.0_windows_amd64.zip
  InstallerSha256: F9E3E13AB358F1FA3BAB245BA77D6C1F8D36269DE89842BE8ACDFCC96386104E
ManifestType: installer
ManifestVersion: 1.9.0
