# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Effekseer.Effekseer
PackageVersion: 1.7.3
PackageLocale: en-US
Publisher: Effekseer
PackageName: Effekseer
License: MIT
ShortDescription: This software is a particle effect editing tool. By incorporating runtimes and plug-ins, effects created in Effekseer can be played back in your application.
ManifestType: defaultLocale
ManifestVersion: 1.12.0