# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ZaferKilic.MDPlus
PackageVersion: 0.3.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{28108E63-E31F-49A0-B315-B945AC850AE0}'
ReleaseDate: 2026-07-29
AppsAndFeaturesEntries:
- Publisher: mdplus
  ProductCode: '{28108E63-E31F-49A0-B315-B945AC850AE0}'
  UpgradeCode: '{36756E2D-76C3-5A5D-9709-390474EC8206}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/MD Plus'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zaferkilic2024/md-plus/releases/download/v0.3.0/MD.Plus_0.3.0_x64_en-US.msi
  InstallerSha256: 3D193E52113B57F7C3BCBAAADA7D420BC308FD7FB161253AD31E9810370C6F03
ManifestType: installer
ManifestVersion: 1.12.0
