# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Proma.Proma
PackageVersion: 0.10.21
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- proma
FileExtensions:
- proma-backup
- proma-share
ProductCode: 7c277a67-1561-5044-94b9-16fb308e8209
ReleaseDate: 2026-05-31
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.proma.cool/releases/win-x64/Proma-0.10.21-setup.exe
  InstallerSha256: 848EC5F7D6767CC8D749541FF9497165FADF13EB81D4C742198CDC2FD571212C
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.proma.cool/releases/win-x64/Proma-0.10.21-setup.exe
  InstallerSha256: 848EC5F7D6767CC8D749541FF9497165FADF13EB81D4C742198CDC2FD571212C
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.10.0
