PackageIdentifier: CryptographicTriangles.TrianglesQt
PackageVersion: 5.9.20
PackageLocale: en-US
InstallerType: exe
InstallerScope: user
InstallerMode: interactive
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/SamiAhmed7777/triangles_v5/releases/download/v${VERSION}/Cryptographic-Triangles-${VERSION}-win-x64-setup.exe
    InstallerSha256: 3b4387f65be129534a2a879c4d7eef4cd8449caeee3a10fb2f80295c841085cd
ManifestType: installer
ManifestVersion: 1.6.0
