# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DesktopPlus.DesktopPlus
PackageVersion: 3.6.4-r1
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- github-windows
- x-github-client
- x-github-desktop-auth
ProductCode: DesktopPlus
ReleaseDate: 2026-07-28
AppsAndFeaturesEntries:
- ProductCode: DesktopPlus
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\DesktopPlus'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/desktop-plus/desktop-plus/releases/download/v3.6.4.1/DesktopPlus-v3.6.4.1-windows-x64.exe
  InstallerSha256: 773DEF289DA7FA1B2FEF0852382262F70F0BAA131558B5547723A72EE36F85CE
- Architecture: arm64
  InstallerUrl: https://github.com/desktop-plus/desktop-plus/releases/download/v3.6.4.1/DesktopPlus-v3.6.4.1-windows-arm64.exe
  InstallerSha256: E3131D2711ACEB52C26D85D3B2296727EFE1FB240F5B7C252A16B063E30C65A1
ManifestType: installer
ManifestVersion: 1.12.0
