# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Postman.Postman.arm64
PackageVersion: 12.29.4
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- postman
ProductCode: Postman
ReleaseDate: 2026-09-25
Installers:
- Architecture: arm64
  InstallerUrl: https://dl.pstmn.io/download/version/12.29.4/windows_arm64
  InstallerSha256: 7DB5A5B6057BE2D427F6E2C6B42EBE33406F90F3B07261858709DC73BF42629E
ManifestType: installer
ManifestVersion: 1.12.0
