# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: hatoo.oha
PackageVersion: 1.16.0
PackageLocale: en-US
Publisher: hatoo
PublisherUrl: https://github.com/hatoo
PublisherSupportUrl: https://github.com/hatoo/oha/issues
PackageName: oha
PackageUrl: https://github.com/hatoo/oha
License: MIT
LicenseUrl: https://github.com/hatoo/oha/blob/master/LICENSE
Copyright: Copyright (c) 2026 hatoo
ShortDescription: HTTP load generator, inspired by rakyll/hey with tui animation
Description: oha is a tiny program that sends some load to a web application and show realtime tui inspired by rakyll/hey. This program is written in Rust and powered by tokio and beautiful tui by ratatui.
ReleaseNotes: |-
  What's Changed
  - Avoid TenSeconds/TenMinutes time scales in summary output by @hatoo in https://github.com/hatoo/oha/pull/891
  - Tune HTTP/3 client performance by @hatoo in https://github.com/hatoo/oha/pull/892
  - Add --worker-threads flag to set the runtime thread count by @ChrisJr404 in https://github.com/hatoo/oha/pull/893
  - Update deps by @hatoo in https://github.com/hatoo/oha/pull/894
  New Contributors
  - @ChrisJr404 made their first contribution in https://github.com/hatoo/oha/pull/893
  Full Changelog: https://github.com/hatoo/oha/compare/v1.15.0...v1.16.0
ReleaseNotesUrl: https://github.com/hatoo/oha/releases/tag/v1.16.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
