# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.tg
PackageVersion: 153.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-07-28
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win32/tg/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: B1FC17B09EC7DC2A9FAA038AA9C1267AA9459A56D5D25B778EE6CC5CFCA4F1AA
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win64/tg/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: 8A7ABECB3237E0240D06613B5F6124A5011518D06F453879181C06E8AF7DE66A
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.0.1/win64-aarch64/tg/Firefox%20Setup%20153.0.1.exe
  InstallerSha256: 1E4080D1C8A3C06EABB2B299991C6B69273A01718519389CD867B6AF6135576D
ManifestType: installer
ManifestVersion: 1.12.0
