# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: gg.ai.ggcode-cli
PackageVersion: 1.3.72
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- ggcode
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/topcheer/ggcode/releases/download/v1.3.72/ggcode_1.3.72_windows_x64.msi
  InstallerSha256: 01809DFFAF6AF77AE4D4A0F3B6841481843E609D13C4D1545C6D393781D5174E
  ProductCode: '{EE0A0CBF-357B-4E0B-9FFE-421A1E4B131D}'
  AppsAndFeaturesEntries:
  - DisplayName: ggcode
    Publisher: GG AI Studio
    ProductCode: '{EE0A0CBF-357B-4E0B-9FFE-421A1E4B131D}'
    UpgradeCode: '{B3C4D5E6-F7A8-9012-BCDE-F23456789012}'
- Architecture: arm64
  InstallerUrl: https://github.com/topcheer/ggcode/releases/download/v1.3.72/ggcode_1.3.72_windows_arm64.msi
  InstallerSha256: 0E53FE9CA60613DC28A9920292DA8625D530D646AA34A645789B27E5B92F52E2
  ProductCode: '{2F17B4E6-6C51-41DE-A50D-AEE3E61E0CBA}'
  AppsAndFeaturesEntries:
  - DisplayName: ggcode
    Publisher: GG AI Studio
    ProductCode: '{2F17B4E6-6C51-41DE-A50D-AEE3E61E0CBA}'
    UpgradeCode: '{B3C4D5E6-F7A8-9012-BCDE-F23456789012}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-06-17
