# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: HetoAndrade.VozDigitada
PackageVersion: 1.9.2004
InstallerType: inno
InstallerLocale: pt-BR
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hetoandrade/hetoandrade.github.io/releases/download/vozdigitada-v1.9.2004/VozDigitada_Setup_v1.9.2004.exe
    InstallerSha256: 2EA54BEF3FC428BBC3C78586D6E2FA6D6B257C80B75812F51CDC3324D6C6A0B7
    ProductCode: "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "VozDigitada versão 1.9.2004"
        Publisher: "VozDigitada"
        ProductCode: "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}_is1"
ManifestType: installer
ManifestVersion: 1.10.0
