PackageIdentifier: Sylin.Ghostlight
PackageVersion: 0.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ghostlight-v0.8.0-x86_64-pc-windows-msvc\ghostlight.exe
    PortableCommandAlias: ghostlight
  - RelativeFilePath: ghostlight-v0.8.0-x86_64-pc-windows-msvc\ghostlight-mcp-connector.exe
    PortableCommandAlias: ghostlight-mcp-connector
  - RelativeFilePath: ghostlight-v0.8.0-x86_64-pc-windows-msvc\ghostlight-browser-connector.exe
    PortableCommandAlias: ghostlight-browser-connector
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/sylin-org/ghostlight/releases/download/v0.8.0/ghostlight-v0.8.0-x86_64-pc-windows-msvc.zip
    InstallerSha256: db0c0f5a95f75145eae496359e5bf7e0e388fd05a429c15956df557ed2be9fea
ManifestType: installer
ManifestVersion: 1.6.0
