# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ShiningLight.OpenSSL.Dev
PackageVersion: 4.0.1
Scope: machine
Commands:
- openssl
Installers:
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://slproweb.com/download/Win32OpenSSL-4_0_1.msi
  InstallerSha256: 8D64CB05325694E5843E3BE40B77A62E8E55FB574349033B23283A7AFD18CA67
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  ProductCode: '{92B1193F-5EE9-40F1-8C84-A844FC88F0B6}'
  AppsAndFeaturesEntries:
  - DisplayName: OpenSSL 4.0.1 (32-bit)
    ProductCode: '{92B1193F-5EE9-40F1-8C84-A844FC88F0B6}'
    UpgradeCode: '{7B69213B-526B-4E63-B03A-E5701A74CCD5}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\OpenSSL'
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://slproweb.com/download/Win64OpenSSL-4_0_1.msi
  InstallerSha256: BCE7D25EBE7AE2A9FE8AB5CAD51E1346CA80100CF9B3D5221DF03CA5EE84197D
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{FD43E7B2-FD3E-41D9-8E0D-7C3A8F6C596F}'
  AppsAndFeaturesEntries:
  - DisplayName: OpenSSL 4.0.1 (64-bit)
    ProductCode: '{FD43E7B2-FD3E-41D9-8E0D-7C3A8F6C596F}'
    UpgradeCode: '{8BA62D91-E3D5-4E94-AEDB-7BB3BA1B578E}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\OpenSSL'
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://slproweb.com/download/Win64ARMOpenSSL-4_0_1.msi
  InstallerSha256: B4B5783264FA25977053CA16E3971C732C3B0DCB14BC94A03EBF4F9D3202A462
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
  ProductCode: '{7C450C64-B256-4A54-9FB0-1ADA763B4014}'
  AppsAndFeaturesEntries:
  - DisplayName: OpenSSL 4.0.1 for ARM (64-bit)
    ProductCode: '{7C450C64-B256-4A54-9FB0-1ADA763B4014}'
    UpgradeCode: '{48963397-0F00-40E0-A37F-740EBBA6E4D5}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\OpenSSL'
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://slproweb.com/download/Win32OpenSSL-4_0_1.exe
  InstallerSha256: F485C425A552C686A6BBBC2A5B5C0B3AE53DB42F620A27BBB35EAE8ECBCBECDD
  ProductCode: OpenSSL (32-bit)_is1
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://slproweb.com/download/Win64OpenSSL-4_0_1.exe
  InstallerSha256: 1B21347A3DB5ED62326E0D732F3FE50ECE08E9361FD770F537DCF901FD13AC24
  ProductCode: OpenSSL (64-bit)_is1
- Architecture: arm64
  InstallerType: inno
  InstallerUrl: https://slproweb.com/download/Win64ARMOpenSSL-4_0_1.exe
  InstallerSha256: 397146C4317E84DBAD20F8A3222B0AF6414DB8DB11A8A3BFE7DE11990B39CBAA
  ProductCode: OpenSSL for ARM (64-bit)_is1
ManifestType: installer
ManifestVersion: 1.12.0
