# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Servo.Servo.Nightly
PackageVersion: "1.0"
InstallerType: burn
Scope: machine
Protocols:
- http
- https
ProductCode: '{5E1C3C24-9C2E-4574-B845-8EFEF41B642E}'
ReleaseDate: 2026-08-10
AppsAndFeaturesEntries:
- DisplayName: ServoShell
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-08-10/servo-x86_64-windows-msvc.exe
  InstallerSha256: CD30CE7F000DB3A5A11696D0636EA32F26613F28ABB252A8D768DD4DEA0463E2
ManifestType: installer
ManifestVersion: 1.12.0
