# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: wl-std.pulse
PackageVersion: "2.1"
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  InstallerUrl: https://dl1.wl-std.com/Pulse-2.1-Setup.exe
  InstallerSha256: B00540B4129546584A3499BBE988B7B3130FC3DC463B5174F41A047392DAADE8
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-21
