# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HongMinhee.Hongdown
PackageVersion: 0.4.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: hongdown.exe
Commands:
- hongdown
ReleaseDate: 2026-06-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dahlia/hongdown/releases/download/0.4.3/hongdown-0.4.3-x86_64-pc-windows-msvc.zip
  InstallerSha256: DCD5753702C0B24F5FB7432A3D8683044FC7D5B897C6E4449F49120ADE9CA087
- Architecture: arm64
  InstallerUrl: https://github.com/dahlia/hongdown/releases/download/0.4.3/hongdown-0.4.3-aarch64-pc-windows-msvc.zip
  InstallerSha256: 202E3ED50B774AC2AB9B0855BD82F012906F56A1CA07C3CE3024F938EFF64500
ManifestType: installer
ManifestVersion: 1.12.0
