# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SpiceLogic.8051Disassembler
PackageVersion: 5.0.0
InstallerType: exe
Scope: user
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: 8051 Disassembler
  Publisher: SpiceLogic Inc.
Installers:
- Architecture: x64
  InstallerUrl: https://spicelogic.com/download/8051hexExplorer/5.0.0
  InstallerSha256: 37D09A3EF0B148BE38B205DF4AB6648C8B0D4A36BEE05BB8D6A7C8C5B87519F5
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-25
