# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: usual2970.Certimate
PackageVersion: 0.4.25
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: certimate.exe
  PortableCommandAlias: certimate
Commands:
- certimate
ReleaseDate: 2026-06-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/certimate-go/certimate/releases/download/v0.4.25/certimate_v0.4.25_windows_amd64.zip
  InstallerSha256: CA0BFEEF34D8FCB39F1E63FE6057DDDCACD0FD2CF71C71F74A3C00ED0941F82A
- Architecture: arm64
  InstallerUrl: https://github.com/certimate-go/certimate/releases/download/v0.4.25/certimate_v0.4.25_windows_arm64.zip
  InstallerSha256: FD2F536A73CA232B95324CC0C0D2C4278A2849F4E0C49DD573C82D0332B15E15
ManifestType: installer
ManifestVersion: 1.12.0
