# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mblua.AgentsCommander
PackageVersion: 0.39.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mblua/AgentsCommander/releases/download/v0.39.0/Agents.Commander_0.39.0_x64-setup.exe
  InstallerSha256: 66740432355BB6CB37A0E4667D0A3B4460E4C28665456D531A76589E4081DF86
ManifestType: installer
ManifestVersion: 1.12.0
