# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ShakaProject.ShakaPackager
PackageVersion: 3.6.1
PackageLocale: en-US
Publisher: Shaka Project
PublisherUrl: https://shaka-project.github.io/
PublisherSupportUrl: https://github.com/shaka-project/shaka-packager/issues
PackageName: Shaka Packager
PackageUrl: https://shaka-project.github.io/shaka-packager/html/
License: Freeware
LicenseUrl: https://github.com/shaka-project/shaka-packager/blob/HEAD/LICENSE
Copyright: Copyright 2026, Google LLC. All rights reserved.
ShortDescription: A media packaging and development framework for VOD and Live DASH and HLS applications, supporting Common Encryption for Widevine and other DRM Systems.
Tags:
- dash
- drm
- encryption
- fairplay
- hls
- live
- marlin
- media
- packaging
- playready
- video
- vod
- widevine
ReleaseNotes: |-
  Bug Fixes
  - DVB-Teletext: heartbeat mechanism and segment alignment with video/audio (#1535) (19dbd20), closes #1428 #1401 #1355 #1430
  - HLS - remove CLOSED-CAPTIONS from EXT-X-I-FRAME-STREAM-INF (#1551) (16a2462)
  - Upgrade deps that are meant for older versions of CMake (#1508) (e46b759)
ReleaseNotesUrl: https://github.com/shaka-project/shaka-packager/releases/tag/v3.6.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
