# Automatically updated by the winget bot at 2026/Jun/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Softplicity.PDFCombine
PackageVersion: 8.1.0.12
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- PDF
ProductCode: PDF Combine_is1
ReleaseDate: 2025-10-13
AppsAndFeaturesEntries:
- ProductCode: PDF Combine_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://www.coolutils.com/Downloads/PDFCombine.exe
  InstallerSha256: 48A0788B23069AFA51A12C22C119EB34376955FD872CF2C1DCB4E7AB4E296DB0
ManifestType: installer
ManifestVersion: 1.12.0
