# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wakatime.CLIWakatime
PackageVersion: 2.14.10
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-05-28
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-386.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.14.10/wakatime-cli-windows-386.zip
  InstallerSha256: 2F7762C82633228D16BC745AD87C9EBAD9C5312ADE3B1EA067383308110243C1
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-amd64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.14.10/wakatime-cli-windows-amd64.zip
  InstallerSha256: 22E726386E82991E6127749018895DBD9EB66E7BCA7960948E2E5F97BA1B1535
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-arm64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.14.10/wakatime-cli-windows-arm64.zip
  InstallerSha256: 23B6EA0BE49C6AB97C2484CB54F23252D7C64BCCEB87D0C9F25829229E86D098
ManifestType: installer
ManifestVersion: 1.12.0
