# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FluxCD.Flux
PackageVersion: 2.8.5
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: flux.exe
ReleaseDate: 2026-04-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/fluxcd/flux2/releases/download/v2.8.5/flux_2.8.5_windows_amd64.zip
  InstallerSha256: C047CEF654C9C6439D324CEB947CCAFF1B96928F604A9F19CE498B892212F900
- Architecture: arm64
  InstallerUrl: https://github.com/fluxcd/flux2/releases/download/v2.8.5/flux_2.8.5_windows_arm64.zip
  InstallerSha256: 36555CABF30BC1532552C202D4C29CA7D024478F9E919AC770592FD04A2E929C
ManifestType: installer
ManifestVersion: 1.12.0
