# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jdx.mise
PackageVersion: 2026.9.9
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mise/bin/mise-shim.exe
  PortableCommandAlias: mise-shim
- RelativeFilePath: mise/bin/mise.exe
  PortableCommandAlias: mise
UpgradeBehavior: install
ReleaseDate: 2026-09-15
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.9.9/mise-v2026.9.9-windows-x64.zip
  InstallerSha256: F758EE4AFE061CCCD4587C0108C147209A7CB2372704909A8B9D5E230203EC07
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.9.9/mise-v2026.9.9-windows-arm64.zip
  InstallerSha256: 1BF02A41BE9C5467B6AAA2B29149C15BA639A425F46302CFD759CFA3FFE4C0BE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
