# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.PyCharm
PackageVersion: "2026.2"
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- ipr
- py
ProductCode: PyCharm 2026.2
ReleaseDate: 2026-07-21
AppsAndFeaturesEntries:
- DisplayVersion: 262.8665.309
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/python/pycharm-2026.2.exe
  InstallerSha256: 6D0E4A1695FB5ED00ED3A97569D78AC9A9AEABBE265A12D05CB2A044660F75BE
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/python/pycharm-2026.2.exe
  InstallerSha256: 6D0E4A1695FB5ED00ED3A97569D78AC9A9AEABBE265A12D05CB2A044660F75BE
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/python/pycharm-2026.2-aarch64.exe
  InstallerSha256: 2E8F901CE6C8850AD64ED8CD647422EF0DB292A6AEE7481C37D91A9586FEC842
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/python/pycharm-2026.2-aarch64.exe
  InstallerSha256: 2E8F901CE6C8850AD64ED8CD647422EF0DB292A6AEE7481C37D91A9586FEC842
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
