# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KoukeNeko.TaigaCLI
PackageVersion: 0.6.0
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/KoukeNeko/taiga-cli/releases/download/v0.6.0/taiga_0.6.0_windows_amd64.zip
  InstallerSha256: FB03C313CC0AAC40F6E9610DA592D5A0C2EBDBE0C805931D5C64AEAE2D91CB41
  NestedInstallerFiles:
  - RelativeFilePath: taiga_0.6.0_windows_amd64\taiga.exe
    PortableCommandAlias: taiga
- Architecture: arm64
  InstallerUrl: https://github.com/KoukeNeko/taiga-cli/releases/download/v0.6.0/taiga_0.6.0_windows_arm64.zip
  InstallerSha256: 9D0EF627CD3ECE400773122EAA62A0D597FF9931F6543C0251E1D959591AED59
  NestedInstallerFiles:
  - RelativeFilePath: taiga_0.6.0_windows_arm64\taiga.exe
    PortableCommandAlias: taiga
ManifestType: installer
ManifestVersion: 1.12.0
