# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: turutupa.yames
PackageVersion: 0.5.2
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/turutupa/yames/releases/download/v0.5.2/Yames_0.5.2_x64-setup.exe
  InstallerSha256: F0919F36D3F621447AF102D368D5A07CD9C4F1F25040730B27243AF8F4E5004D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-07
