# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RedEyeNetworks.LogivoreForVeeam
PackageVersion: 0.12.3
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  Custom: /NORESTART
UpgradeBehavior: install
Commands:
- logivoreforveeam
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.redeyenetworks.com/logivore-for-veeam/releases/0.12.3/logivore-for-veeam-win-x64-setup.exe
  InstallerSha256: 2929A63EA38653E53C619E1BBFBE4807E5568937304B2CD7012B55E0A2F568A4
- Architecture: x64
  Scope: machine
  ElevationRequirement: elevatesSelf
  InstallerUrl: https://download.redeyenetworks.com/logivore-for-veeam/releases/0.12.3/logivore-for-veeam-win-x64-machine-setup.exe
  InstallerSha256: 50DF9D43C1C9AC8BB973C3D71E6348B8AD5F45076B27AFC67511912A8F991738
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.redeyenetworks.com/logivore-for-veeam/releases/0.12.3/logivore-for-veeam-win-arm64-setup.exe
  InstallerSha256: F91F3080041593E85330D07371065D295F38CB4824A45D06756892CA702EA435
- Architecture: arm64
  Scope: machine
  ElevationRequirement: elevatesSelf
  InstallerUrl: https://download.redeyenetworks.com/logivore-for-veeam/releases/0.12.3/logivore-for-veeam-win-arm64-machine-setup.exe
  InstallerSha256: 0EC969DD884280D1036E6195C8A54E03667B686EA2AF71FEBCC87C21AA83C5B9
ManifestType: installer
ManifestVersion: 1.12.0
