# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Parslee.Car
PackageVersion: 0.24.1
InstallerType: zip
NestedInstallerType: portable
Commands:
  - car
  - car-server
  - car-memgine-eval
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Parslee-ai/car-releases/releases/download/v0.24.1/car-win32-x64-msvc.zip
    InstallerSha256: 2C58296388C0B4C9D0E61E7772DFEB3F152271DB40A02F90ED95F36F01A201B4
    NestedInstallerFiles:
      - RelativeFilePath: car.exe
        PortableCommandAlias: car
      - RelativeFilePath: car-server.exe
        PortableCommandAlias: car-server
      - RelativeFilePath: car-memgine-eval.exe
        PortableCommandAlias: car-memgine-eval
ReleaseDate: 2026-06-14
ManifestType: installer
ManifestVersion: 1.6.0
