# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hellowind777.hellogrok.CLI
PackageVersion: 0.1.21
InstallerType: portable
Commands:
- hellogrok
ReleaseDate: 2026-09-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hellowind777/hellogrok/releases/download/v0.1.21/hellogrok-cli-windows-amd64.exe
  InstallerSha256: EFA935A605F51435CF5848C8741A1FDAF38A8FB791B206A48A1C1C59CA171F92
- Architecture: arm64
  InstallerUrl: https://github.com/hellowind777/hellogrok/releases/download/v0.1.21/hellogrok-cli-windows-arm64.exe
  InstallerSha256: 93EE020593EFF45B384A4383B859B586196436B0C862592C01EC664D679A5242
ManifestType: installer
ManifestVersion: 1.12.0
