# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lovasoa.dezoomify-rs
PackageVersion: 2.17.0
InstallerType: portable
UpgradeBehavior: install
Commands:
- dezoomify-rs
ReleaseDate: 2026-06-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lovasoa/dezoomify-rs/releases/download/v2.17.0/dezoomify-rs.exe
  InstallerSha256: 664B005F838BBA5B46AC1473778FF9F175F91BC077976557222AED3A582E8EE9
ManifestType: installer
ManifestVersion: 1.12.0
