# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: GPSoftware.DirectoryOpus
PackageVersion: "13.24"
PackageLocale: zh-TW
License: 專有軟件
ShortDescription: 文件資源管理器的完全替代品，其功能和強大程度遠超目前市面上的任何其它文件資源管理器。
Tags:
- blake3
- ftp客戶端
- md5
- sha1
- zip檔案
- ㄧㄚㄙㄨㄛㄅㄠ
- ㄨㄣˊㄐㄧㄢˋㄗㄩㄢˊㄍㄨㄢˇㄌㄧˇㄑㄧˋ
- 去重
- 哈希
- 壓縮包
- 文件夾
- 文件管理器
- 文件資源管理器
- 目錄
- 管理器
- 重命名
Documentations:
- DocumentLabel: 文檔
  DocumentUrl: https://docs.dopus.com/
ManifestType: locale
ManifestVersion: 1.12.0
