# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GlassWire.GlassWire
PackageVersion: 3.8.1061
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\GlassWire'
Installers:
- Architecture: x86
  InstallerUrl: https://s3.us-east-1.amazonaws.com/s3.glasswire.com/download/GlassWireSetup.exe
  InstallerSha256: F68B016A9D72AC1D34164FF753803D146EE0A770C94A0E47718A7FB34A4082C2
ManifestType: installer
ManifestVersion: 1.12.0
