# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Omnissa.WorkspaceONE.DEEM
PackageVersion: 25.9.0.6655
InstallerType: exe
Scope: machine
InstallModes:
- silent
InstallerSwitches:
  Silent: /s /v/qn
Installers:
- Architecture: x64
  InstallerUrl: https://packages.omnissa.com/winapps/WS1/DEEM/Omnissa-Telemetry-Agent-x86_64-25.9.0-6655.exe
  InstallerSha256: B746D382DE91F3145C883813FBC63DE513745D97DC51A43D8107697795CA036B
  AppsAndFeaturesEntries:
  - DisplayName: Omnissa Workspace ONE Experience Management
    Publisher: Omnissa
    DisplayVersion: 25.9.0.6655
    ProductCode: '{A98FC312-15F8-4683-995B-93E1B75ED8EE}'
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.10.0
