# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SST.opencode
PackageVersion: 1.18.13
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: opencode.exe
Commands:
- opencode
ReleaseDate: 2026-08-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.18.13/opencode-windows-x64.zip
  InstallerSha256: 4CC2BD079255DB237DEF148AA0771D5117E0791B96DA2B281891A45A2A7D15E2
- Architecture: arm64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.18.13/opencode-windows-arm64.zip
  InstallerSha256: F3770C4D52A608827377EED103B9F5E026783CDD7512E01E5C5457B8FA5FAA86
ManifestType: installer
ManifestVersion: 1.12.0
