# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 148.1.92.56
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser-Nightly
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: B35041C9AD03DB6EE6CD613D64EC324341219899B42E8CC5D33122848592D270
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 10AB07399D14654A3877D2195835DD0453F4558EFFE0B3821CDAC41C61B7B831
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 71291B608E59F08DB6577C732B4557C6258123B3F8B6EF8768E837BB9118A36F
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: B86438A17DB45600ABFD9BCBE9BA7F883E2ED85999DB9400689C3294F03B3A0F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: EFDFD6F3B0EA5A6848816F6A67D7F7F09A2BC22425B98FCC00A2DFC4B6DCCB94
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.92.56/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: F2C4AF11F27165D0370B4399703738F5E62F56471089BC403DBB40B461D3E174
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
