# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.cak
PackageVersion: "153.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-07-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0/win32/cak/Thunderbird%20Setup%20153.0.exe
  InstallerSha256: BB6E505C281FECBB6AF2A846D404912063EE2685B7957FBC973487517217759E
  ProductCode: Mozilla Thunderbird 153.0 (x86 cak)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.0/win64/cak/Thunderbird%20Setup%20153.0.exe
  InstallerSha256: 8326370A11C018AB57278391057C35FBF68E58E440BC42B2EF16353046E5D5EE
  ProductCode: Mozilla Thunderbird 153.0 (x64 cak)
ManifestType: installer
ManifestVersion: 1.12.0
