# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WXRIW.Lyricify
PackageVersion: 4.3.51
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /exenoui /quiet /norestart
  SilentWithProgress: /exenoui /passive /norestart
  InstallLocation: APPDIR="<INSTALLPATH>"
  Log: /log "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 87
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1
  ReturnResponse: invalidParameter
- InstallerReturnCode: -1
  ReturnResponse: cancelledByUser
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
ReleaseDate: 2026-07-01
AppsAndFeaturesEntries:
- UpgradeCode: '{CA8FC4DE-6BEC-4C25-BD21-AD316980A6EF}'
  InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.3.51/Lyricify.Setup.Ver.4.3.51.260701-release.x86.exe
  InstallerSha256: 4C773BCC52CC302FF750932FC3E6F6729E9C387993E0D655022569CB957B34F5
  ProductCode: '{88869056-5665-4B96-87A3-2C014125E7AB}'
- Architecture: x64
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.3.51/Lyricify.Setup.Ver.4.3.51.260701-release.x64.exe
  InstallerSha256: 31FA910D58845236B74D72E2B44C65886251AC2FD408F5D2F9D86BDC7E91C5E8
  ProductCode: '{1EC598ED-9A3A-43B0-A1E2-A006ED56649F}'
- Architecture: arm64
  InstallerUrl: https://github.com/WXRIW/Lyricify-App/releases/download/v4.3.51/Lyricify.Setup.Ver.4.3.51.260701-release.Arm64.exe
  InstallerSha256: 93A8E8BA048237A7AC73819A898FBA2FBEBF4471B8C2732F3BB14E75796C9247
  ProductCode: '{F48A7CA6-A06C-4FED-948A-1C032F12F13E}'
ManifestType: installer
ManifestVersion: 1.12.0
