# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: WXRIW.Lyricify
PackageVersion: 4.3.51
PackageLocale: zh-CN
License: 免费软件
Copyright: 版权所有 © 2026 WXRIW
ShortDescription: 一款为 Spotify 等各种应用提供滚动歌词的软件
Tags:
- spotify
- 歌词
- 音乐
ReleaseNotes: |-
  1. 优化 Apple Music 歌词性能，最高可提升至 2 倍。
  2. 全新设置页，更多页面支持移动模式并优化页面性能。
  3. 非商店版本添加 Microsoft Store 许可证检测。
  4. 任务栏歌词支持多显示器。
  5. 修复任务栏歌词托盘图标区域识别问题。
  6. Apple Music 歌词添加曲目信息跑马灯和高级混合模式。
  7. 修复 Apple Music 歌词背景人声飞出动画的拖动效果及多行高亮时呼吸点的问题。
  8. 调整 Apple Music 歌词纵向布局条件并修复封面裁切问题。
  9. 调整 Isolation 调色板算法。
  10. 添加“更新内容”弹窗。
  11. 添加灵动词岛和桌面歌词支持全屏时自动隐藏。
  12. 添加桌面歌词添加禁用强制置顶选项。
  13. 任务栏歌词添加轮询频率选项。
  14. 添加由 pascal-00 提供的意大利语支持。
ManifestType: locale
ManifestVersion: 1.12.0
