# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: invcble.NoMoreBorder
PackageVersion: 1.3.7
PackageLocale: en-US
Publisher: invcble
PublisherUrl: https://github.com/invcble
PackageName: NoMoreBorder
PackageUrl: https://github.com/invcble/NoMoreBorder
License: MIT License
LicenseUrl: https://github.com/invcble/NoMoreBorder/blob/main/LICENSE
ShortDescription: GUI Python app for Borderless behaviour
Description: |-
  NoMoreBorder is a utility designed to enhance your multitasking experience by enabling any windowed application to run in a fullscreen borderless mode without changing the screen resolution.
  This software is perfect for certain scenarios where applications don't have a dedicated full-screen borderless mode and running it fullscreen would mess up with dual screen behaviours.
Moniker: nomoreborder
Tags:
- nomoreborder
- borderless-gaming
ReleaseNotes: Updated the Exe lookup logic which stores both app name and path in config now. Please delete your old config and re-setup to use the new functionality.
ReleaseNotesUrl: https://github.com/invcble/NoMoreBorder/releases/tag/v1.3.7
ManifestType: defaultLocale
ManifestVersion: 1.12.0
