# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Aircall.AircallWorkspace
PackageVersion: 1.15.12
UpgradeBehavior: install
Protocols:
- aircall
- callto
- tel
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download-electron.aircall.io/aircall-workspace/Aircall-Workspace-1.15.12-x64.exe
  InstallerSha256: A74CC304E6A40C7CF74F36F39C5EBCA8F40C14C40FEC885784CA4E3D64DF3CC8
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: Aircall-Workspace
  AppsAndFeaturesEntries:
  - DisplayName: Aircall-Workspace
    DisplayVersion: 1.15.12
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://download-electron.aircall.io/aircall-workspace/Aircall-Workspace-1.15.12-x64.msi
  InstallerSha256: 93C6304250F539CA4C6CCA2C77632E029A9298DE53AA72D6EC6E387C3B4C3209
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{6A4D3DCF-AEFC-445E-AA93-7F202D5D3EEF}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 1.15.12.55901
    ProductCode: '{6A4D3DCF-AEFC-445E-AA93-7F202D5D3EEF}'
    UpgradeCode: '{4267F4EE-71BB-5FAA-9A6A-70660A24E665}'
ManifestType: installer
ManifestVersion: 1.12.0
