# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: TravisLane.SteamArtManager
PackageVersion: 3.18.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Valve.Steam
ProductCode: "{29FA2C08-4C14-402E-8EB3-503D1494264A}"
ReleaseDate: 2026-09-09
AppsAndFeaturesEntries:
- ProductCode: "{29FA2C08-4C14-402E-8EB3-503D1494264A}"
  UpgradeCode: "{728C60C1-38C9-5878-A895-495AD8F0727F}"
InstallationMetadata:
  DefaultInstallLocation: "%ProgramFiles%\\Steam Art Manager"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v3.18.0/steam-art-manager.msi
  InstallerSha256: 7E4993199EE920A3AEE2DCA9108287F14A920F3C2608F0778AB72BB5AC0127E7
ManifestType: installer
ManifestVersion: 1.12.0
