# Automatically updated by the winget bot at 2026/Jun/29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BoxlightCorporation.LYNXWhiteboard
PackageVersion: 8.7.4.0
InstallerLocale: en-US
InstallerType: wix
ReleaseDate: 2025-09-04
Scope: machine
ElevationRequirement: elevatesSelf
ProductCode: "{9D968917-02C0-46C3-B9E3-CDDDA50FB651}"
AppsAndFeaturesEntries:
- DisplayName: LYNX Whiteboard
  Publisher: Boxlight Corporation
  ProductCode: "{9D968917-02C0-46C3-B9E3-CDDDA50FB651}"
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.lynxcloud.app/lynx-whiteboard/releases/win64/lynx-whiteboard.msi
  InstallerSha256: 6448E19C2C330406D363FCA18582D02447D3E5389D580357ACA0BC8A4A30E98F
ManifestType: installer
ManifestVersion: 1.12.0
