# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Netbird.Netbird
PackageVersion: 0.66.1
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-03-03
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.66.1/netbird_installer_0.66.1_windows_amd64.msi
  InstallerSha256: 3D52140CC38917A5B41AE52C98B760A5F2B5613A6DE428B6DAA1E05C55FAF3E7
  ProductCode: '{FC6B7AE4-478C-4929-BD4E-40297FA2F37C}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.66.1
    ProductCode: '{FC6B7AE4-478C-4929-BD4E-40297FA2F37C}'
    UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.66.1/netbird_installer_0.66.1_windows_amd64.exe
  InstallerSha256: 5EE484DE4692A855A12C2232F1A11EFBCD3ADB47FC1F6CE8C4F5C9375FA666DC
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - Publisher: Netbird
    DisplayVersion: 0.66.1.22627318967
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.66.1/netbird_installer_0.66.1_windows_arm64.msi
  InstallerSha256: FD23E11C83D0B475A0CAAFF700A0C7A17EF7AAECB7B0C93083B86A4CA2297B44
  ProductCode: '{FB78C180-3CA9-4B59-9ECC-10CBD051B191}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.66.1
    ProductCode: '{FB78C180-3CA9-4B59-9ECC-10CBD051B191}'
    UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.66.1/netbird_installer_0.66.1_windows_arm64.exe
  InstallerSha256: BA7918AC6F072ABAA1F72536C309B49D5029D9FBB51558D695F7F534CCEB63AC
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - Publisher: Netbird
    DisplayVersion: 0.66.1.22627318967
ManifestType: installer
ManifestVersion: 1.12.0
