# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.Utilities
PackageVersion: 3.0.8.9
ReleaseDate: 2026-08-05
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx86
  InstallerSha256: 9A45FEEAA7CC898E1C0BB58A9D9582717B177FC301BFAD6EBFCD8ACDF81B8572
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx64
  InstallerSha256: 2976D87FC7AEC94EB9B3582B1B103B55241F0BC736C71C8999FA58C331A2C349
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesarm64
  InstallerSha256: 8CF430A84C1F4A911B0FFD913A3942408519BBA6B21C5E84DF0EC5E79C67C578
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.X86\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx86portable
  InstallerSha256: DE5E2584ABD1ED5F14D7D27A9C4FD71465396EED4691515A918850AA75807000
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.X64\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx64portable
  InstallerSha256: 1C261C86B716F2B5968CD6D99FD19DD413B11F1F3EEDE3D968FE09B4E14A935A
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.Arm64\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesarm64portable
  InstallerSha256: E962FCDFC97EA84949A341A77FED84624701DFFD63B0B0246964B192E211A37C
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
