# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tableau.PrepBuilder
PackageVersion: 26.2.45750
InstallerType: burn
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Custom: ACCEPTEULA=1 SKIPAPPLICATIONLAUNCH=1
UpgradeBehavior: uninstallPrevious
FileExtensions:
- tfl
- tflx
ProductCode: '{7a5c6e7d-6287-4ca5-a12d-adce12f81679}'
ReleaseDate: 2026-07-20
AppsAndFeaturesEntries:
- ProductCode: '{7a5c6e7d-6287-4ca5-a12d-adce12f81679}'
  UpgradeCode: '{B621B786-2567-483E-A509-D4138AABF9B5}'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.tableau.com/esdalt/tableau_prep/2026.2.1/TableauPrep-2026-2-1.exe
  InstallerSha256: 0665A631D98A5F99A0D7AD66C975CADAAD4796054B46D25FEDC21353DEEC9E1A
ManifestType: installer
ManifestVersion: 1.12.0
