# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: surge-downloader.surge
PackageVersion: 0.7.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: surge.exe
  PortableCommandAlias: surge
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
Commands:
- surge
ReleaseDate: 2026-04-02
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/surge-downloader/Surge/releases/download/v0.7.6/Surge_0.7.6_windows_386.zip
  InstallerSha256: 1C183ED898A6BB3A6C600AC075D115404817DE37EF59E839590378FBE61B0355
- Architecture: x64
  InstallerUrl: https://github.com/surge-downloader/Surge/releases/download/v0.7.6/Surge_0.7.6_windows_amd64.zip
  InstallerSha256: 3CC7CCE370316A12288EDF7894BC56FCB5B82B7B3669736C0A840512EF0AE1C0
- Architecture: arm64
  InstallerUrl: https://github.com/surge-downloader/Surge/releases/download/v0.7.6/Surge_0.7.6_windows_arm64.zip
  InstallerSha256: 9205A60F076082A4055BD1EA1BF8B8C4861A85E35FC682A5DE156FC6AABC4823
ManifestType: installer
ManifestVersion: 1.12.0
