# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Dev.EXE
PackageVersion: 149.0.7815.2
InstallerType: exe
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome Dev
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://dl.google.com/release2/chrome/dqqoya7kjbejhjav6gmblwnwgi_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: 24E4BD96AE6E73D057AFEA31193393AEC07357A0FB64FC40DC086D21AD69DB1B
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome
- Architecture: x86
  Scope: machine
  InstallerUrl: https://dl.google.com/release2/chrome/dqqoya7kjbejhjav6gmblwnwgi_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: 24E4BD96AE6E73D057AFEA31193393AEC07357A0FB64FC40DC086D21AD69DB1B
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome --system-level
- Architecture: x64
  Scope: user
  InstallerUrl: https://dl.google.com/release2/chrome/adqgkrfyjtaj46s5temudn6lwsia_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: 7663BB6D622C0CE38F755E98E6B65F267DB7FEBA5C62EC87596DF200DB43A78B
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome
- Architecture: x64
  Scope: machine
  InstallerUrl: https://dl.google.com/release2/chrome/adqgkrfyjtaj46s5temudn6lwsia_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: 7663BB6D622C0CE38F755E98E6B65F267DB7FEBA5C62EC87596DF200DB43A78B
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome --system-level
- Architecture: arm64
  Scope: user
  InstallerUrl: https://dl.google.com/release2/chrome/acxq7obuqxeihl246dnqc7v3stqq_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: D87B5B781F8B738D0E6A29299926FAB3D591C52E0DAA7C05A8C722551E46FB88
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://dl.google.com/release2/chrome/acxq7obuqxeihl246dnqc7v3stqq_149.0.7815.2/149.0.7815.2_chrome_installer_uncompressed.exe
  InstallerSha256: D87B5B781F8B738D0E6A29299926FAB3D591C52E0DAA7C05A8C722551E46FB88
  InstallerSwitches:
    Custom: --chrome-dev --do-not-launch-chrome --system-level
ManifestType: installer
ManifestVersion: 1.12.0
