# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GLab.GLab
PackageVersion: 1.106.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{679C50AE-F48A-46D1-9493-77F095E9884D}_is1'
ReleaseDate: 2026-06-30
AppsAndFeaturesEntries:
- DisplayName: glab v1.106.0
  ProductCode: '{679C50AE-F48A-46D1-9493-77F095E9884D}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://gitlab.com/gitlab-org/cli/-/releases/v1.106.0/downloads/glab_1.106.0_Windows_x86_64_installer.exe
  InstallerSha256: 52B9E05BCBA4597A9791342016BDE83426C2F56E850A2693F759026973FF16EB
  InstallerSwitches:
    Custom: /CURRENTUSER
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\glab'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://gitlab.com/gitlab-org/cli/-/releases/v1.106.0/downloads/glab_1.106.0_Windows_x86_64_installer.exe
  InstallerSha256: 52B9E05BCBA4597A9791342016BDE83426C2F56E850A2693F759026973FF16EB
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\glab'
ManifestType: installer
ManifestVersion: 1.12.0
