# Automatically updated by the winget bot at 2026/Jun/24
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Axialis.IconVectors
PackageVersion: '1.70.0.0'
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /q
  InstallLocation: /f "<INSTALLPATH>"
UpgradeBehavior: install
FileExtensions:
- SVG
ReleaseDate: 2025-09-17
Installers:
- Architecture: x86
  InstallerUrl: https://www.axialis.com/downloads/IconVectors-Pro-32-bit.exe
  InstallerSha256: DDD9E52D3A441FC455D808222C2497C26C0EF4B0A8DB86E15428FD822C16C204
  ProductCode: 'IconVectors'
- Architecture: x64
  InstallerUrl: https://www.axialis.com/downloads/IconVectors-Pro.exe
  InstallerSha256: ACDF6CFABEF771EA507207293F031DF71CF369470D3BEB22C48D0E3ECA994A7C
  ProductCode: 'IconVectors (64-bit)'
ManifestType: installer
ManifestVersion: 1.12.0
