# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.VCFEditor
PackageVersion: 3.1.0.0
InstallerLocale: en-US
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/vcf-editor.exe
  InstallerSha256: D5C2CCFD415E4B1501542C654866746CEB5494E32DFA80FC7226B1FEA4BBF2A2
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  FileExtensions:
  - VCF
  ProductCode: VCF Editor_is1
  AppsAndFeaturesEntries:
  - DisplayName: VCF Editor
    ProductCode: VCF Editor_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\VCF Editor'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: vcfeditor.exe
    PortableCommandAlias: vcfeditor
  InstallerUrl: https://files.vovsoft.com/vcf-editor-portable.zip
  InstallerSha256: C30DA906C26EDFB0424A0393401A77BDF89D0241FAE63BAFC8F54139BFF35C41
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-06
