# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mehuge.MultiPing
PackageVersion: 1.0.0-beta.1
InstallerType: portable
Commands:
- MultiPing
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Mehuge/MultiPing/releases/download/v1.0.0-beta.1/MultiPing.exe
  InstallerSha256: 65824A913F7D4212E0E58F9D198A170892696E55972F6E6ED02F01E16F39A9D4
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-18
