# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixDesktop
PackageVersion: 1.17.8
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Reasonix
ReleaseDate: 2026-07-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/desktop-v1.17.8/Reasonix-windows-amd64-installer.exe
  InstallerSha256: 60CC540535DD8370D7ECD9F81BCE1097FC3984916AF6B87D914F515A798DDACD
ManifestType: installer
ManifestVersion: 1.12.0
