# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.sco
PackageVersion: 140.13.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2026-07-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win32/sco/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 140D913FB7D2DA7982BD70C369FC3B3A2C46C1605E683BC0DFE10D8F93BB54F6
  ProductCode: Mozilla Firefox 140.13.0 ESR (x86 sco)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win64/sco/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 9FC3C5E8CEC7C0A0694CE694E9EB9920FF9AE4346039474845D5A493556A93E5
  ProductCode: Mozilla Firefox 140.13.0 ESR (x64 sco)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win64-aarch64/sco/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 4B45C5759C16B0CD68D4BD557E7EE76EF51260C44B98E99D009888D27DF45A73
  ProductCode: Mozilla Firefox 140.13.0 ESR (arm64 sco)
ManifestType: installer
ManifestVersion: 1.12.0
