# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Cloudflare.cloudflared
PackageVersion: 2026.5.1
ReleaseDate: 2026-05-25
Installers:
- Architecture: x86
  InstallerType: portable
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/download/2026.5.1/cloudflared-windows-386.exe
  InstallerSha256: FEE35ED451CF3C405A5736447A3F2CCE7482B3CA1F6F0F1B1E3C2AE7B18D3D06
  Commands:
  - cloudflared
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/download/2026.5.1/cloudflared-windows-amd64.exe
  InstallerSha256: 8B97B5AF442651E07C52CAA9C79C6F60032BC10B675C2B36DD11C7690D9942E3
  Commands:
  - cloudflared
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/download/2026.5.1/cloudflared-windows-386.msi
  InstallerSha256: B4BCCCC19A92168A45282C3FB76DE5ADC8B1632C97C0FBF380F69504A24017A2
  ProductCode: '{36666E08-1BDA-4986-A3DB-0D44B785A479}'
  AppsAndFeaturesEntries:
  - ProductCode: '{36666E08-1BDA-4986-A3DB-0D44B785A479}'
    UpgradeCode: '{23f90fdd-9328-47ea-ab52-5380855a4b12}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/cloudflared'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/download/2026.5.1/cloudflared-windows-amd64.msi
  InstallerSha256: 506124ECC4140973304F7AA41070E9D1258A5D26125331BB6D16DCEAB4FA5B4E
  ProductCode: '{2CDA78AE-C040-41AE-A2D2-EEDC158777AD}'
  AppsAndFeaturesEntries:
  - ProductCode: '{2CDA78AE-C040-41AE-A2D2-EEDC158777AD}'
    UpgradeCode: '{23f90fdd-9328-47ea-ab52-5380855a4b12}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/cloudflared'
ManifestType: installer
ManifestVersion: 1.12.0
