# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: amiasea.tfcred
PackageVersion: 1.4.15
PackageLocale: en-US
Publisher: amiasea
PublisherUrl: https://github.com/amiasea/terraform-credentials-tfcred
PackageName: tfcred
PackageUrl: https://github.com/amiasea/terraform-credentials-tfcred
License: MIT
ShortDescription: Terraform credential context manager
ManifestType: defaultLocale
ManifestVersion: 1.12.0
