# Created for GestureSign V2 18.0.8
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Tomclanc.GestureSignV2
PackageVersion: 18.0.8
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{E7391C65-9E38-4808-95DE-17E6798762DD}'
AppsAndFeaturesEntries:
- DisplayName: GestureSign V2
  Publisher: TransposonY / WinUI rebuild
  ProductCode: '{E7391C65-9E38-4808-95DE-17E6798762DD}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Tomclanc/GestureSignv2/releases/download/v18.0.8/GestureSign-V2-18.0.8-x64.msi
  InstallerSha256: 45325ABDF70AC51F904626B8C67947E9B0FFBAE08487672469F3479621CCB2D1
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-25
