# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JohannesMillan.superProductivity
PackageVersion: 18.15.1
InstallerLocale: en-US
InstallerType: nullsoft
ProductCode: 50dcac04-ae56-5b20-97aa-2c97dcd03d4b
ReleaseDate: 2026-07-17
AppsAndFeaturesEntries:
- DisplayName: Super Productivity 18.2.8
  ProductCode: 50dcac04-ae56-5b20-97aa-2c97dcd03d4b
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/johannesjo/super-productivity/releases/download/v18.15.1/Super-Productivity-Setup.exe
  InstallerSha256: BC775C47925E75B4A58E8F2DA086F1994D04123713AFCDCEF0207F5A193C5DB2
- Architecture: x64
  InstallerUrl: https://github.com/johannesjo/super-productivity/releases/download/v18.15.1/Super-Productivity-Setup-x64.exe
  InstallerSha256: A0A813CF1FB693C828DDAAF4C48B64B4EFE5C7E768307A42319414E57054968B
- Architecture: arm64
  InstallerUrl: https://github.com/johannesjo/super-productivity/releases/download/v18.15.1/Super-Productivity-Setup-arm64.exe
  InstallerSha256: 4330CD28383ACD80AF23BA334E6CEA9BC4054363E1E805DBB885A46F4FC0A401
ManifestType: installer
ManifestVersion: 1.12.0
