# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PowCal.PowCal
PackageVersion: 1.7.0
PackageLocale: en-US
Publisher: PowCal
PublisherUrl: https://powcal.com
PublisherSupportUrl: https://github.com/thomasbachem/powcal-releases/issues
PackageName: PowCal
PackageUrl: https://powcal.com
License: Proprietary
ShortDescription: A powerful app to customize & extend Google Calendar.
Moniker: powcal
Tags:
- calendar
- google-calendar
- productivity
ReleaseNotesUrl: https://github.com/thomasbachem/powcal-releases/releases/tag/v1.7.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
