# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: zerx-lab.FluxDown
PackageVersion: 0.4.7
PackageLocale: en-US
Publisher: FluxDown
PublisherUrl: https://github.com/zerx-lab
PublisherSupportUrl: https://github.com/zerx-lab/FluxDown/issues
Author: zerx-lab
PackageName: FluxDown
PackageUrl: https://github.com/zerx-lab/FluxDown
License: AGPL-3.0
LicenseUrl: https://github.com/zerx-lab/FluxDown/blob/HEAD/LICENSE
ShortDescription: Rust 驱动的多协议下载管理器，支持 HTTP/FTP/BitTorrent 磁力链接及 HLS/DASH 流媒体，智能多线程加速与浏览器无缝集成。精美界面，极致性能，永久免费，零广告。
ReleaseNotes: |-
  [0.4.7] - 2026-08-16
  🐛 Bug Fixes
  - (installer) Windows 包随附 MSVC CRT 运行库
  - (nmh) 裸运行与 --help/--version 立即退出
  - (cloud) 保留下架套餐的展示快照
ReleaseNotesUrl: https://github.com/zerx-lab/FluxDown/releases/tag/v0.4.7
ManifestType: defaultLocale
ManifestVersion: 1.12.0
