# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CaptainKillSwitch.CaptainKillSwitch
PackageVersion: 0.4.8
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{35A04619-2D12-4DB5-9ACF-BF34655C8A3B}'
ReleaseDate: 2026-09-20
AppsAndFeaturesEntries:
- Publisher: Captain Kill Switch Team
  ProductCode: '{35A04619-2D12-4DB5-9ACF-BF34655C8A3B}'
  UpgradeCode: '{984FC5FB-4BE0-5465-85FF-3FDCFED283B5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Captain Kill Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/captainkillswitch/downloads/releases/download/v0.4.8/captain-kill-switch-0.4.8-windows-x64.msi
  InstallerSha256: 925BAF5D2F365B5D2563CE81507D52A526B354517637FF266EDD432520F11272
ManifestType: installer
ManifestVersion: 1.12.0
