# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zoho.Meeting
PackageVersion: 5.0.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- zohomeetinglauncher
ProductCode: 073f5d58-255d-5942-bb74-82b8af86d982
ReleaseDate: 2026-09-07
Installers:
- Architecture: x86
  InstallerUrl: https://d1ctjwn89mb7yf.cloudfront.net/agent/5.0.0/ZohoMeetingInstaller.exe
  InstallerSha256: 2AF24E3DEF0F37A8620D49DB25418BDBB3BD4A16A8CEFE370916549A0E4C9FF8
ManifestType: installer
ManifestVersion: 1.12.0
