# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: raphamorim.rio
PackageVersion: 0.3.3
PackageLocale: en-US
Publisher: Raphael Amorim
PublisherUrl: https://github.com/raphamorim/rio
PublisherSupportUrl: https://github.com/raphamorim/rio/issues
Author: Raphael Amorim
PackageName: Rio
PackageUrl: https://github.com/raphamorim/rio
License: MIT
LicenseUrl: https://github.com/raphamorim/rio/blob/HEAD/LICENSE
Copyright: Copyright (c) 2022-present Raphael Amorim
CopyrightUrl: https://raw.githubusercontent.com/raphamorim/rio/main/LICENSE
ShortDescription: Rio terminal is a hardware-accelerated GPU terminal emulator, focusing to run in desktops and browsers.
Description: |-
  Rio terminal is a hardware-accelerated GPU terminal emulator, focusing to run in desktops and browsers.
  The supported platforms currently consist of BSD, Linux, MacOS and Windows.
Moniker: rio
Tags:
- cross-platform
- terminal
- terminal-emulators
ReleaseNotes: |-
  Changelog
  - 9f2342c prepare 0.3.3
  - 3820375 update changelog
  - 4645f61 change fontcache way
  - b0bf16f update render to fix sixel
  - aa950dd wip kitty
  - 98a2235 resize grow fix
  - 33198ef some fixes for kitty rendering
  - f6061ba update docs
  - 7320234 fix docs build
  - 23b57fb cpu fix for non macos
  - 1ac33de small update for build on windows
  - 9e989c0 fix lint
  - 7ea41f4 disabled by default
  - 97ad0e2 add on docs
  - 6d16f33 few opportunities
  - e0ce302 update changelog.dmx
  - 2ef473e update rendering
  - 835d0ef add cpu rendering option
  - 646bb07 add copy on select config to docs
ReleaseNotesUrl: https://github.com/raphamorim/rio/releases/tag/v0.3.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
