# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ant-lib.Hingewave
PackageVersion: 0.2.3
InstallerType: portable
Commands:
- hingewave
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-09-16
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ant-lib/hingewave/releases/download/v0.2.3/hingewave-x64.exe
  InstallerSha256: F7E369442E9CC314DF458CBC3E76B7A86BBE54ABADEBC44EC08BAEE37CD9D1B1
- Architecture: arm64
  InstallerUrl: https://github.com/Ant-lib/hingewave/releases/download/v0.2.3/hingewave-arm64.exe
  InstallerSha256: AC8D01764E2E56D624E6BD273028E7898E8BDAAE667A38C0DE3F77047EBDB3BE
ManifestType: installer
ManifestVersion: 1.12.0