# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.475
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-09-03
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.475/fabric_Windows_i386.zip
  InstallerSha256: EEF96183F9046FC0605A9607F6A1F5B6824499D4A8BB6A513229AFA3D27A6608
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.475/fabric_Windows_x86_64.zip
  InstallerSha256: 37F5CBEAB1C932210D8B89307A3D93B29328DF5F0292100ECE3D9E69E866BE0B
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.475/fabric_Windows_arm64.zip
  InstallerSha256: 7CBE3636403D3040FED3086A79636A2E7981E335F45B70987BB3CD5FB556BDD2
ManifestType: installer
ManifestVersion: 1.12.0
