# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Rustlang.Rust.GNU
PackageVersion: 1.97.0
InstallerType: wix
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-07-09
Installers:
- Architecture: x86
  InstallerUrl: https://static.rust-lang.org/dist/rust-1.97.0-i686-pc-windows-gnu.msi
  InstallerSha256: B79EA41B267C72C05F1C34C70C677497A7ACA9CA8FC57A73FC31374B259A5F68
  ProductCode: '{988D6E01-B173-4AA2-8E99-8BAAAC9CA23C}'
  AppsAndFeaturesEntries:
  - DisplayName: Rust 1.97 (GNU)
    ProductCode: '{988D6E01-B173-4AA2-8E99-8BAAAC9CA23C}'
    UpgradeCode: '{1C7CADA5-D117-43F8-A356-DF15F9FBEFF6}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Rust'
- Architecture: x64
  InstallerUrl: https://static.rust-lang.org/dist/rust-1.97.0-x86_64-pc-windows-gnu.msi
  InstallerSha256: 04A32B4EC12B403A3B6F6F2708973B9342354024B39A1011DF54B1CE843B23D8
  ProductCode: '{D4ED7A72-FCB4-4697-9BEE-4ECF0691E60D}'
  AppsAndFeaturesEntries:
  - DisplayName: Rust 1.97 (GNU 64-bit)
    ProductCode: '{D4ED7A72-FCB4-4697-9BEE-4ECF0691E60D}'
    UpgradeCode: '{B440B077-F8D1-4730-8E1D-D6D37702B4CE}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Rust'
ManifestType: installer
ManifestVersion: 1.12.0
