# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Fluxzy.Fluxzy
PackageVersion: 1.39.48.18975
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fluxzy.exe
  PortableCommandAlias: fluxzy
- RelativeFilePath: fluxzynetcap.exe
  PortableCommandAlias: fluxzynetcap
ReleaseDate: 2026-09-09
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/haga-rak/fluxzy.core/releases/download/v1.39.48.18975/fluxzy-cli-1.39.48.18975-win-x86.zip
  InstallerSha256: 6548966D3C0230960456896790CBD1112A68BAE3B1DCC973521CB46B394EF902
ManifestType: installer
ManifestVersion: 1.10.0
