# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.457.316.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-08-24
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.316.0&arch=x86
  InstallerSha256: DA505157A20034450FF8A58155ADC3DC6415BF0A0BD91CA5DC9A75C292D1CCD0
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.316.0&arch=amd64
  InstallerSha256: FAF40C33AB34B0EC03D8BAAAA19E15932EE8E8E30368671EC10EEF279FB614A1
ManifestType: installer
ManifestVersion: 1.12.0
