# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NimbusAgent.Nimbus
PackageVersion: 1.4.0
InstallerType: wix
ProductCode: '{8FC787C9-E091-49C5-905B-A3F8515E8E38}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbus-agent/Nimbus/releases/download/v1.4.0/nimbus-headless-windows-x64.msi
  InstallerSha256: 49FC552CCD4907938851B1B379F9FC01ADF5E7BD2896893144A3E1205CBCD06E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-07-28
