# Created with Sundry-Locale
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DuckStudio.Sundry
PackageVersion: 1.8.1
UpgradeBehavior: install
Commands:
  - sundry
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Git.Git
    - PackageIdentifier: GitHub.cli
ReleaseDate: 2026-08-22 # Asia/Shanghai (UTC+8)
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: sundry.exe
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.8.1/Sundry.zip
    InstallerSha256: 38C99B607331D21054D4B98EDAC85FC1EF99D82227125239DBD44EDCB78FE9BA
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: sundry.exe
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.8.1/Sundry.zip
    InstallerSha256: 38C99B607331D21054D4B98EDAC85FC1EF99D82227125239DBD44EDCB78FE9BA
  - Architecture: x64
    InstallerType: inno
    Scope: machine
    ElevationRequirement: elevatesSelf
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\Sundry'
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.8.1/Sundry_Setup.exe
    InstallerSha256: 1E11EED8208DF8203386842C9DB18B06B99AB139A039D12D15CCA1636742BE7E
  - Architecture: arm64
    InstallerType: inno
    Scope: machine
    ElevationRequirement: elevatesSelf
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\Sundry'
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.8.1/Sundry_Setup.exe
    InstallerSha256: 1E11EED8208DF8203386842C9DB18B06B99AB139A039D12D15CCA1636742BE7E
ManifestType: installer
ManifestVersion: 1.12.0
