# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: TwintailTeam.TTL
PackageVersion: 2.2.0
PackageLocale: en-US
Publisher: TwintailTeam
PublisherUrl: https://twintaillauncher.app/
PublisherSupportUrl: https://twintaillauncher.app/
Author: TwintailTeam
PackageName: twintaillauncher
PackageUrl: https://twintaillauncher.app/
License: GPL-3.0
LicenseUrl: https://github.com/TwintailTeam/TwintailLauncher/blob/HEAD/LICENSE
Copyright: Copyright TwintailTeam & Contributors
ShortDescription: A multi-platform launcher for your anime games
Description: Twintaillauncher is a multi-platform launcher that brings mod support, quality-of-life improvements, and advanced features to a variety of anime-styled games.
Moniker: ttl
Tags:
- aether-gazer
- game
- genshin-impact
- honkai-impact
- honkai-starrail
- launcher
- linux-app
- punishing-gray-raven
- windows-app
- wutheringwaves
- zenless-zone-zero
ReleaseNotes: |-
  Changelog
  Games
  - Honkai: StarRail now again works with all protons and by all we mean all
  - Honkai: StarRail no longer crashes on cutscenes on flatpak
  - WutheringWaves should have no more cases where for some people skips cutscenes
  Modding
  - XXMI for WutheringWaves now behaves fully as expected no weird textures etc...
  Bug fixes & Improvements
  - Application now has support for making translation locales, default is English
  - New and improved Update available notification popup
  - Bazzite and Fedora atomic like distros /var/home pathing should be fixed yet again
  - Various bug fixes we did not keep track off
  What's Changed
  - Add german and nekonian translation by @MrLGamer in #252
  - Release 2.2.0 by @TukanDev in #253
  New Contributors
  - @MrLGamer made their first contribution in #252
  Full Changelog: ttl-v2.1.1...ttl-v2.2.0
ReleaseNotesUrl: https://github.com/TwintailTeam/TwintailLauncher/releases/tag/ttl-v2.2.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
