# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.nb-NO
PackageVersion: 140.10.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-04-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.10.0esr/win32/nb-NO/Thunderbird%20Setup%20140.10.0esr.exe
  InstallerSha256: A5FCA35030180ECD7DCE09418CE5655536520432BBF26064EAC914ADF733D511
  ProductCode: Mozilla Thunderbird 140.10.0 (x86 nb-NO)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 nb-NO)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.10.0esr/win64/nb-NO/Thunderbird%20Setup%20140.10.0esr.exe
  InstallerSha256: C8F0503B2D45434D17320B50A339AB9479EA6B45308B9A40A19898A45E22E8F4
  ProductCode: Mozilla Thunderbird 140.10.0 (x64 nb-NO)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 nb-NO)
ManifestType: installer
ManifestVersion: 1.12.0
