# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.Utilities
PackageVersion: 3.0.9.9
ReleaseDate: 2026-09-21
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx86
  InstallerSha256: 2123443E0B48952656DA6BBF1FE946206E06A90C9E8E97E83D88843E50CC439E
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx64
  InstallerSha256: B188C3C471E1C507D3C11303E31D4FBB73B1631A4B3E372ADF8DDDA1817EA43D
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesarm64
  InstallerSha256: 025DF342543D87060587358CDDB9415362EC83039C2286D7FDEDEA9B0860F9CE
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART --hidden
    SilentWithProgress: /SILENT /NORESTART --hidden
  UpgradeBehavior: install
  ProductCode: Argente Utilities 3.0
  ElevationRequirement: elevatesSelf
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.X86\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx86portable
  InstallerSha256: 25D2AD02FDF34FB172FFF85A8719631C94445FE703339438B3EF17FD599ED195
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.X64\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx64portable
  InstallerSha256: D56831BE980634DBAA56F2EBAFEA176D798DECC3C33985CB250E134A897AB63F
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Argente.Utilities.Arm64\Argente.Utilities.exe
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesarm64portable
  InstallerSha256: 3F8B94F67F0C2B68CCF73926EC0A6CC9A0B40E92885E564FB1D58CF95D9EA0F7
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
