# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NetEase.UURemote
PackageVersion: 4.34.0.8979
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: GameViewer
ReleaseDate: 2026-07-23
Installers:
- Architecture: x64
  InstallerUrl: https://a56.gdl.netease.com/UURemote_Setup_4.34.0.8979_0723104500_gwqd.exe
  InstallerSha256: 237EB74939A62935AE3E2B1FD43C484D634CCD96FB1094BA764C8CB64065DC9A
ManifestType: installer
ManifestVersion: 1.12.0
