# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.OpenCodeReview
PackageVersion: 1.2.4
InstallerType: portable
Commands:
- opencodereview
ReleaseDate: 2026-06-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.2.4/opencodereview-windows-amd64.exe
  InstallerSha256: 2B25AB569F1962A77653473F1518A768AB76FF08868F62DC1EB2F875435A5F35
- Architecture: arm64
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.2.4/opencodereview-windows-arm64.exe
  InstallerSha256: 6FF237814EFC8230EBE797814F7ED35CF465D32568E90B54EF9CEE7E4175B4BD
ManifestType: installer
ManifestVersion: 1.12.0
