# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 155.2607.2609.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-07-26
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/07/2026-07-26-09-24-01-mozilla-central/firefox-155.0a1.multi.win32.installer.msix
  InstallerSha256: 66F8C929ACB913EFB637A3A9E67F4949C09F0E06345723B99E0EDD2073FD5094
  SignatureSha256: DC679015D1E4FE81B9E6B02514116FF6DCC620CD01519B5AAE667E295EDAFFAA
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_155.2607.2609.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/07/2026-07-26-09-24-01-mozilla-central/firefox-155.0a1.multi.win64.installer.msix
  InstallerSha256: 823D12A0E0CA78210BC330EECF4458200D5997BF218F2D7965B41AA325AF0EB0
  SignatureSha256: 169E13D837B647FA0886150D0FAE0BAE22305729D20EBD8FCB78CD647F872B94
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_155.2607.2609.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/07/2026-07-26-09-24-01-mozilla-central/firefox-155.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: E45883AA4A56A100C8D711E2929EA4CBA6F9914E7CA4C5606BB7056259A3AD5C
  SignatureSha256: 982867CB6BEF25B98AEC9F6A93FD38EB20C5EC62E8E8CA6AD170094C81897066
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_155.2607.2609.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
