# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.Toolbox
PackageVersion: 3.4.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /headless
  SilentWithProgress: /S
UpgradeBehavior: install
Protocols:
- jetbrains
ProductCode: Toolbox
ReleaseDate: 2026-03-17
Installers:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/toolbox/jetbrains-toolbox-3.4.0.77112.exe
  InstallerSha256: 166B55D16711493946B4BCE01429BA1A12970481B362C39CBDE4B395496CE4E2
- Architecture: arm64
  InstallerUrl: https://download.jetbrains.com/toolbox/jetbrains-toolbox-3.4.0.77112-arm64.exe
  InstallerSha256: D7162B4C1EAE317221485BEF0ED9E0B7F71A90CBD9CCF57793AC5FA49700BBCD
ManifestType: installer
ManifestVersion: 1.12.0
