# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fr
PackageVersion: 150.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-04-28
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win32/fr/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: DF785AC583235A5A54B9B46376A2478AC9EC59D8C9B808D7AED37E558A2DD344
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win64/fr/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: 3D5D2FADC69E0B3B185426EEF590ACC6ADD642EC78B21BB0882E8175878DD147
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win64-aarch64/fr/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: 0FAA6228DD8DB6282314948441213096B0DA20EF5D15312F01E60EDEFF546968
ManifestType: installer
ManifestVersion: 1.12.0
