# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Stardock.Fences.5
PackageVersion: 5.9.1.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
InstallerSuccessCodes:
- 3010
- 9
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://stardock.cachefly.net/software/Fences/Fences5/Fences5_setup.exe
  InstallerSha256: F3F4CFDA630D40BBB6819A6717D8E51169429A8781337FB17BCC7CD7155337B4
ManifestType: installer
ManifestVersion: 1.12.0
