# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DifferentAI.OpenWork
PackageVersion: 0.12.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ProductCode: '{5BE6D74D-715D-4FB2-A846-DCC540D4E874}'
ReleaseDate: 2026-04-28
AppsAndFeaturesEntries:
- UpgradeCode: '{2A300FB5-FA81-5886-A03C-B8C20DF4E74B}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/different-ai/openwork/releases/download/v0.12.0/openwork-desktop-windows-x64.msi
  InstallerSha256: B87A201C75E9EC5B908C40A2499E0BB3AE5247044EB2BEE9DB9377CB090DFEFE
ManifestType: installer
ManifestVersion: 1.12.0
