# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.KDEConnect.AppX
PackageVersion: 26.402.6318.0
Platform:
- Windows.Desktop
UpgradeBehavior: install
Installers:
- MinimumOSVersion: 10.0.14316.0
  Architecture: x64
  InstallerType: appx
  InstallerUrl: https://cdn.kde.org/ci-builds/network/kdeconnect-kde/release-26.04/windows/kdeconnect-kde-release_26.04-6318-windows-cl-msvc2022-x86_64-sideload.appx
  InstallerSha256: 76BA95F08D09C66939AF2F224ED45CF51FA0712C3FF131996234F20AA71AFD43
  SignatureSha256: 178CFAE57910EDDC8FD837B41A6DCC979BAB0FFF5D4CA65C9EF3B794F74C93F4
  PackageFamilyName: KDEe.V.KDEConnect_5b9q37dtznz5e
  Capabilities:
  - globalMediaControl
  - userNotificationListener
  RestrictedCapabilities:
  - runFullTrust
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\KDEe.V.KDEConnect_26.400.6173_x64__5b9q37dtznz5e'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: kdeconnect-app.exe
  - RelativeFilePath: kdeconnect-cli.exe
  - RelativeFilePath: kdeconnect-handler.exe
  - RelativeFilePath: kdeconnect-sms.exe
  - RelativeFilePath: kioworker.exe
  - RelativeFilePath: snoretoast.exe
  InstallerUrl: https://cdn.kde.org/ci-builds/network/kdeconnect-kde/release-26.04/windows/kdeconnect-kde-release_26.04-6318-windows-cl-msvc2022-x86_64-sideload.appx?_
  InstallerSha256: 76BA95F08D09C66939AF2F224ED45CF51FA0712C3FF131996234F20AA71AFD43
  AppsAndFeaturesEntries:
  - DisplayName: KDE Connect (Portable)
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
