# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MongoDB.MongoDBAtlasCLI
PackageVersion: 1.55.0
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{9A6579B2-EF71-4115-BD85-DA46119FE921}'
Installers:
- Architecture: x64
  InstallerUrl: https://fastdl.mongodb.org/mongocli/mongodb-atlas-cli_1.55.0_windows_x86_64.msi
  InstallerSha256: 28B53B580B69CBAC5FC1D22E6E06B8E9A76047FEB3EA88B8EBC442C126B2DAFD
ManifestType: installer
ManifestVersion: 1.12.0
