# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Game1024.OpenSpeedy
PackageVersion: 3.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: openspeedy.exe
  PortableCommandAlias: openspeedy
ReleaseDate: 2026-06-21
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/game1024/OpenSpeedy/releases/download/3.1.1/OpenSpeedy-3.1.1-portable-signed.zip
  InstallerSha256: 859226B1CA44439DCB3687A784B99F7A9039F480F41DE9C4EA152A060FA45CF7
ManifestType: installer
ManifestVersion: 1.10.0
