PackageIdentifier: dixieflatline76.Spice
PackageVersion: 2.2.7
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/dixieflatline76/Spice/releases/download/v2.2.7/Spice-Setup-2.2.7-windows-amd64.exe
    InstallerSha256: FE60A2497809EB2CDD947FBD0FB9196E20062EE30A311D1FB0275F60C9C3489C
    UpgradeBehavior: install
    InstallerSwitches:
      Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
      SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.5.0
