# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.br
PackageVersion: 153.1.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-08-18
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.1.0esr/win32/br/Firefox%20Setup%20153.1.0esr.exe
  InstallerSha256: A2BB9499772F115047887C4D4CDE9C6F86E7D051778C13E188ACD6EB791DA264
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.1.0esr/win64/br/Firefox%20Setup%20153.1.0esr.exe
  InstallerSha256: 3F29CB7BD1E9755A4474250B578BFFE83EC1D5EF2BA42B639DC656D4E5DFDD80
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.1.0esr/win64-aarch64/br/Firefox%20Setup%20153.1.0esr.exe
  InstallerSha256: F5A24A07407BE1E7F5B32206D017B642333DA318908797A3AE3017FB7E589C1D
ManifestType: installer
ManifestVersion: 1.12.0
