PackageIdentifier: rulssss.CloudCostTree
PackageVersion: 0.2.10
InstallerType: portable
Commands:
  - cloudcosttree
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/rulssss/cloudcosttree/releases/download/v0.2.10/cloudcosttree-windows-amd64.exe
    InstallerSha256: B122DA7FD8819F35676C4CA19E52E6B348B08F3CC741570B8542E4136F47D237
  - Architecture: arm64
    InstallerUrl: https://github.com/rulssss/cloudcosttree/releases/download/v0.2.10/cloudcosttree-windows-arm64.exe
    InstallerSha256: 638F8B7BEA4CBFB87BCA7FED746A521060DE9B9BB4D5C25AC0954C3BC48B069C
ManifestType: installer
ManifestVersion: 1.6.0
