# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MaaAssistantArknights.maa-cli
PackageVersion: 0.7.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: maa-cli.exe
InstallModes:
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Commands:
- maa
- maa-cli
ReleaseDate: 2026-04-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MaaAssistantArknights/maa-cli/releases/download/v0.7.4/maa_cli-v0.7.4-x86_64-pc-windows-msvc-winget.zip
  InstallerSha256: 1F232DAE85FB33D95DB1E508D4D1F1891F34E595AD1D1B31F354C9A6FE965D8A
- Architecture: arm64
  InstallerUrl: https://github.com/MaaAssistantArknights/maa-cli/releases/download/v0.7.4/maa_cli-v0.7.4-aarch64-pc-windows-msvc-winget.zip
  InstallerSha256: 66352E49EF191FBD1083E92F89174DE47F189C505E850C6BF7006BDFA6068C07
ManifestType: installer
ManifestVersion: 1.12.0
