# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: ByteDance.AnyGen
PackageVersion: 0.7.82
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 可跨本地文件与工作流工作的 AI 智能体工作区。
Description: AnyGen 是一款 AI 智能体桌面应用，可以跨本地工作区工作：访问文件、执行操作并帮助自动化端到端工作流。它还提供 AI 幻灯片与文档生成，以及 PDF 转 PPT 等文件转换工具。
Tags:
- 人工智能
- 代码
- 大模型
- 大语言模型
- 工作区
- 智能体
- 编程
- 聊天机器人
- 自主智能
ManifestType: locale
ManifestVersion: 1.12.0
