# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: endev.aube
PackageVersion: 1.38.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: aube.exe
- RelativeFilePath: aubr.exe
- RelativeFilePath: aubx.exe
ReleaseDate: 2026-08-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/endevco/aube/releases/download/v1.38.1/aube-v1.38.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: 3EADBE826A79184792F423C52E6AD3A20575F0C408EDE66612F6DB175339A180
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/endevco/aube/releases/download/v1.38.1/aube-v1.38.1-aarch64-pc-windows-msvc.zip
  InstallerSha256: 93BD2BDAC42E2A8CC54AE02C7D4D3E46985C0883509BBA1624C355B129086F66
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
