# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: StruisICT.InLook
PackageVersion: 1.2.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{A24F9D1E-9574-45C7-83EF-53E928589EEE}'
ReleaseDate: 2026-08-28
AppsAndFeaturesEntries:
- ProductCode: '{A24F9D1E-9574-45C7-83EF-53E928589EEE}'
  UpgradeCode: '{8E5A3C2B-1D4F-4E7A-9B6C-7D8E9F0A1B2C}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\InLook'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/StruisICT/InLook/releases/download/v1.2.1/inlook-1.2.1-x86_64.msi
  InstallerSha256: 734E734820EBC852D994D946870064671FC1F0F3BDAE95DFC577F751A56EFED6
ManifestType: installer
ManifestVersion: 1.12.0
