# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: wm94i.WorkReview
PackageVersion: 1.0.35
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Work Review
ReleaseDate: 2026-04-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wm94i/Work_Review/releases/download/v1.0.35/Work_Review_1.0.35_x64-setup.exe
  InstallerSha256: AF647EF2FD303998DB16F64ABF95AA174BD0F96BF9DCCB18F5581E17B875D25B
ManifestType: installer
ManifestVersion: 1.12.0
