# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Threema.Threema.OnPrem.2
PackageVersion: 2.0.66.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19044.0
InstallerType: msix
PackageFamilyName: Threema.Desktop.OnPrem_cvh4qa9n1gk2r
ReleaseDate: 2026-08-24
Installers:
- Architecture: x64
  InstallerUrl: https://releases.threema.ch/desktop/2.0-beta64/threema-onprem-desktop-v2.0-beta64-windows-x64.msix
  InstallerSha256: 1D7C5654E6BF5E6B643B9047B4C52777CA1C3897234D6D8CD9191C364F1CDE7C
  SignatureSha256: ECF17D29E4E1A23FD63A1B81504A555A929915BAB05C563A1AF6D19BBE7493B8
ManifestType: installer
ManifestVersion: 1.12.0
