# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BtbN.FFmpeg.GPL.Shared.8.1
PackageVersion: 8.1.2-20260731
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-07-31
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-win64-gpl-shared-8.1\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-win64-gpl-shared-8.1\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-win64-gpl-shared-8.1\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-07-31-14-10/ffmpeg-n8.1.2-34-g9b6c8969e0-win64-gpl-shared-8.1.zip
  InstallerSha256: 16A289099A2C0AE4862B4F42E101C058E2227EE5F2E2AFB1660B560BB229B477
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-winarm64-gpl-shared-8.1\bin\ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-winarm64-gpl-shared-8.1\bin\ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-n8.1.2-34-g9b6c8969e0-winarm64-gpl-shared-8.1\bin\ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-07-31-14-10/ffmpeg-n8.1.2-34-g9b6c8969e0-winarm64-gpl-shared-8.1.zip
  InstallerSha256: 6DFDE4C203C1076E9D1088DDADFD5B711FC73C889C819F374DF0AE916D62574F
ManifestType: installer
ManifestVersion: 1.12.0
