# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.RegistryCleaner
PackageVersion: 4.1.0.1
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Registry Cleaner 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx86
  InstallerSha256: 356980B3DB2FAE1EE924F505742DC0E296B240C93FFA20BA6781C42D4EBCD656
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx64
  InstallerSha256: DF012C54B769966A59ABF5521815C77FD59335F5AFBD915C766F88A88B8E226C
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerarm64
  InstallerSha256: C5ADD71333D0F8A410641462B11D8CD240F6569D0ADAC8FF9C5C93B56284D634
ManifestType: installer
ManifestVersion: 1.12.0
