# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LinuxContainers.Incus
PackageVersion: 7.5.1
InstallerType: portable
Commands:
- incus
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lxc/incus/releases/download/v7.5.1/bin.windows.incus.x86_64.exe
  InstallerSha256: FE8F397E4794D706116CD5A7A4CB9292558F54147377BF8B67B3866F121535D4
- Architecture: arm64
  InstallerUrl: https://github.com/lxc/incus/releases/download/v7.5.1/bin.windows.incus.aarch64.exe
  InstallerSha256: 62F873A0A97F382650C2BBCA1A88B6F106A5A834C855E84145639561D686DDE5
ManifestType: installer
ManifestVersion: 1.12.0
