# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.uk
PackageVersion: 151.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-05-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.1/win32/uk/Firefox%20Setup%20151.0.1.exe
  InstallerSha256: 21792A89F04489FB7D158216B20D69858E9D6EFB26558F562A6D738D96CE5885
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.1/win64/uk/Firefox%20Setup%20151.0.1.exe
  InstallerSha256: 41E028E67EA28AD57CDA9B12EC3A0D8B3183BB7BD21C0C8E170957621E8B8089
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.1/win64-aarch64/uk/Firefox%20Setup%20151.0.1.exe
  InstallerSha256: 6EECC272ABF1AEDBBAE837DBF34A2C6D275D7CE8D5D1A9AC5AF6973A646AA56F
ManifestType: installer
ManifestVersion: 1.12.0
