# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Ethersphere.Swarm-Desktop
PackageVersion: 0.55.2
PackageLocale: en-US
Publisher: Swarm Association
PublisherUrl: https://www.ethswarm.org/
PublisherSupportUrl: https://github.com/ethersphere/swarm-desktop/issues
Author: Ethersphere
PackageName: Swarm Desktop
PackageUrl: https://www.ethswarm.org/build/desktop
License: BSD-3-Clause
LicenseUrl: https://github.com/ethersphere/swarm-desktop/blob/HEAD/LICENSE
Copyright: Copyright © 2025 Swarm Association
ShortDescription: Electron Desktop app that helps you easily spin up and manage Swarm node
Description: Electron Desktop app that helps you easily spin up and manage Swarm node
Moniker: swarm, p2p, node, storage
Tags:
- electron
- ethereum
- swarm
ReleaseNotes: "## [0.55.2](https://github.com/ethersphere/swarm-desktop/compare/v0.55.1...v0.55.2) (2026-08-18)\r\n\r\n\r\n### Bug Fixes\r\n\r\n• upgrade to Bee v2.8.2 ([#568](https://github.com/ethersphere/swarm-desktop/issues/568)) ([2dafdca](https://github.com/ethersphere/swarm-desktop/commit/2dafdca02dac9f85aa373485b66d817d6475e6a8))\r\n\r\n\r\n### Documentation\r\n\r\n• remove beta disclaimer from README ([#565](https://github.com/ethersphere/swarm-desktop/issues/565)) ([d5c6a7d](https://github.com/ethersphere/swarm-desktop/commit/d5c6a7d1839ce60a17c3187cdc239ee313660158))"
ReleaseNotesUrl: https://github.com/ethersphere/swarm-desktop/releases/tag/v0.55.2
ManifestType: defaultLocale
ManifestVersion: 1.12.0
