# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DefinedNet.DNClient.Desktop
PackageVersion: 0.9.5
InstallerLocale: en-US
MinimumOSVersion: 10.0.10240.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-06-04
ElevationRequirement: elevationRequired
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Defined Networking/DNClient Desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.defined.net/stable/binaries/dnclient/v0.9.5/windows/amd64/DNClient-Desktop.msi
  InstallerSha256: 2FF184AF1481BF81935864D2F49902D98515338FAC967F96F7C4F64F68F150DF
  ProductCode: '{90B74880-2A4D-4D86-80B0-CF2E922C0C37}'
  AppsAndFeaturesEntries:
  - ProductCode: '{90B74880-2A4D-4D86-80B0-CF2E922C0C37}'
    UpgradeCode: '{A2D1C63D-9291-4518-8A55-4A65BD70D9E9}'
- Architecture: arm64
  InstallerUrl: https://dl.defined.net/stable/binaries/dnclient/v0.9.5/windows/arm64/DNClient-Desktop.msi
  InstallerSha256: 6CD49C2A8EA90EE621F20DD355BB06FC0D6CC2765A5AF899816D34431C7D136E
  ProductCode: '{5FF3FBA2-A0A9-4899-831C-0F98625ED79F}'
  AppsAndFeaturesEntries:
  - ProductCode: '{5FF3FBA2-A0A9-4899-831C-0F98625ED79F}'
    UpgradeCode: '{A2D1C63D-9291-4518-8A55-4A65BD70D9E9}'
ManifestType: installer
ManifestVersion: 1.12.0
