# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Dolphin
PackageVersion: 26.08.1
InstallerType: nullsoft
UpgradeBehavior: install
ReleaseDate: 2026-09-22
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/system/dolphin/release-26.08/windows/dolphin-release_26.08-8591-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FB6E8CD6270ACC57814E4848C978DB54D21F42B81C43A2A5D24B29881642103D
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/system/dolphin/release-26.08/windows/dolphin-release_26.08-8591-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FB6E8CD6270ACC57814E4848C978DB54D21F42B81C43A2A5D24B29881642103D
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
