# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JuanjoFuchs.voice-tunnel
PackageVersion: 0.2.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: voice-tunnel.exe
  PortableCommandAlias: voice-tunnel
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JuanjoFuchs/voice-tunnel/releases/download/v0.2.4/voice-tunnel-0.2.4-windows-x64.zip
  InstallerSha256: CCFD1C8AEF8F88729B8C689720FCAC22D18562145A4268FE35C29143D46689A3
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-10
