# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jely2002.youtube-dl-gui
PackageVersion: 3.2.1
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jely2002/youtube-dl-gui/releases/download/app-v3.2.1/Open.Video.Downloader_3.2.1_x64-setup.exe
  InstallerSha256: 9174411D64DDA61AAEB951AAA98FCDCFD9701BDCEAD184B8E129E07D9AA2E5DE
- Architecture: arm64
  InstallerUrl: https://github.com/jely2002/youtube-dl-gui/releases/download/app-v3.2.1/Open.Video.Downloader_3.2.1_arm64-setup.exe
  InstallerSha256: E80F1D0724542FDDE40F3F1543E8A10E270E9E59C1A4CE969B54C20FF474EFDF
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-07-05
