# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Bomber
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: bomber
ReleaseDate: 2026-09-14
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/bomber/master/windows/bomber-master-905-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 764E5B89D74BE3B29FB8FCFC5C878953C74467B25D680298F93D5A38F4FD0B6A
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/bomber/master/windows/bomber-master-905-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 764E5B89D74BE3B29FB8FCFC5C878953C74467B25D680298F93D5A38F4FD0B6A
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
