# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Bomber
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: bomber
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/bomber/master/windows/bomber-master-816-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FE55483E76D5B6B799B3F3D897F9481DCDE03D11475C2EC77F6216CF2F531BE1
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/bomber/master/windows/bomber-master-816-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FE55483E76D5B6B799B3F3D897F9481DCDE03D11475C2EC77F6216CF2F531BE1
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
