# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: 7zip.7zr
PackageVersion: '24.06'
InstallerType: portable
Commands:
- 7zr
ReleaseDate: 2024-05-31
Installers:
- Architecture: x86
  InstallerUrl: https://sourceforge.net/projects/sevenzip/files/7-Zip/24.06/7zr.exe
  InstallerSha256: 06654D17334FA342F62D42BD805C8BC6DA8105612D9FF45C45B8F092A7C46E17
ManifestType: installer
ManifestVersion: 1.12.0
