# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FinalWire.AIDA64.Engineer
PackageVersion: "8.35"
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: AIDA64 Engineer_is1
ReleaseDate: 2026-08-16
Installers:
- Architecture: x64
  InstallerUrl: https://download.aida64.com/aida64engineer835.exe
  InstallerSha256: 871B1C882AF00BDBBAC5300E329DB8ECC9C54B1442F2B5B9AAE383E500EE97D2
ManifestType: installer
ManifestVersion: 1.12.0
