# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: M-Igashi.mp3rgui
PackageVersion: 2.0.3
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: mp3rgui.exe
ReleaseDate: 2026-03-20
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/M-Igashi/mp3rgain/releases/download/v2.0.3/mp3rgui-v2.0.3-windows-x86_64.zip
    InstallerSha256: CD9B6BE297E85FC6E2760189C3491FD516CADCC5141C8AC44978933EB2BC3A2A
  - Architecture: arm64
    InstallerUrl: https://github.com/M-Igashi/mp3rgain/releases/download/v2.0.3/mp3rgui-v2.0.3-windows-arm64.zip
    InstallerSha256: 9466E73603FE7CD76F7EC77EB07A726CE47C872822D8C5A653A8E9CBFB6A23A5
ManifestType: installer
ManifestVersion: 1.12.0
