# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: FOSSA.FOSSA-cli
PackageVersion: 3.17.13
PackageLocale: en-US
Publisher: FOSSA
PublisherUrl: https://fossa.com/
PublisherSupportUrl: https://github.com/fossas/fossa-cli/issues
PackageName: fossa-cli
PackageUrl: https://github.com/fossas/fossa-cli
License: MPL-2.0
LicenseUrl: https://github.com/fossas/fossa-cli/blob/HEAD/LICENSE
ShortDescription: Fast, portable and reliable dependency analysis for any codebase.
Moniker: fossa
Tags:
- open-source-licensing
- open-source-vulnerabilities
ReleaseNotes: |-
  What's Changed
  - Pnpm lock refactor by @csasarak in #1725
  - Bump version for themis v1.0.58 by @zlav in #1729
  - Release groups: resolve add-projects target via server-side lookup (CORE-7241) by @lackstein in #1728
  Full Changelog: v3.17.12...v3.17.13
ReleaseNotesUrl: https://github.com/fossas/fossa-cli/releases/tag/v3.17.13
ManifestType: defaultLocale
ManifestVersion: 1.12.0
