# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.gl
PackageVersion: 151.0.4
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-06-09
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win32/gl/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: 7445FBAC0B281E4776ADBABA76A675D7E3586893A5CE34974D4D3D50F719CA69
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win64/gl/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: E49D60722B368198FC684BA26B92312245C5BE2B720A48321012965E73A76071
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win64-aarch64/gl/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: CA4ECBCCC35FD68FEDCBEDE8105B3811054EAA3F144E5A2A1A25E262576E8577
ManifestType: installer
ManifestVersion: 1.12.0
