# Created with komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.DockerDesktop
PackageVersion: 4.66.1
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: install --quiet
  SilentWithProgress: install --quiet
UpgradeBehavior: install
ReleaseDate: 2026-03-26
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://desktop.docker.com/win/main/amd64/222799/Docker%20Desktop%20Installer.exe
  InstallerSha256: 4005825EB546424C1D16A27E3A514EFCC2D66BABEA70DC8345073507B7A52A37
- Architecture: arm64
  InstallerUrl: https://desktop.docker.com/win/main/arm64/222799/Docker%20Desktop%20Installer.exe
  InstallerSha256: 18BF47B28B49E55EFDC63484DF7E7FCC5231C63650BAF006A86F6C435FE0E3E6
ManifestType: installer
ManifestVersion: 1.12.0
