# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Psynect.OmniMend
PackageVersion: 2.0.8
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://crashpro-inference.psynect.workers.dev/releases/v2.0.8/OmniMend-v2.0.8-offline-setup.exe
  InstallerSha256: 9B21D84EC9B0E66749CDA0A93F9570E6101B1C521FE8F1736581959F7931072D
ManifestType: installer
ManifestVersion: 1.12.0
