# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Routebase.Routebase
PackageVersion: 1.8.4
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /P
UpgradeBehavior: install
ReleaseDate: 2026-09-11
Installers:
  - Architecture: x64
    InstallerUrl: https://releases.routebase.dev/desktop/1.8.4/Routebase_1.8.4_x64-setup.exe
    InstallerSha256: 4234B9A70CF53A0CCC3811F5B0D1953A20537FEEF70273DBFA678B869650E5B1
    ProductCode: Routebase
ManifestType: installer
ManifestVersion: 1.12.0
