# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ast
PackageVersion: 150.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-04-28
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win32/ast/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: DBD6313C45AEBD80DE9AF81CB450DC26B63126DDC00D50676E45267D53D04F21
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win64/ast/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: 1B0249E8696F1806BE035B24CB805EED877DBCAF5D33B97EFA670298FC35A028
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.1/win64-aarch64/ast/Firefox%20Setup%20150.0.1.exe
  InstallerSha256: 29CBC2A4BF35F61D590CC11B00569DBDEC08963E2AA18229B52ADA9D4A7E7510
ManifestType: installer
ManifestVersion: 1.12.0
