# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: raphamorim.rio
PackageVersion: 0.5.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-07-27
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Rio'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/raphamorim/rio/releases/download/v0.5.0/Rio-installer-x86_64.msi
  InstallerSha256: 36017FF70AB8E86608BF432BBAFB8DE696AAAC5B093389E25D5901B444BE72DD
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{B9A331F6-FEDB-441D-97BF-93519BC9A305}'
  AppsAndFeaturesEntries:
  - ProductCode: '{B9A331F6-FEDB-441D-97BF-93519BC9A305}'
    UpgradeCode: '{87C21C74-DBD5-4584-89D5-46D9CD0C40A8}'
- Architecture: arm64
  InstallerUrl: https://github.com/raphamorim/rio/releases/download/v0.5.0/Rio-installer-aarch64.msi
  InstallerSha256: CB6D1EAEBF9853CBF677D9F4AACEF205228368753CFE4F9EABBA182642B37D4D
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
  ProductCode: '{E07DF576-E1BD-433B-914C-576210FE83AA}'
  AppsAndFeaturesEntries:
  - ProductCode: '{E07DF576-E1BD-433B-914C-576210FE83AA}'
    UpgradeCode: '{87C21C74-DBD5-4584-89D5-46D9CD0C40A8}'
ManifestType: installer
ManifestVersion: 1.12.0
