# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: BroadcastRadio.MyriadPlayoutSupportApplications
PackageVersion: 6.9.26215
PackageLocale: en-US
Publisher: Broadcast Radio Limited
PublisherUrl: https://www.broadcastradio.com/
PublisherSupportUrl: https://help.broadcastradio.com/
PrivacyUrl: https://www.broadcastradio.com/website-privacy-policy
Author: Broadcast Radio Limited
PackageName: Myriad Playout Support Applications v6
PackageUrl: https://www.broadcastradio.com/myriad-6-playout-support
License: Proprietary
LicenseUrl: https://help.broadcastradio.com/support/solutions/articles/101000536668
Copyright: © Broadcast Radio Ltd.
CopyrightUrl: https://help.broadcastradio.com/support/solutions/articles/101000536668
ShortDescription: Support applications for Myriad Playout v6, including Remote Edit Server, AutoImporter, OCP and Backup
Description: 'Myriad Playout Support Applications v6 bundles the supporting tools for Myriad Playout: the Remote Edit Server, the AutoImporter for automated media import, the On-Air Client Panel (OCP), and the backup utility.'
Tags:
- backup
- broadcast
- importer
- ocp
- radio
- remote
- support
ReleaseNotes: |-
  Myriad Remote Edit Server Changes:
  New Features/Changes:
  REST API:
  - Log: There are 3 new API methods to work with the Scheduled Log:
    - /BrMyriadRES/v6/api/Log/ReadHourInformation - reads top level information about 1 or more hours from the Scheduled Log.
    - /BrMyriadRES/v6/api/Log/AddHour - writes a complete hour to the Scheduled Log for the specified time. Includes options to control when existing hours can be overwritten.
    - /BrMyriadRES/v6/api/Log/DeleteHour - deletes a complete hour from the Scheduled Log. Includes a forceDelete parameter to control if Edited hours can be deleted.
  The following issues have been fixed:
  - Myriad OCP: The Broadcast.Radio Output has been updated to handle multiple updates being received in quick succession when using slower internet connections. This could cause double listing of the same song in the Song History in Broadcast.Radio.
  - Myriad Remote Edit Server: Fixed an issue where the Myriad Anywhere Tunnel might not reconnect to the Myriad Anywhere Cloud if the internet connection was temporarily lost in certain circumstances
  - Myriad Remote Edit Server: Fixed an issue with the Media/UpdateMediaItem REST api where some fields would not be written when using the method to create a brand new Media Item.
ReleaseNotesUrl: https://support.broadcastradio.com/Products/Myriad/v6/v6.9.26215/Support//MyriadSupportApplicationsVersionHistory.html
ManifestType: defaultLocale
ManifestVersion: 1.12.0
