# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 140.10.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.en-US.win64.installer.exe
  InstallerSha256: 8B329005113DB6B3BE35233D086F66ADC237BE0E55E7E0B98BB33F46564C1668
  ProductCode: Betterbird 140.10.0 (x64 en-US)
- InstallerLocale: de
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.de.win64.installer.exe
  InstallerSha256: 7E07D40F63662AF8785D8955CB7C7E80A7ECE6519C71E1ECCC05236938A0C5C4
  ProductCode: Betterbird 140.10.0 (x64 de)
- InstallerLocale: es-ES
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.es-ES.win64.installer.exe
  InstallerSha256: A4094997F88673A489F35D520B176A401E21A010DFED2AB76E9DF366128DE37B
  ProductCode: Betterbird 140.10.0 (x64 es-ES)
- InstallerLocale: fr
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.fr.win64.installer.exe
  InstallerSha256: A3AC697DEF2F985326189F3FB498EA931D462F74F8934D0858A24A9FB17B2EA3
  ProductCode: Betterbird 140.10.0 (x64 fr)
- InstallerLocale: it
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.it.win64.installer.exe
  InstallerSha256: 68940156BF5CFE77813AA5169CDFEF6F3680EBC3E217F19CE5047BBC05065C13
  ProductCode: Betterbird 140.10.0 (x64 it)
- InstallerLocale: ja
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.ja.win64.installer.exe
  InstallerSha256: 5197566D16061BEDA161048986F0FCFD8B7D947F5B91DEB398FFE2FAA6F5EE48
  ProductCode: Betterbird 140.10.0 (x64 ja)
- InstallerLocale: nl
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.nl.win64.installer.exe
  InstallerSha256: 9E3659E17F2A1C80C6F0A61E1FCF1B1B76FB4EB81CD3CD37864BF05F64641BA5
  ProductCode: Betterbird 140.10.0 (x64 nl)
- InstallerLocale: pt-BR
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.pt-BR.win64.installer.exe
  InstallerSha256: 6B7115133C1660876093E7CB395FD20EF1A83F60A89BF0DB3C5999E1788A7195
  ProductCode: Betterbird 140.10.0 (x64 pt-BR)
- InstallerLocale: ru
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-140.10.0esr-bb21.ru.win64.installer.exe
  InstallerSha256: B9BC8FDDBDE5697F1CE439873C39CDA677CA2850A13F640465466782A431F5C8
  ProductCode: Betterbird 140.10.0 (x64 ru)
ManifestType: installer
ManifestVersion: 1.12.0
