# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: TaeminGames.Heimdall
PackageVersion: 3.4.287
InstallerLocale: ko-KR
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/sontaemin80/Heimdall-OS/releases/download/v3.4.287/HEIMDALL_Setup_v3.4.287.exe
    InstallerSha256: 6dcdbeb3daa87800bc018ebc90852037a3b1041ddeee471ce564aea8d0e03bb2
ManifestType: installer
ManifestVersion: 1.6.0
