# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PerryTS.Perry
PackageVersion: 0.5.891
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: perry.exe
  PortableCommandAlias: perry
Dependencies:
  PackageDependencies:
  - PackageIdentifier: LLVM.LLVM
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PerryTS/perry/releases/download/v0.5.891/perry-windows-x86_64.zip
  InstallerSha256: AC1D39847840BDA2D7ED56CD67D66ED78384B1DFDC17DBEF4B7D38037A75419E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-13
