# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.he
PackageVersion: 155.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-04
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/155.0.1/win32/he/Firefox%20Setup%20155.0.1.exe
  InstallerSha256: 608112263AF7C1C51CB832C74D9F7EFEC07422BED3ABD4DF6DC2305DDEA01458
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/155.0.1/win64/he/Firefox%20Setup%20155.0.1.exe
  InstallerSha256: 61D20B5B51268C4447B6C3558B60BB99EA386BB87C22F4822AE83DD3ED2AB42F
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/155.0.1/win64-aarch64/he/Firefox%20Setup%20155.0.1.exe
  InstallerSha256: 6EF039C8BDFE6F9B640878B73A447C0418A5D4ABDDF2B971F06AD8D63AD96409
ManifestType: installer
ManifestVersion: 1.12.0
