# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 154.0.8019.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-08-23
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/fub4qdnehmr4yojhzab4kaatdu_154.0.8019.0/154.0.8019.0_chrome_installer_uncompressed.exe
  InstallerSha256: 03F3F7DC3814C342F9FB61DFCD08C1836E3AB6E8C2DC2A7C6FE2518FDE5A5050
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/ltyfwugvwilv6hwsl5cgeazyyq_154.0.8019.0/154.0.8019.0_chrome_installer_uncompressed.exe
  InstallerSha256: A2EA6A4A649587B3D81F2256AAC37DB9769A37673C8E1951B7A1A045481E9B68
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/jaryrhzsmojxdrch3h2owi6cia_154.0.8019.0/154.0.8019.0_chrome_installer_uncompressed.exe
  InstallerSha256: 58C3E3FA84EAA6DF77E36C2CD73FD16D0AFA62F3FDACC69E699B2E594EB804A8
ManifestType: installer
ManifestVersion: 1.12.0
