# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Kubetail.Kubetail
PackageVersion: 0.14.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: kubetail.exe
    PortableCommandAlias: kubetail
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/kubetail-org/kubetail/releases/download/cli%2Fv0.14.0/kubetail-windows-amd64.zip
    InstallerSha256: 6e77188e4430d7c724c5cfcda975b2e9d4dd60f6070967e719626a98b57aaffc
  - Architecture: arm64
    InstallerUrl: https://github.com/kubetail-org/kubetail/releases/download/cli%2Fv0.14.0/kubetail-windows-arm64.zip
    InstallerSha256: 1db6ecf1ac10ab649751689a6accf17b327cdab63d7758d23e112008ffa10b17
ManifestType: installer
ManifestVersion: 1.10.0
