# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Stylebending.Aperture
PackageVersion: 0.3.0
InstallerType: portable
Commands:
- aperture
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stylebending/Aperture/releases/download/v0.3.0/Aperture.exe
  InstallerSha256: 093CBFBC411F44013573416E98680563CB5C5626F8176285A6A74B01A9319DE2
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-07-26
