# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenAI.Codex
PackageVersion: 0.139.0
InstallerType: zip
NestedInstallerType: portable
Commands:
- codex
ReleaseDate: 2026-06-09
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  - RelativeFilePath: codex-x86_64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.139.0/codex-x86_64-pc-windows-msvc.exe.zip
  InstallerSha256: 1F76F5E211E36A204883B2975B39BF3F5AD106D7B7A84D45E9A1C062983E0902
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: codex-aarch64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.139.0/codex-aarch64-pc-windows-msvc.exe.zip
  InstallerSha256: 72BF328225419571705FB161B26AC2AF5A74C6C45B8ECC84C3C35DB43DD02B51
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
