# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.FirebaseCLI
PackageVersion: 15.14.0
InstallerType: portable
InstallModes:
- silent
Commands:
- firebase
ReleaseDate: 2026-04-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/firebase/firebase-tools/releases/download/v15.14.0/firebase-tools-win.exe
  InstallerSha256: F175CF0C0BE7E2A86D3E3390311F87DEE6EE833D3880751BB332C5D5FBAA8B85
ManifestType: installer
ManifestVersion: 1.12.0
