# Automatically updated by the winget bot at 2026/Jun/16
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.SoftwareUpdater
PackageVersion: 1.0.7.3
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Software Updater 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/softwareupdaterx86
  InstallerSha256: 2F3E38D39652F4ECD28A625AB573D43EB47A7274C208CBC1B8C16FB6E993385F
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/softwareupdaterx64
  InstallerSha256: 5962A9781298A389FDD6721CC6F15305E5B765B6181C1F6454D479C80D50D2FF
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/softwareupdaterarm64
  InstallerSha256: 1EF470B181D5BE738B22E8C98478E9B256EF1B3F72ABCDE0F21107397328D8F2
ManifestType: installer
ManifestVersion: 1.12.0
