# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sbt.sbt
PackageVersion: 2.0.5
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{CE07BE71-510D-414A-92D4-DFF47631848A}'
ReleaseDate: 2026-08-03
AppsAndFeaturesEntries:
- DisplayName: sbt 2.0.5
  Publisher: Scala Center
  ProductCode: '{CE07BE71-510D-414A-92D4-DFF47631848A}'
  UpgradeCode: '{D77590D3-7919-7168-4627-7A4D8EE2E51F}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%/sbt'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/sbt/sbt/releases/download/v2.0.5/sbt-2.0.5.msi
  InstallerSha256: 9022B629B45FED7C2FADDFAF0EA0F8E067325147A67E84C989237DC8209AB846
ManifestType: installer
ManifestVersion: 1.12.0
