# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ledgerful.Ledgerful
PackageVersion: 0.2.14
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ledgerful.exe
  PortableCommandAlias: ledgerful
Commands:
- ledgerful
ReleaseDate: 2026-09-18
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ryan-AI-Studios/Ledgerful/releases/download/v0.2.14/ledgerful-x86_64-pc-windows-msvc.zip
  InstallerSha256: 61FF2E5D6CC1FDC6A7CF1C45618F55E454D5FD6AAADD0557CBDE73731B1107AE
ManifestType: installer
ManifestVersion: 1.12.0
