# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Appest.Dida
PackageVersion: 8.0.8.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Protocols:
- ticktick
ReleaseDate: 2026-05-18
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.dida365.cn/download/win/dida_win_setup_release_x86_8080.exe
  InstallerSha256: B06E516C9E5E68D99C3A23D011D8110FD8D7658D41A42A5DF0EBA5D2C50A11C1
- Architecture: x64
  InstallerUrl: https://cdn.dida365.cn/download/win64/dida_win_setup_release_x64_8080.exe
  InstallerSha256: 6C799E531900A7A75D71F34554BD083FEF28788A9AE94680AA630B2892EC9790
ManifestType: installer
ManifestVersion: 1.12.0
