# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Qualcomm.Snapdragon.ESRT
PackageVersion: 1.0.4
ReleaseDate: 2026-03-30
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: SnapdragonEnterpriseSoftwareReadinessTool.exe
  PortableCommandAlias: esrt
Installers:
- Architecture: x64
  InstallerUrl: https://softwarecenter.qualcomm.com/api/download/software/tools/Snapdragon_ESRT/Windows/1.0.4.0/SnapdragonEnterpriseSoftwareReadinessTool.zip
  InstallerSha256: 0919585B42159A66A50069C77B24F8E45A6BF38B98B109E896C3DFC5421FF847
ManifestType: installer
ManifestVersion: 1.12.0