# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ca
PackageVersion: 148.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-03-10
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/148.0.1/win32/ca/Thunderbird%20Setup%20148.0.1.exe
  InstallerSha256: 3EF5641018A7F59C232AD9CED621D00A47C7F7AA29A3DD3B6EF78346000600CC
  ProductCode: Mozilla Thunderbird 148.0.1 (x86 ca)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/148.0.1/win64/ca/Thunderbird%20Setup%20148.0.1.exe
  InstallerSha256: 513BDE15F0587145AFE525D91428AE69343B64A185A8A08C9941C36791AE5758
  ProductCode: Mozilla Thunderbird 148.0.1 (x64 ca)
ManifestType: installer
ManifestVersion: 1.12.0
