# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: KGSOnline.CGoban
PackageVersion: 3.5.23
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://files.gokgs.com/javaBin/cgoban.msi
  InstallerSha256: e8a15effa671bfbac959213f5427e86f2477e4848d381077764d2505d05c20fd
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://files.gokgs.com/javaBin/cgoban.exe
  InstallerSha256: 623385AF77E75A6F315E7625C5AE72EE919EA064A4F57C7F9F6993A04697F0D7
ManifestType: installer
ManifestVersion: 1.9.0
