# Automatically updated by the winget bot at 2026/Jul/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.SystemManager
PackageVersion: 1.0.3.1
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente System Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx86
  InstallerSha256: E4CCF5FDD64C911326156F2B2E708C0A54DA6113312BF85762E88DA6E28CAE5E
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx64
  InstallerSha256: DFACA9B349B8DDEBF0B9D07BF7BD7C4AA4C7C30079FF9382C8ABF885A854F085
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerarm64
  InstallerSha256: 777C6035EC41DB3475ABD0AFF431ECE5A96D5D068F956ED7E165B7816F6141C7
ManifestType: installer
ManifestVersion: 1.12.0
