# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: 0state.scafld
PackageVersion: 2.4.4
InstallerLocale: en-US
InstallerType: portable
Commands:
  - scafld
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nilstate/scafld/releases/download/v2.4.4/scafld_2.4.4_windows_amd64.exe
    InstallerSha256: 7d90de49a796151b3dc82595b205124350dc2715bc0398fbb57143b5521714db
  - Architecture: arm64
    InstallerUrl: https://github.com/nilstate/scafld/releases/download/v2.4.4/scafld_2.4.4_windows_arm64.exe
    InstallerSha256: 62a5edb2cb4e3aec699ee6b319fcf37ee5b91609e0bff6a2d1d94ef237f77d42
ManifestType: installer
ManifestVersion: 1.9.0
