# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1780601115-gdd09a6
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1780601115-gdd09a6/amp-windows-x64-baseline.exe
  InstallerSha256: 8A20DB07F13A962E2A848D02B665961103FC5CE8D8F1266045C78888D49CB19C
ManifestType: installer
ManifestVersion: 1.12.0
