# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Unity.CLI
PackageVersion: 1.0.0.20009
InstallerLocale: en-US
InstallerType: msix
MinimumOSVersion: 10.0.17763.0
PackageFamilyName: UnityTechnologies.UnityCLI_2vrhnee42bhxm
Commands:
- unity
ReleaseDate: 2026-09-08
Installers:
- Architecture: x64
  InstallerUrl: https://public-cdn.cloud.unity3d.com/hub/prod/cli/1.0.0-beta.9/unity-windows-x64.msix
  InstallerSha256: 08DC6B675F6C852FF19DDA1E6D4BF4BF5875320B5A6613BF59929B943DB84483
  SignatureSha256: 163C803DB3C83E7C9DA98B66EAC07F82403F693ADD641B9EB3BE5B3B500B5158
- Architecture: arm64
  InstallerUrl: https://public-cdn.cloud.unity3d.com/hub/prod/cli/1.0.0-beta.9/unity-windows-arm64.msix
  InstallerSha256: F26DD26ABEA7CA37840AF6E5AE8A8D6DA417209F854B83AE626415ED554EF9F4
  SignatureSha256: D21D468FB916C902A4F03450EBD97332ADCE41BC717096453D779CC5FD8D02DF
ManifestType: installer
ManifestVersion: 1.12.0
