# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hwtnb.SylphyHornPlus
PackageVersion: 4.0.0-beta.16
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: SylphyHorn/SylphyHorn.WinGetLauncher.exe
  PortableCommandAlias: SylphyHornPlus
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.16/SylphyHornPlus-v4.0.0-beta.16-x86.zip
  InstallerSha256: FABDED7AA874F66ED5E4156B1BB80F24892DF688FA5E8626291F045E93167D88
- Architecture: x64
  InstallerUrl: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.16/SylphyHornPlus-v4.0.0-beta.16-x64.zip
  InstallerSha256: 31681525BF5482D7AA29BD2F41AF8B41E32B76EDA6785ADCAB96EA38D43EB71F
- Architecture: arm64
  InstallerUrl: https://github.com/hwtnb/SylphyHornPlusWin11/releases/download/v4.0.0-beta.16/SylphyHornPlus-v4.0.0-beta.16-arm64.zip
  InstallerSha256: 04AF68230141C104745934E0B4D7FA225AD3ADF36B6B70A3AFF324648C6E0E4B
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-20
