# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hoppscotch.Hoppscotch
PackageVersion: 26.4.0-0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{3E267CA3-D20D-4989-A206-346F8A24C9EE}'
ReleaseDate: 2026-04-30
AppsAndFeaturesEntries:
- DisplayVersion: 26.4.0
  ProductCode: '{3E267CA3-D20D-4989-A206-346F8A24C9EE}'
  UpgradeCode: '{75553029-191D-517B-AAA3-B841B7DD3064}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Hoppscotch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hoppscotch/releases/releases/download/v26.4.0-0/Hoppscotch_win_x64.msi
  InstallerSha256: 440FECDA30882836B21B19A9987CCC63A96DC16F9E8CCD18037DEC55DB8AC31F
ManifestType: installer
ManifestVersion: 1.12.0
