# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dell.Optimizer
PackageVersion: 6.3.4.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
  Log: /l="<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: rebootRequiredToFinish
Protocols:
- delloptimizer
ProductCode: '{CC40119D-6ADF-4832-8025-4808195E41D5}'
ReleaseDate: 2026-07-09
Installers:
- Architecture: x64
  InstallerUrl: https://dl.dell.com/FOLDER14755376M/1/Dell-Optimizer-Application_5N4CV_WIN64_6.3.4.0_A00.EXE
  InstallerSha256: 632A6959D8BA4E8DAD80DB2D1DCA201D3CC9E1FBDF11265927E2AC817077484C
- Architecture: arm64
  InstallerUrl: https://dl.dell.com/FOLDER14755334M/2/Dell-Optimizer-Application_NNY96_WINARM64_6.3.4.0_A00.EXE
  InstallerSha256: DDD226DB46F4AEE95B18DBF169442A9666B52356E73E80B4B58691DE8EDEF120
ManifestType: installer
ManifestVersion: 1.12.0
