# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Microsoft.LogCheetah
PackageVersion: 1.1.0
PackageLocale: en-GB
ShortDescription: A Windows GUI tool for viewing column-based log data, optimised for interacting with large volumes (millions of rows) of data in memory at once.
ManifestType: locale
ManifestVersion: 1.12.0
