# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TinyHumansAI.OpenHuman
PackageVersion: 0.57.52
UpgradeBehavior: install
ReleaseDate: 2026-06-20
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.57.52/OpenHuman_0.57.52_x64-setup.exe
  InstallerSha256: 87D89AF3CBC7B39420E0480245EF70A0BA25593822FD093FECE35C833FD475FA
  ProductCode: OpenHuman
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.57.52/OpenHuman_0.57.52_x64_en-US.msi
  InstallerSha256: 675CA1EC3FC4648BFF765BE38D60BE4EA183DEA140C746093902BF0275A5A27C
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{06753C9F-7575-4630-8A17-F0BFFA29826F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{54052255-0CFF-5EA8-82D1-C533E6DE0990}'
ManifestType: installer
ManifestVersion: 1.12.0
