# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.pa-IN
PackageVersion: 140.11.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-05-19
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.11.0esr/win32/pa-IN/Thunderbird%20Setup%20140.11.0esr.exe
  InstallerSha256: EF40A07F49989A2F01C2E3A756C7E0F1EA0FF4E5FF6C2B7F8AB85DA88A54F578
  ProductCode: Mozilla Thunderbird 140.11.0 (x86 pa-IN)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 pa-IN)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.11.0esr/win64/pa-IN/Thunderbird%20Setup%20140.11.0esr.exe
  InstallerSha256: BC9D638D2C48AADDB5B40B4D4A071C787AE6438252C176B2B30F3A30EF88BA64
  ProductCode: Mozilla Thunderbird 140.11.0 (x64 pa-IN)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 pa-IN)
ManifestType: installer
ManifestVersion: 1.12.0
