# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TerraformLinters.tflint
PackageVersion: 0.63.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tflint.exe
Commands:
- tflint
FileExtensions:
- hcl
- tf
ReleaseDate: 2026-06-03
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_windows_386.zip
  InstallerSha256: 401E97DF8675D7B42E8DBFEAFD1EB93A4152C19A6E305E6B94C8D7CDA1B3D28C
- Architecture: x64
  InstallerUrl: https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_windows_amd64.zip
  InstallerSha256: 5FBFB643B83C4AD489BDE15A0E0D46E53DC9AA8DFA76D25DA3C4BD2698A41A19
ManifestType: installer
ManifestVersion: 1.12.0
