# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Yeastar.Linkus.Desktop.MSI
PackageVersion: 1.21.2.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- callto
- linkus
- tel
ProductCode: '{F0526ACD-4014-4FAC-B03C-869FE74D1AE8}'
AppsAndFeaturesEntries:
- UpgradeCode: '{C330D237-16BF-5693-99E4-97CDCE68770A}'
Installers:
- Architecture: x86
  InstallerUrl: https://image.yeastar.com/Yeastardownload/linkus_desktop_windows_msi_version.msi
  InstallerSha256: A939997E61704B23AC73BAB0D773F59162D55F474E8F641F496CE73C1200EFC7
ManifestType: installer
ManifestVersion: 1.12.0
