# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Bitwarden.Bitwarden
PackageVersion: 2026.7.0
PackageLocale: en-US
Publisher: Bitwarden Inc.
PublisherUrl: https://bitwarden.com/
PublisherSupportUrl: https://bitwarden.com/help
PrivacyUrl: https://bitwarden.com/privacy
Author: Bitwarden Inc.
PackageName: Bitwarden
PackageUrl: https://bitwarden.com/
License: GPL-3.0 or Bitwarden-1.0
LicenseUrl: https://github.com/bitwarden/clients/blob/HEAD/LICENSE.txt
Copyright: Copyright © 2015-2026 Bitwarden Inc.
CopyrightUrl: https://github.com/bitwarden/server/blob/HEAD/TRADEMARK_GUIDELINES.md
ShortDescription: A secure and free password manager for all of your devices.
Tags:
- card-storage
- credentials
- passphrases
- password-manager
- protect
- protection
- security
- ssh-keys
- vault
ReleaseNotes: |-
  What's Changed

  💙 Community Highlight
  - [PM-38362] fix(powermonitor): Improve connection handling and remove unwraps by @ChihweiLHBird in #20919
  - [PM-32423] Add a less confusing argument and environment variable name to disable updates by @marcquark in #19045
  - [PM-35288] feat: auto-close sso tab after authentication completes by @sander-adamse in #20213
  - [PM-38760] Recursively create directory when writing manifest by @pschlan in #21141
  - [PM-36443] fix microsoft totp autofill by @danysigha in #20481
  - [PM-33285] Enhance privacy in password leak detection with response padding by @TheDcoder in #19439
  - [PM-38109] fix(browser): use direct clipboard API when popup has DOM access by @RobinAngele in #20859
  - [PM-39179] fix(desktop): correct various typos in desktop application by @luojiyin1987 in #21322
  - [PM-39180] fix(browser): correct various typos in browser extension by @luojiyin1987 in #21323
  - [PM-39177] fix(libs): correct various typos in shared libraries and documentation by @luojiyin1987 in #21320
  - [PM-38123] [bug] Preserve 1Password archive state on 1pux import (closes #20694) by @999purple999 in #20867
  - [PM-33198] Keeper direct importer by @detunized in #19395

  Feature Development
  - [PM-38565] Replace tray settings with "Keep Bitwarden running in the background" by @quexten in #21044
  - [PM-39048] Feat: scaffold @bitwarden/pam library by @Hinton in #21259
  - [PM-34779] Add accept method to OrganizationInviteLinkApiService by @r-tome in #21266
  - [PM-31884] implemented controls for send policy access dropdown by @bmbitwarden in #19777
  - Auth/PM-38298 - Org Invite Acceptance Refactor by @JaredSnider-Bitwarden in #21011
  - [PM-35059] Coachmark tour for Access Intelligence by @voommen-livefront in #20808
  - [PM-38580] Adds copy to invite member role select by @BTreston in #21280
  - [PM-38787] Pin vault bulk-actions bar to the viewport on scroll by @nick-livefront in #21154
  - [PM-34023] Remove 2FA account recovery flag by @eliykat in #21291
  - PM 35229 [Browser/Desktop] Stripe Checkout from upgrade dialog by @cyprain-okeke in #20592
  - [PM-36835] implement logging in the weak-passwords component by @voommen-livefront in #21305
  - Revert "[PM-36835] implement logging in the weak-passwords component" by @voommen-livefront in #21343
  - Revert "Revert "[PM-36835] implement logging in the weak-passwords component"" by @voommen-livefront in #21344
  - IPC Desktop <-> Browser transport by @coroiu in #19908
  - [PM-34053] Swap verify trust to new SDK method by @Thomas-Avery in #21347
  - [PM-39070] Create new permissions screen by @dan-livefront in #21311
  - [PM-39129] Add UsePam organization capability by @Hinton in #21298
  - [PM-39195] Add banner to scimv2 component for invite link by @BTreston in #21363
  - [BEEEP] [PM-38226] Add disable auto-start option for snap by @quexten in #20855
  - [PM-38834]Allow programmatic changes to Firefox settings by @dan-livefront in #21177
  - [PM-37986] Centralized ownership UI rework by @BTreston in #21348
  - [PM-35230] clients Web Checkout success page by @cyprain-okeke in #20653
  - Auth/PM-38742 - SSO Invited Existing User Flow Improvement - Show SSO redirect error notification on LoginComponent by @JaredSnider-Bitwarden in #21134
  - [PM-36864] Refactor vault routing to use VaultV2Component directly, removing feature flagged code by @JaredScar in #21419
  - [PM-37875] Automatic V2 Upgrade Migration by @quexten in #20831
  - [PM-38778]Make Bitwarden default password manager, callout implementation. by @dan-livefront in #21156
  - [PM-39195] Back port banner to old component by @BTreston in #21415
  - [PM-34580] Rename "Note" to "Secure note" for SecureNote cipher type by @nick-livefront in #21423
  - [PM-33740] Remove unlock service for password flagged logic by @mzieniukbw in #21427
  - [PM-37555] add autofill lifecycle by @audreyality in #20949
  - [PM-33408] Add OrganizationUserNotification banner to vault by @jengstrom-bw in #21209
  - [PM-37807] Implement VaultBatchBarComponent on organization vault by @gbubemismith in #21345
  - [PM-32696] Add data field to Cipher object to support blob encryption by @nikwithak in #20765
  - [PM-24223] Add feature flagged support for password v2 registration by @eligrubb in #20782
  - [PM-38345] block account, remove card, remove free fam, and desktop autotype to simple toggle by @JaredScar in #21097
  - [PM-3841] - Default the new collection organization select to the active org by @jaasen-livefront in #21374
  - [PM-38343] 2 step and require sso and remove unlock and remove export into simple toggle by @JaredScar in #21092
  - [PM-33410] Add organizationusernotification banners to vault desktop by @jengstrom-bw in #21462
  - [PM-29785] Abstract Windows Passkey Plugin Authenticator COM implementation by @iinuwa in #20285
  - [PM-33409] Add organizationusernotification banner to vault browser by @jengstrom-bw in #21461
  - [PM-37978] update UI for MP policy, refactor org lookup by @BTreston in #21313
  - [CL-1138] Add stacked drawer support with back button by @willmartian in #19804
  - [PM-38480] Add Staged Event Message by @sven-bitwarden in #21499
  - [PM-32402] Update copy from new to add/create web app by @jengstrom-bw in #21355
  - [PM-35106] Make AES-GCM the default algorithm in crypto.rs for secure memory by @mzieniukbw in #21553
  - [PM-37808] Bulk Selection + Batch Bar for Desktop by @nick-livefront in #21308
  - [PM-39472] Note -> Secure Note by @nick-livefront in #21469
  - [PM-37987] update drawer UI for account recovery administration policy by @JaredScar in #21565
  - [PM-37989] update drawer UI for password generator policy by @JaredScar in #21564
  - [PM-38346] Single Org and Autofill into SimpleTogglePolicyComponent by @JaredScar in #21595
  - [PM-38481] Add Staged Filter for Organization Members by @sven-bitwarden in #21394
  - [PM-29785] CTAP2 CBOR Parser by @iinuwa in #21584
  - [PM-39071]Wire new permissions screen by @dan-livefront in #21391
  - [PM-38828]Change settings order and copy by @dan-livefront in #21464
  - [PM-29785] Allow waiting for Autofill IPC connection in Windows authenticator by @iinuwa in #21615
  - [PM-29790] Prepare for separate Windows Passkey Plugin Authenticator exe by @iinuwa in #21616
  - [PM-29790] Add credential request processing for Windows passkey plugin by @iinuwa in #21618
  - Auth/PM-39774 - SSO - Improve error for existing users without org membership by @JaredSnider-Bitwarden in #21573
  - [PM-29790] Wire up authenticator IPC and COM server for Windows passkey plugin by @iinuwa in #21622
  - [PM-34393] Show invite link events in event log by @r-tome in #21335
  - [CL-1158] update browser footer by @BryanCunningham in #21612
  - [PM-37963] - Add Staged Member Actions by @sven-bitwarden in #21597
  - [PM-29790] Windows passkey plugin: unify signature verification by @iinuwa in #21634
  - windows-plugin: Add plugin entrypoint by @iinuwa in #21635
  - [PM-33362] Autotype Edit Cipher Initial Changes by @coltonhurst in #21500
  - [PM-37988] Add SessionTimeoutPolicyV2 component usage for new policy drawers by @JaredScar in #21561
  - [PM-39147] Batch bar copy fixes — singular/plural toasts and dialog title by @nick-livefront in #21602
  - PM-32187 implemented restrict send type by @bmbitwarden in #20129
  - [PM-40060] Add native messaging permission dialog by @quexten in #21703
  - Pm 31929 new send policy for deletion days by @bmbitwarden in #20128
  - [PM-33054] Remove feature flag cipher-key-encryption by @jengstrom-bw in #21309
  - [PM-36505] Finalize Send Controls policy design, adjust base policy component enabled display logic by @mcamirault in #21739
  - [PM-39876] Implement targeting rules form category by @jprusik in #21715
  - [PM-20344] Disallow multiple attachments with the same name, handle existing in zip export format by @mcamirault in #21596
  - [PM-40060] Split shared unlock setting into desktop and web by @quexten in #21704
  - [PM-35796] Use SDK bindings for invite link generation by @BTreston in #21004
  - [PM-40074] Refactor policy definitions to remove deprecated versions and streamline components by @JaredScar in #21717
  - [PM-37964] Add Ability to Disable Automatic Invitations in SCIM by @sven-bitwarden in #21756
  - [CL-1001] adding new toggle group styles by @BryanCunningham in #20403
  - feat: add Region.Gov to available environments by @addisonbeck in #21211
  - [PM-40126] Update organizationusernotificationpolicy for policy drawer by @jengstrom-bw in #21747
  - [PM-38387] Introduce KeePass KDBX importer by @harr1424 in #21052
  - Finalize Manage Send policy description by @mcamirault in #21786
  - feat(platform): introduce GovModeService for FedRAMP region gating by @addisonbeck in #21366
  - [CL-1274] Add bit-page layout region for bit-layout main content by @willmartian in #21790
  - [PM-37944] Differentiate Send events according to domain by @harr1424 in #20787

  🐛 Bug fixes
  - [PM-25277] SSH Key desktop translations by @nick-livefront in #21208
  - [PM-34926] Allow single-character CJK vault searches by @jaasen-livefront in #21013
  - [PM-35212] - allow bulk archive/unarchive of items in a collection by @jaasen-livefront in #20920
  - [PM-37752] - fix collections control when extension loses focus by @jaasen-livefront in #20812
  - [PM- 38988] Fix Trial Dialog Dismissal Caching by @sbrown-livefront in #21240
  - [PM-38830] fix: Display fixed-amount and repeating churn discounts by @amorask-bitwarden in #21281
  - [PM-38275] Fix at-risk application count in Access Intelligence v2 drawer by @Banrion in #21265
  - [PM-38286] Fix Access Intelligence at-risk drawer can reopen by @Banrion in #21314
  - [PM-32445] Extension Scrollbar Fix by @rr-bw in #20478
  - [PM-39206] use block input to ensure radios are displayed stacked by @BryanCunningham in #21361
  - Auth/PM-35783 - Fix Org Invite Policy State Pollution and State Clearing Issue by @JaredSnider-Bitwarden in #21218
  - [PM-39200] - fix notification bar behavior with save and fill by @jaasen-livefront in #21351
  - [PM-38409] - update custom field value on reorder by @jaasen-livefront in #21137
ReleaseNotesUrl: https://github.com/bitwarden/clients/releases/tag/desktop-v2026.7.0
PurchaseUrl: https://bitwarden.com/pricing/business/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
