# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Threebit.OutaStory
PackageVersion: 1.9.16.222
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: io.threebit.outastory_x1n4bg2pjdgww
Installers:
- Architecture: x64
  InstallerUrl: https://download.outastory.com/windows/1.9.16/OutaStory-1.9.16.msixbundle
  InstallerSha256: 14963D1ABE1CE9C297C98F776982851E1A7B50F336A2E29EB66B4A114529E6D3
  SignatureSha256: 3D5B02ADADAB29289F0A51668357CF2C664EC4DF1F1AC123E99F121D41A81ECD
- Architecture: arm64
  InstallerUrl: https://download.outastory.com/windows/1.9.16/OutaStory-1.9.16.msixbundle
  InstallerSha256: 14963D1ABE1CE9C297C98F776982851E1A7B50F336A2E29EB66B4A114529E6D3
  SignatureSha256: 3D5B02ADADAB29289F0A51668357CF2C664EC4DF1F1AC123E99F121D41A81ECD
ManifestType: installer
ManifestVersion: 1.12.0
