# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SmokeTurner.Vouch
PackageVersion: 2026.6.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: vouch.exe
  PortableCommandAlias: vouch
ReleaseDate: 2026-06-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vouch-sh/vouch/releases/download/v2026.6.1/vouch-v2026.6.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: FE937E5F0663EA2D3D6AD3A23F0866B2367520EDB58A39F5BCF363BB389320CB
- Architecture: arm64
  InstallerUrl: https://github.com/vouch-sh/vouch/releases/download/v2026.6.1/vouch-v2026.6.1-aarch64-pc-windows-msvc.zip
  InstallerSha256: 02B046A5C06EFF51495063E41D9E791187EDE2A8F951A3DACF36707EF0CF991D
ManifestType: installer
ManifestVersion: 1.12.0
