# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: rhshourav.Hydracast
PackageVersion: 6.5.0
PackageLocale: en-US
Publisher: rhshourav
PublisherUrl: https://github.com/rhshourav
PublisherSupportUrl: https://github.com/rhshourav/HydraCast/issues
PrivacyUrl: https://github.com/rhshourav/HydraCast/blob/main/LICENSE
Author: rhshourav
PackageName: HydraCast
PackageUrl: https://github.com/rhshourav/HydraCast
License: HYDRACAST SOFTWARE LICENSE
LicenseUrl: https://github.com/rhshourav/HydraCast/blob/main/LICENSE
Copyright: https://github.com/rhshourav/HydraCast/blob/main/LICENSE
ShortDescription: RTSP live streaming scheduler for local media — web UI included.
Description: HydraCast is a lightweight Python application that turns your media files into continuous 24/7 live RTSP and HLS broadcast streams. It manages multiple FFmpeg processes, integrates with MediaMTX for stream serving, and exposes a full-featured Web Dashboard for remote control.
Moniker: hydracast
Tags:
- rtsp
- stream
- mediamtx
ReleaseNotes: v6.5.0
ReleaseNotesUrl: https://github.com/rhshourav/HydraCast/releases/tag/v6.5.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/rhshourav/HydraCast/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
