# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: binaricat.Netcatty
PackageVersion: 1.0.72
PackageLocale: en-US
Publisher: binaricat
PublisherUrl: https://github.com/binaricat
PublisherSupportUrl: https://github.com/binaricat/Netcatty/issues
PackageName: Netcatty
PackageUrl: https://github.com/binaricat/Netcatty
License: GPL-3.0
LicenseUrl: https://github.com/binaricat/Netcatty/blob/HEAD/LICENSE
Copyright: Copyright © 2026 binaricat
ShortDescription: Netcatty is a modern SSH manager and terminal app with host grouping, SFTP, keychain, port forwarding, and a rich UI.
Tags:
- electron
- electron-app
- radix-ui
- react
- sftp-client
- ssh
- ssh-client
- terminal
- terminal-emulator
- xterm
ReleaseNotes: |-
  Download based on your OS:
  ───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  OS     │Download
  ───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Windows│Setup x64 Setup arm64
  ───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  macOS  │DMG Apple Silicon DMG Intel X64
  ───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Linux  │AppImage x64 DebPackage x64 RpmPackage x64
         │AppImage arm64 DebPackage arm64 RpmPackage arm64
  ───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  What's Changed
  - fix: use system browser for OAuth flows (#563) by @binaricat in #565
  - fix: prevent key file path from overflowing panel (#551) by @binaricat in #567
  - perf: optimize same-host SFTP transfer with remote cp command by @binaricat in #564
  Full Changelog: v1.0.71...v1.0.72
ReleaseNotesUrl: https://github.com/binaricat/Netcatty/releases/tag/v1.0.72
ManifestType: defaultLocale
ManifestVersion: 1.12.0
