# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.hu
PackageVersion: 140.10.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2026-04-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.10.0esr/win32/hu/Firefox%20Setup%20140.10.0esr.exe
  InstallerSha256: 87B2D0BFCBC3C074E2CBA4EF3F5B52627468C9FA9375BE0CB8579EDE2557E65A
  ProductCode: Mozilla Firefox 140.10.0 ESR (x86 hu)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.10.0esr/win64/hu/Firefox%20Setup%20140.10.0esr.exe
  InstallerSha256: 9958F871FB267FE36578ADE35B14E2EBDD920D82B687211AA8F06812C051697D
  ProductCode: Mozilla Firefox 140.10.0 ESR (x64 hu)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.10.0esr/win64-aarch64/hu/Firefox%20Setup%20140.10.0esr.exe
  InstallerSha256: D48C01CBD3DB5D0AD65DECF040E82ED9DCCABEF2656BD469E8229B6632EDA196
  ProductCode: Mozilla Firefox 140.10.0 ESR (arm64 hu)
ManifestType: installer
ManifestVersion: 1.12.0
