# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: OpenTubeX.OpenTubeX
PackageVersion: 0.29.0
PackageLocale: en-US
Publisher: OpenTubeX contributors
PublisherUrl: https://github.com/OpenTubeX
PublisherSupportUrl: https://github.com/OpenTubeX/OpenTubeX/issues
Author: OpenTubeX contributors
PackageName: OpenTubeX
PackageUrl: https://opentubex.org/
License: AGPL-3.0
LicenseUrl: https://github.com/OpenTubeX/OpenTubeX/blob/HEAD/LICENSE
Copyright: Copyleft © 2020-2026
CopyrightUrl: https://github.com/OpenTubeX/OpenTubeX/blob/HEAD/LICENSE
ShortDescription: A private YouTube client
Description: OpenTubeX is a private YouTube client for desktop.
Moniker: opentubex
Tags:
- freetube
- freetube-fork
- privacy
- subscriptions
- video
- videos
- youtube
ReleaseNotes: |-
  - Added support for downloading videos via yt-dlp (#37)
  - The internals of the tab system were reworked. Creating and switching between tabs is a lot smoother now. One downside: Tab previews can no longer be captured of background tabs
  - New full-screen docks for comments, playlists and chapters
  - Keyboard shortcuts can now be customized
  - Experimental fix that allows rewinding live streams/premieres (#163)
  - Added an option to remember the history across restarts (#135)
  - The SponsorBlock icon under the player now opens a side panel with the segments, the skip toggle and a new option to whitelist channels
  - Auto PiP can now be set when minimizing or switching windows
  - Options for showing indicators of newly fetched content and a separate new feed
  - Improved comments appearance and now they render nested reply threads
  - Updated autoplay to show the next video with the countdown on the player
  - Chapters are now displayed in the sidebar instead of overlapping the video
  - Added a button to switch between horizontal and vertical tabs
  - Added a bunch of animations throughout the UI
  - You can now force disable/enable animations without changing your system settings
  - Skipping to a SponsorBlock highlight now produces a notification allowing you to undo it (#252)
  - Premieres are now displayed as premiere instead of just showing the live indicator
    otx-premiere-metadata
  - While watching a video you can now make the card that displays the playlist taller/shorter (#256)
  - Subscriptions auto-refresh timers are now persistent. Example: When you close the app with 5 minutes remaining and open the app again 4 minutes later it's at 1 minute remaining
  - Added a visual indicator for the auto-refresh
  - The subscription feed items are now kept visible while refreshing
  - You can now click on a chatter's handle to open their channel from the live chat
  - Allow playlist remove actions while playback (#249)
  - Mark as watched and remove from history are now two separate actions on videos (#222)
  - Add option to move the profile selector to the channels list (#246)
  - When a SABR stream encounters a playback error it is now reloaded instead of falling back to legacy formats (max 360p)
  - Fixed a bug where a SABR reload would keep the current tab's video on the timestamp where it occurred
  - Improved the reliability of the fast-forward silence feature
  - Restore the replay icon when the video ended
  - Tabs with channels that don't have a preview yet now fall back to the avatar
  - Show when comments are edited
  - Fixed the position and size of elements in the end screen annotations
  - Fixed a bug where scrolling one subscription feed affected the scroll position in the other feeds
  - Fix vertical position of texts and elements with certain Unicode characters (#239)
ReleaseNotesUrl: https://github.com/OpenTubeX/OpenTubeX/releases/tag/v0.29.0-beta
ManifestType: defaultLocale
ManifestVersion: 1.12.0
