# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ManicTime.ManicTime
PackageVersion: 26.2.0.3
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ManicTime.exe
  InstallerUrl: https://cdn.manictime.com/setup/v2026_2_0_3/manictime-portable-2026.2.0.3-win-x86.zip
  InstallerSha256: 5DF85AC2BFA34A5C71FAC1529D16445CF30A53B983450453872FE758329A3C4D
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ManicTime.exe
  InstallerUrl: https://cdn.manictime.com/setup/v2026_2_0_3/manictime-portable-2026.2.0.3-win-x64.zip
  InstallerSha256: 9F7B104DE3A8D0BEDB9631E34C44E426C6F8B0393A526EB2D90BA83678679832
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  Scope: user
  InstallerUrl: https://cdn.manictime.com/setup/v2026_2_0_3/manictime-setup-2026.2.0.3-win-x86.msi
  InstallerSha256: 33073AB21B39A05DE2D8F7F15AE4B7220A02D7B4F827A351D318680B4BB544B9
  ProductCode: '{050FF232-4530-4A2D-92A2-0B5AE133D544}'
  AppsAndFeaturesEntries:
  - ProductCode: '{050FF232-4530-4A2D-92A2-0B5AE133D544}'
    UpgradeCode: '{EDF2F2D1-1851-4424-8682-9B52D765B0E8}'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\ManicTime'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: user
  InstallerUrl: https://cdn.manictime.com/setup/v2026_2_0_3/manictime-setup-2026.2.0.3-win-x64.msi
  InstallerSha256: 0AC03377DAF90171685A177C362DB7EEDF5966472F9515E3562A2DE98B384BB1
  ProductCode: '{D4E4DADA-A289-47A6-A8DB-360A4CD93935}'
  AppsAndFeaturesEntries:
  - ProductCode: '{D4E4DADA-A289-47A6-A8DB-360A4CD93935}'
    UpgradeCode: '{EDF2F2D1-1851-4424-8682-9B52D765B0E8}'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\ManicTime'
ManifestType: installer
ManifestVersion: 1.12.0
