# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Profullstack.PairUX
PackageVersion: 0.9.59
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/profullstack/pairux.com/releases/download/v0.9.59/PairUX.Setup.0.9.59.exe
    InstallerSha256: 134CEA720D6483244D39BA196B0CD4CB5ACDBC8CCA80FB6EA9EF38FA97510B94
ManifestType: installer
ManifestVersion: 1.10.0
