# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: SFXTechInnovation.SimpleFixAI
PackageVersion: 1.7.47
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-08-27
Installers:
  - Architecture: x64
    InstallerUrl: https://updates.simplefixai.com/SimpleFixAI_1.7.47_x64-setup.exe
    InstallerSha256: D5A0DBA840AFFF97C577D22451E1E639A6073206E5C117106C75B4A0702C2482
    AppsAndFeaturesEntries:
      - DisplayName: SimpleFixAI
        Publisher: SFX Tech Innovation LLC
        ProductCode: SimpleFixAI
ManifestType: installer
ManifestVersion: 1.12.0
