# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: itsnateai.MWBToggle
PackageVersion: 2.5.12
InstallerType: portable
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/itsnateai/MousewithoutBordersToggle/releases/download/v2.5.12/MWBToggle.exe
  InstallerSha256: 60A90EB1C762ED8575EFBA437C8329E5AC02FDCA1603712BB976BF29C7A0A50F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-04-24
