# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MichaelTippach.ASIO4ALL
PackageVersion: "2.20"
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: ASIO4ALL
Installers:
- Architecture: x86
  InstallerUrl: https://asio4all.org/downloads/ASIO4ALL_2_20.exe
  InstallerSha256: 67E47DB6BFEBB49EF84EA34E07EB391F42E0BFFCFCBE09F8D7FC2BC3BA52E7FE
- Architecture: x64
  InstallerUrl: https://asio4all.org/downloads/ASIO4ALL_2_20.exe
  InstallerSha256: 67E47DB6BFEBB49EF84EA34E07EB391F42E0BFFCFCBE09F8D7FC2BC3BA52E7FE
ManifestType: installer
ManifestVersion: 1.12.0
