# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 146.1.90.21
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser-Nightly
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 58D07171B7F65590E8438912BFB25C5F2C297A04BA24F8BF6D455D259E24EF94
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 59E23CDE3404B805F4B97F41D7B228292ECC829AC168DCE41288694ECC2C2B2A
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 146DCD6085C402C65802A9D50D6D1C56ABE026766E2793905C17BC47DBED665A
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 3E651A7408BD1686959DB89EC6450718170D4F860A9EA6C1CD954FD8C115C42C
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: FC6B7BF7B95F9F60AD1A2EBDDADBDE99AF6CBFD302C5A0B5DB104ECBDA45B59D
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.21/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 665DC99C1BA7875095A2DC3ED91D813836F0D377DD1DA95132D64649386A36D0
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
