# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: D2L.BMX
PackageVersion: 3.2.1
PackageLocale: en-US
Publisher: D2L
PublisherUrl: https://github.com/Brightspace
PublisherSupportUrl: https://github.com/Brightspace/bmx/issues
PackageName: BMX
PackageUrl: https://github.com/Brightspace/bmx
License: Apache-2.0
LicenseUrl: https://github.com/Brightspace/bmx/blob/HEAD/LICENSE
ShortDescription: BMX provides API access to your AWS accounts using existing Okta credentials.
Tags:
- aws
- iam
- okta
- vulcan
ReleaseNotes: |-
  What's Changed
  - add passwordless auth section to README by @cfbao in #496
  - Use spectre.console lib to manage ANSI escape code by @AnimalXing in #497
  - move versioning logic into csproj & simplify build commands by @cfbao in #498
  - write all informational messages to stderr by @cfbao in #499
  - add more debug logs for passwordless auth by @cfbao in #500
  - longer timeout for first page load during passwordless auth by @cfbao in #501
  - build for Linux ARM64 in CI by @cfbao in #502
  - add back Version environment variable in CI by @cfbao in #503
  - Remove PR size labeler workflow (unused) by @boarnoah in #504
  - add winget manifest and updating doc by @gord5500 in #505
  - use new SLNX format by @boarnoah in #506
  - Add AWS_PROFILE env var to readme by @eKoopmans in #507
  - update puppeteersharp by @gord5500 in #510
  New Contributors
  - @AnimalXing made their first contribution in #497
  - @eKoopmans made their first contribution in #507
  Full Changelog: v3.2.0...v3.2.1
ReleaseNotesUrl: https://github.com/Brightspace/bmx/releases/tag/v3.2.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
