# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.VisualStudioCode.Insiders
PackageVersion: 1.115.0
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
Commands:
- code-insiders
Installers:
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/insider/8c85df126b92b742f00c4d2107f6be50ec8298ac/VSCodeSetup-arm64-1.115.0-insider.exe
  InstallerSha256: 3B91FF9F1001521AD6139B55B8645EFE4F68992A8995F5F07EA7EFE3CBF12597
- Architecture: arm64
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/insider/8c85df126b92b742f00c4d2107f6be50ec8298ac/VSCodeUserSetup-arm64-1.115.0-insider.exe
  InstallerSha256: F0A7C0F3B1AE3EA06FEA0C257D87E09D96601CF1EC619101ECBABB8C0263BD79
- Architecture: x64
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/insider/8c85df126b92b742f00c4d2107f6be50ec8298ac/VSCodeSetup-x64-1.115.0-insider.exe
  InstallerSha256: 8778CB5861A449AE50A63869A2F70EDA6E5C561983EB9E62677AFCA42FD2D03E
- Architecture: x64
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/insider/8c85df126b92b742f00c4d2107f6be50ec8298ac/VSCodeUserSetup-x64-1.115.0-insider.exe
  InstallerSha256: 7597CB98AB25DACF5589CBABFD40CBF3D71E2C7920F4062672DD52E32937ED1D
ManifestType: installer
ManifestVersion: 1.12.0
