# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Learneo.LanguageTool
PackageVersion: 1.6.2.0
Platform:
- Windows.Desktop
- Windows.Universal
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
Protocols:
- languagetool
PackageFamilyName: 2059LanguageToolerGmbH.5380069E15F3D_1brdv1ch1ayj6
Capabilities:
- internetClient
- packageManagement
- runFullTrust
Installers:
- Architecture: x64
  InstallerUrl: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_1.6.2.0/Languagetool.Packaging_1.6.2.0_x64.msixbundle
  InstallerSha256: F0D3D433C89CFC6444101645E1D4A9BBC92F5686E41C5A235CA2ABE41E8582BB
  SignatureSha256: 4BF33104C03A4EC3D26E3ECA62C12475AF947CAE2DE3EA980D9599B6A772786C
ManifestType: installer
ManifestVersion: 1.12.0
