# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 152.1.96.2
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-08-20
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: B29F41A954EE7C560135761EFFD5D154934D63577A4D59D8DD8CECCB34278530
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 430D3692663B0D43EE5E931E768784759D285778E0E13225B45F00CFE05056DE
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: F5DEF37F7D7F8E638D8F149B1529FAEC8F1F1D963380171CFCAE06EBB7FC09B0
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 16684CD34E7ED943E9F42F4F9CEFC9CAFC6D357D075CA3FEAC332EAC162C32DC
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: BD9BBFD08F83AC49AA26FA1912A53AD5657791B7D17F399DEFAC526230F53A92
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.96.2/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 6381963D7285DA4A20092FC0BB256AB6FDDC96EC6226AF9526BB6222F5475A7A
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
