# Created by Anthelion using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Oracle.OCI-CLI
PackageVersion: 3.76.0
InstallerType: msi
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- oci
ProductCode: '{C424979F-16E9-4914-9447-37DDD70625A0}'
ReleaseDate: 2026-03-11
AppsAndFeaturesEntries:
- DisplayName: oci-cli
  Publisher: Oracle
  ProductCode: '{C424979F-16E9-4914-9447-37DDD70625A0}'
  UpgradeCode: '{48B079F4-B598-438D-A62A-8A233A3F8901}'
InstallationMetadata:
  DefaultInstallLocation: Lib
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/oracle/oci-cli/releases/download/v3.76.0/oci-cli-3.76.0-Windows-Server-Installer.msi
  InstallerSha256: C33F5DA8ED16AE5E53E8DB443BFA012F240E2DC2A423062DDF649669407100DD
ManifestType: installer
ManifestVersion: 1.12.0
