# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Bitvise.SSH.Server
PackageVersion: "9.66"
PackageLocale: en-US
Publisher: Bitvise Limited
PublisherUrl: https://bitvise.com/
PublisherSupportUrl: https://bitvise.com/contact
PrivacyUrl: https://bitvise.com/privacy-policy
Author: Bitvise Limited
PackageName: Bitvise SSH Server
PackageUrl: https://bitvise.com/ssh-server
License: Proprietary
LicenseUrl: https://bitvise.com/ssh-server-license
Copyright: Copyright (C) 2000-2026 by Bitvise Limited.
CopyrightUrl: https://bitvise.com/terms-of-use
ShortDescription: Secure file transfer and terminal shell access for Windows
Description: |-
  Our SSH server supports all desktop and server versions of Windows, 32-bit and 64-bit, from Windows XP SP3 and Windows Server 2003, up to the most recent – Windows 11 and Windows Server 2025.
  Bitvise SSH Server includes the following:
  - SFTP server: Secure file transfer using SFTP - compatible with a wide variety of clients
  - SCP server: Secure file transfer using SCP - compatible with command line and graphical clients
  - FTPS server: Secure file transfer using FTP over TLS/SSL - compatible with secure FTPS clients
  - SSH server: Secure remote access via console - vt100, xterm and bvterm are supported
  - Secure remote access via GUI - Remote Desktop or WinVNC required
  - Secure, effortless Git integration
  - Secure TCP/IP connection tunneling (port forwarding)
Moniker: bitvisesshserver
Tags:
- sftp
- ssh
- sshd
Agreements:
- AgreementLabel: End User License Agreement (EULA)
  AgreementUrl: https://bitvise.com/ssh-server-license
ReleaseNotes: |-
  - Release notes:
    - We are anticipating an "information security armageddon" due to increasing ability of AI to find security issues, in all software and systems, which were not found in human testing and code review.
      The quality of commercially available AI tools has improved to where they are now indispensable for software correctness. We are applying AI tools proactively to find and fix flaws which previously missed detection.
      Users will observe this as an increased frequency of significant and important updates. We believe the time to do this is now, before exploitation becomes too easy.
  - Control Panel and Settings:
    - Advanced settings and its windows now open much faster.
      Recent Windows versions have become painfully slow to open settings, compared to older Windows versions. We implemented optimizations to restore and improve performance.
    - Improved interactive diagnostics for connections that fail due to SSH algorithm mismatches.
  - SSH:
    - Improved multiple avenues which an authenticated client could use to exert disproportionate memory pressure on the server.
    - The SSH Server now accepts the client's SSH_MSG_EXT_INFO if the client sends it incorrectly as the next packet after SSH_MSG_SERVICE_REQUEST. Correct client implementations must send this packet after SSH_MSG_NEWKEYS. If the packet is sent late, not all extensions are supported.
      If the SSH_MSG_EXT_INFO packet is received even later, this still causes an SSH protocol disconnect.
ReleaseNotesUrl: https://www.bitvise.com/ssh-server-version-history-9-5#966
PurchaseUrl: https://bitvise.com/ssh-server-pricing
Documentations:
- DocumentLabel: Printable Documentation
  DocumentUrl: https://bitvise.com/printable-docs/ssh-server-doc-printable
- DocumentLabel: Users' Guide
  DocumentUrl: https://bitvise.com/ssh-server-users-guide
- DocumentLabel: FAQ
  DocumentUrl: https://bitvise.com/ssh-server-usage-faq
ManifestType: defaultLocale
ManifestVersion: 1.12.0
