# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Dystroy.broot
PackageVersion: 1.60.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: x86_64-pc-windows-gnu/broot.exe
ReleaseDate: 2026-09-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Canop/broot/releases/download/v1.60.1/broot_1.60.1.zip
  InstallerSha256: DE4A054424AC01EF73FB30C3B3FAC0CDA437E7426388085D7467B5E0AAA1CB55
ManifestType: installer
ManifestVersion: 1.12.0
