# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: MarcoDAmato.WinContig
PackageVersion: 5.0.3.3
PackageLocale: en-US
Publisher: MarcoDAmato
PackageName: WinContig
License: Proprietary
ShortDescription: Portable Defragmentation Tool for files and folders.
Description: >
  WinContig is an easy-to-use stand-alone defragmentation tool that does not create any installation
  directories or registry entries on your computer. Its purpose is to quickly defragment individual
  files without the need to defragment the entire disk. WinContig supports FAT32 and NTFS file
  systems, and works with both hard disks and SSDs.
ReleaseNotes: |-
  - If one or more filter criteria are set, the filter icon may fail to display the expected small
    green notification dot on the toolbar. Fixed.
  - If WinContig is run from the command-line with the '/close', '/closeifok' or '/nogui' parameters
    specified, the 'Critical Stop' sound notification is played upon exit. Fixed. Thanks to MacMacMac
    for reporting this.
  - Even when the settings have been configured to take no action when a computer is running on
    battery power, WinContig stops processing files when a computer is running on battery power.
    Fixed.
  - The execution speed of some operations has been improved.
ReleaseNotesUrl: https://www.mdtzone.it/sw/wincontig/en/history.html
ManifestType: defaultLocale
ManifestVersion: 1.12.0
