# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.fr
PackageVersion: 153.2.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox ESR
ReleaseDate: 2026-09-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.2.0esr/win32/fr/Firefox%20Setup%20153.2.0esr.exe
  InstallerSha256: 0EB0FA883D83B98B724C9CF663EC83DE7C357F8191BEC4B071A6A9A2349A19CB
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.2.0esr/win64/fr/Firefox%20Setup%20153.2.0esr.exe
  InstallerSha256: 00D85F1CB44E64661D1217D4FF9DC4BE8461EA1531C4E38DAA1CE1BD69068D13
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/153.2.0esr/win64-aarch64/fr/Firefox%20Setup%20153.2.0esr.exe
  InstallerSha256: 496B7E7185826C36112CB1F98CECD4D27DE7F7CD495E62E5809B1F42D3D5C277
ManifestType: installer
ManifestVersion: 1.12.0
