# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: evilmartians.lefthook
PackageVersion: 2.1.11
InstallerType: portable
UpgradeBehavior: install
Commands:
- lefthook
ReleaseDate: 2026-08-21
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.11/lefthook_2.1.11_Windows_i386.exe
  InstallerSha256: E3A6C29C6EAC018D7B828B82EDAE29CDE8B7D6045054E9B02B687F086C4BEF5D
- Architecture: x64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.11/lefthook_2.1.11_Windows_x86_64.exe
  InstallerSha256: A3D506B8D4BC421C22A0FE1E1E0C373E9BB7D413EDCAE3237A3518C7B78A2F5A
- Architecture: arm64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.11/lefthook_2.1.11_Windows_arm64.exe
  InstallerSha256: 7333EF649FCC41EE3140FFE2E8479C21BFCD9DF2A69DF0A9905A5FCF86166C7B
ManifestType: installer
ManifestVersion: 1.12.0
