# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: InferenceHub.InferenceHub
PackageVersion: 0.2.20
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: InferenceHub
ReleaseDate: 2026-08-03
AppsAndFeaturesEntries:
- Publisher: inferencehub
  ProductCode: InferenceHub
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\InferenceHub'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/InferenceHub/inferencehub-desktop/releases/download/v0.2.20/InferenceHub_0.2.20_x64-setup.exe
  InstallerSha256: CA4902F8579A337BFB96E431F1D454943A921D4BFB13CD1A1F1C5CD1EFF9CE98
ManifestType: installer
ManifestVersion: 1.12.0
