# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TKEngineering.CANtrace
PackageVersion: 4.5.0
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: Stable\CANtrace-setup-4.5.exe
Installers:
- Architecture: x86
  InstallerUrl: https://tke.fi/wp-content/uploads/2026/04/CANtrace-4.5.zip
  InstallerSha256: 13C7F2326773676E8042B7FFC54CE86FDF57F9CB591C7A3F25A931038A13CE09
  AppsAndFeaturesEntries:
  - DisplayVersion: "4.5"
    ProductCode: '{554F0F6B-A644-43E9-907C-BD01C5C3986C}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
