# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: dagaza.Qube.Vulkan
PackageVersion: 1.3.44
InstallerType: inno
Dependencies:
  PackageDependencies:
  - PackageIdentifier: KhronosGroup.VulkanRT
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dagaza/Qube/releases/download/v1.3.44/Qube-1.3.44-vulkan-Setup.exe
  InstallerSha256: 7A65D9D18FB84205F94FABDA989F4EFB838291203739E36742E8B50C4D01E44E
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.6.0
