# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Chyckenwing.Chickenwing
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: chickenwing-windows-x64-v0.1.0\chickenwing.exe
  PortableCommandAlias: chickenwing
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/chyckenwing/chickenwing/releases/download/v0.1.0/chickenwing-windows-x64-v0.1.0.zip
  InstallerSha256: 826310E7D363CAEED80C0933292DDE63D9935C93FA2A86B5BDB7877CE7084B0D
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-04-29
