# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: NuvioMedia.Nuvio
PackageVersion: 0.1.1 alpha
PackageLocale: en-US
Publisher: Nuvio Media
PackageName: Nuvio
License: GPL-3.0
ShortDescription: Nuvio Desktop is a media client for browsing metadata, managing collections and watch progress, downloading media, and playing streams from user-installed extensions or user-provided sources.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
