# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WinBooster.Cross_Cleaner_GUI
PackageVersion: 2.0.2.5
InstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2026-09-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/WinBooster/Cross-Cleaner/releases/download/v2.0.2.5/Windows-Cross_Cleaner_GUI.exe
  InstallerSha256: 0E9D738E42299EFC2BC250B5CCFF8D17A4DE5F6BD29F34BB1081178BC1F6FFA2
ManifestType: installer
ManifestVersion: 1.12.0
