# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Pulumi.Pulumi
PackageVersion: 3.234.0
MinimumOSVersion: 10.0.0.0
InstallerType: wix
ProductCode: '{73E3C220-99B5-41F6-8C00-DE0D24D6F9EE}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pulumi/pulumi-winget/releases/download/v3.234.0/pulumi-3.234.0-windows-x64.msi
  InstallerSha256: 96FC2378D3851CB338B2CDD29D584095CE17AE10A164373F30E9C78403B76FEC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-01
