# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EligianLabs.PIICrawlerCLI
PackageVersion: 26.0904.0431
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: piicrawler.exe
Commands:
- piicrawler
ReleaseDate: 2026-09-04
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.eligian.com/piicrawler-cli-windows-signed.zip
  InstallerSha256: C3A3907779E3C9CB8868E90F01C5E2F640D506A68A8F2B4C0EA728B8820F16BD
ManifestType: installer
ManifestVersion: 1.12.0
