# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: JanPereiraDev.QuantumLog
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: qlog.exe
    PortableCommandAlias: qlog
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/janpereira-dev/quantum_log/releases/download/v0.1.0/qlog_0.1.0_windows_amd64.zip
    InstallerSha256: fe408003b65a933f825f4d1e862daa177435ec07ea8a534d8800f2afb4af528f
  - Architecture: arm64
    InstallerUrl: https://github.com/janpereira-dev/quantum_log/releases/download/v0.1.0/qlog_0.1.0_windows_arm64.zip
    InstallerSha256: cbed08f3eb61467baf4d0da9b8ec80c4c7f6906597f09e86a78e9f4b466e4a02
ManifestType: installer
ManifestVersion: 1.10.0
