# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: vantoan1511.TableView
PackageVersion: 0.4.5
InstallerType: inno
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /NORESTART
UpgradeBehavior: install
ProductCode: '{D1A8F9B2-3C4D-5E6F-7A8B-9C0D1E2F3A4B}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vantoan1511/table-view/releases/download/v0.4.5/setup.exe
  InstallerSha256: D351DE90FCC71907D7C3E9D9F2BE9679200DCE27D6C656C079E44BBE793905F8
ManifestType: installer
ManifestVersion: 1.6.0
