# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Coder.CoderDesktop
PackageVersion: 0.8.3
InstallerType: burn
Scope: machine
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Coder Desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/coder/coder-desktop-windows/releases/download/v0.8.3/CoderDesktop-0.8.3-x64.exe
  InstallerSha256: E2D3A68E09318F8CD46615829DE333BCF048A6B8E278E0B3071F3E55280603A1
  AppsAndFeaturesEntries:
  - DisplayName: Coder Desktop
    ProductCode: '{90CEFACA-BA0B-4399-BBA6-B8A9043440F8}'
    UpgradeCode: '{8A773CF1-029C-4BA8-A3F8-DDA90F9E641B}'
    InstallerType: burn
- Architecture: arm64
  InstallerUrl: https://github.com/coder/coder-desktop-windows/releases/download/v0.8.3/CoderDesktop-0.8.3-arm64.exe
  InstallerSha256: DF9D4138870F3A5F5F1CC03B68575EA4539B55832F4DE91E53F6D72EDFBA02F9
  AppsAndFeaturesEntries:
  - DisplayName: Coder Desktop
    ProductCode: '{6D25D6B3-8B4F-4F59-AB52-695088174DCA}'
    UpgradeCode: '{8A773CF1-029C-4BA8-A3F8-DDA90F9E641B}'
    InstallerType: burn
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-12
