PackageIdentifier: PLCMind.PLCMind
PackageVersion: 0.9.28.0
InstallerType: burn
Installers:
  - Architecture: x64
    InstallerUrl: https://plcmind.com/downloads/PLCMindSetup-0.9.28.0.exe
    InstallerSha256: 4D4C99D985E291F16654DA234C5535AFD1D3FD62142773E22EBA183C9E0A628D
    InstallerSwitches:
      Silent: -quiet -norestart
      SilentWithProgress: -passive -norestart
      Interactive: -norestart
    UpgradeBehavior: uninstallPrevious
    AppsAndFeaturesEntries:
      - DisplayName: PLCMind
        Publisher: Taiyuan Xiaodian Dist. Code-All-Open Software Development Studio
        DisplayVersion: 0.9.28.0
ManifestType: installer
ManifestVersion: 1.6.0
