# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AList.AListDesktop
PackageVersion: 3.58.0
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ReleaseDate: 2026-03-17
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/AlistGo/desktop-release/releases/download/v3.58.0/alist-desktop_3.58.0_x64-setup.exe
  InstallerSha256: A5A4A5DC2099B6E68CECF8CF76F3507F9D34D882078744C1C3F3C32306CC57F1
  ProductCode: alist-desktop
- Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/AlistGo/desktop-release/releases/download/v3.58.0/alist-desktop_3.58.0_arm64-setup.exe
  InstallerSha256: 510183A55087C566AC3910902827DD1A6859CA0F5A926E47753691B470552903
  ProductCode: alist-desktop
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/AlistGo/desktop-release/releases/download/v3.58.0/alist-desktop_3.58.0_x64_en-US.msi
  InstallerSha256: 6B00A6485B6ECE602C3D7D625A6B09422DE6C16AF1A5E27C57F75B44D029E8C5
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{0EB21571-AD08-42E4-8181-5CA50844CAC3}'
  AppsAndFeaturesEntries:
  - ProductCode: '{0EB21571-AD08-42E4-8181-5CA50844CAC3}'
    UpgradeCode: '{35D0EA96-CF42-529B-9122-220745E50D7A}'
ManifestType: installer
ManifestVersion: 1.12.0
