# Created with komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: hrzlgnm.mdns-tui-browser
PackageVersion: v1.26.1
PackageLocale: en-US
Publisher: hrzlgnm
PublisherUrl: https://github.com/hrzlgnm
PublisherSupportUrl: https://github.com/hrzlgnm/mdns-tui-browser/issues
Author: hrzlgnm
PackageName: mDNS TUI Browser
PackageUrl: https://github.com/hrzlgnm/mdns-tui-browser
License: MIT
LicenseUrl: https://github.com/hrzlgnm/mdns-tui-browser/blob/HEAD/LICENSE
Copyright: Copyright (c) hrzlgnm
CopyrightUrl: https://raw.githubusercontent.com/hrzlgnm/mdns-tui-browser/refs/heads/main/LICENSE
ShortDescription: Cross platform TUI mdns-browser written in rust, vibe coded with opencode free model
Tags:
- mdns-sd
- ratatui
- rust
- terminal-ui
ReleaseNotes: |-
  What's Changed
  ✨ New Features
  - feat: add flapping filter keyword @hrzlgnm #255
  🧰 Maintenance
  - chore: cached install komac and cargo-edit using cargo-install @hrzlgnm #247
  - chore: pass winget token via env to komac @hrzlgnm #249
  - chore: cache-tools job after build @hrzlgnm #251
  - chore: run lint and tests before cache-tools @hrzlgnm #252
  - chore: cache cargo-auditable in cache-tools workflow too @hrzlgnm #256
  ♻️ Refactor
  - refactor: extract user input handling to dedicated module @hrzlgnm #254
  ⬆️ Dependency Updates
  - chore(deps): update hrzlgnm/actions action to v2.0.3 @renovate[bot] #245
  - chore(deps): update dependency cargo-auditable to v0.7.4 @renovate[bot] #246
  - chore(deps): update hrzlgnm/actions action to v2.0.4 @renovate[bot] #250
  - chore(deps): update release-drafter/release-drafter action to v6.3.0 @renovate[bot] #253
  Full Changelog
  v1.25.1...v1.26.1
ReleaseNotesUrl: https://github.com/hrzlgnm/mdns-tui-browser/releases/tag/v1.26.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
