# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KinichiAnjuMakino.unifocl
PackageVersion: 2.21.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: unifocl.exe
  PortableCommandAlias: unifocl
ReleaseDate: 2026-03-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Kiankinakomochi/unifocl/releases/download/v2.21.3/unifocl-2.21.3-win-x64.zip
  InstallerSha256: 7AEB37D5ED7DACE3FF5051B9B8B2BCA289B4594FB273CF0F6C9B4C8AB3FE7964
ManifestType: installer
ManifestVersion: 1.12.0
