# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: pbek.QOwnNotes
PackageVersion: 26.4.24
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: QOwnNotes.exe
  PortableCommandAlias: qownnotes.exe
ReleaseDate: 2026-04-27
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/pbek/QOwnNotes/releases/download/v26.4.24/QOwnNotes.zip
  InstallerSha256: AFB8475F110242926077540783AC1DE11A2FA53247B85DA2411E82633F3C1FA0
ManifestType: installer
ManifestVersion: 1.12.0
