# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AndreaGrandi.LogBasset
PackageVersion: 0.5.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: logbasset.exe
  PortableCommandAlias: logbasset
UpgradeBehavior: install
Commands:
- logbasset
ReleaseDate: 2026-05-20
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/andreagrandi/logbasset/releases/download/v0.5.0/logbasset_Windows_x86_64.zip
  InstallerSha256: BBA64AD7324D6E122EF676D033FB80C4255A1822F099F18764691BA5F7183B7B
ManifestType: installer
ManifestVersion: 1.12.0
