# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ecosia.EcosiaBrowser
PackageVersion: 147.1.7727.18
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: EcosiaBrowser
ReleaseDate: 2026-04-28
Installers:
- Architecture: x86
  InstallerUrl: https://app-cms-repo.ecosia-browser.net/0aac13df-2a94-4570-8229-285102897d3d/build/147.1.7727.18/mini_installer_147.1.7727.18_x86.exe
  InstallerSha256: 8335C30FB951E2A420C93BDAE6EDF39D8EC5155F1C0B5C3325AC03B8C7861B73
- Architecture: x64
  InstallerUrl: https://app-cms-repo.ecosia-browser.net/0aac13df-2a94-4570-8229-285102897d3d/build/147.1.7727.18/mini_installer_147.1.7727.18_x64.exe
  InstallerSha256: 5B42273DBB5F1B37F49757D0F270BFC12104859892CBA40F6E255F190B8D6BBA
ManifestType: installer
ManifestVersion: 1.12.0
