# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WSDOT.BridgeLink
PackageVersion: 9.0.3
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{A0E7B213-9034-41FD-8F18-41BCCD8DFE18}'
AppsAndFeaturesEntries:
- DisplayName: BridgeLink (x64)
  DisplayVersion: 9.0.3
  ProductCode: '{A0E7B213-9034-41FD-8F18-41BCCD8DFE18}'
  UpgradeCode: '{AE47FAA1-1DB0-48A0-9B82-C99C7120B8C4}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.wsdot.wa.gov/eesc/bridge/software/downloads/BridgeLink_9.0/BridgeLink_9.0.3.msi
  InstallerSha256: 8822BBF6B448628F50BE78A034D32ADA79E2700CD259AB3533484FF4D41CEDEA
ManifestType: installer
ManifestVersion: 1.12.0
