# Created with WinGet Releaser using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Debba.Tabularis
PackageVersion: 0.9.10
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: tabularis
ReleaseDate: 2026-03-18
AppsAndFeaturesEntries:
- Publisher: tabularis
  ProductCode: tabularis
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\tabularis'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/debba/tabularis/releases/download/v0.9.10/tabularis_0.9.10_x64-setup.exe
  InstallerSha256: 0F7ADCF286840D5949730B6BFF469CF0A12BF43BB8851F2CF96AF6E8267870C1
ManifestType: installer
ManifestVersion: 1.12.0
