# Created with komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Lenovo.ServiceBridge
PackageVersion: 5.0.2.19
PackageLocale: zh-CN
License: 专有软件
ShortDescription: Lenovo Service Bridge 可识别您设备的服务标签、分析硬件问题、运行诊断测试并扫描驱动程序更新。
ManifestType: locale
ManifestVersion: 1.12.0
