# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AppiumDevelopers.AppiumInspector
PackageVersion: 2026.5.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
ProductCode: 5335de9f-10e5-5584-90c5-274c050b3ea9
ReleaseDate: 2026-05-04
AppsAndFeaturesEntries:
- DisplayName: Appium Inspector 2026.5.1
  ProductCode: 5335de9f-10e5-5584-90c5-274c050b3ea9
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/appium/appium-inspector/releases/download/v2026.5.1/Appium-Inspector-2026.5.1-win-x64.exe
  InstallerSha256: 8F65E01BD305C10AD54652E1F2D7825790351C733406361B4D30F01421B4E74C
ManifestType: installer
ManifestVersion: 1.12.0
