# Created with WinGet Updater using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: autobrr.mkbrr
PackageVersion: 1.24.1
PackageLocale: en-US
Publisher: autobrr
PublisherUrl: https://github.com/autobrr
PublisherSupportUrl: https://github.com/autobrr/mkbrr/issues
PackageName: mkbrr
PackageUrl: https://github.com/autobrr/mkbrr
License: GPL-2.0
LicenseUrl: https://github.com/autobrr/mkbrr/blob/HEAD/LICENSE
ShortDescription: mkbrr is a tool to create, modify and inspect torrent files. Fast.
Tags:
- bittorrent
- go
- golang
- metafile
- torrent
ReleaseNotes: |-
  Changelog
  Bug fixes
  - f32da2a: fix(torrent): normalize decomposed filenames to NFC (#183) (@s0up4200)
  Other work
  - 786882e: chore(deps): bump the github group with 2 updates (#178) (@dependabot[bot])
  - f3f9c1f: chore(deps): migrate anacrolix/torrent to autobrr/go-torrent (#181) (@zze0s)
  - cc3d21d: chore: bump Go to 1.26 (#180) (@s0up4200)
  Full Changelog: v1.24.0...v1.24.1
ReleaseNotesUrl: https://github.com/autobrr/mkbrr/releases/tag/v1.24.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
