# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Voltius.Voltius
PackageVersion: 0.16.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Voltius
ReleaseDate: 2026-08-04
AppsAndFeaturesEntries:
- Publisher: voltius
  ProductCode: Voltius
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Voltius'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/VoltiusApp/voltius/releases/download/v0.16.0/Voltius_0.16.0_x64-setup.exe
  InstallerSha256: A7AFFFD49C2BF621EC1CDE10B5373A55C6B491214400CE90AE34BC45DA25FE43
- Architecture: arm64
  InstallerUrl: https://github.com/VoltiusApp/voltius/releases/download/v0.16.0/Voltius_0.16.0_arm64-setup.exe
  InstallerSha256: E288502B3096F5CF6C073664E2F9C971514513480C1FBBA26C3D12D6D4C3B453
ManifestType: installer
ManifestVersion: 1.12.0
