# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: llt22.Talkio
PackageVersion: 2.13.3
UpgradeBehavior: install
ReleaseDate: 2026-08-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/llt22/talkio/releases/download/v2.13.3/talkio_2.13.3_x64-setup.exe
  InstallerSha256: 27430EB7972068FDDCD6F5299CFCBDA192A792D3C9A92CEA8EC9C01458F705EC
  ProductCode: talkio
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/llt22/talkio/releases/download/v2.13.3/talkio_2.13.3_x64_en-US.msi
  InstallerSha256: E5699C871B1FB2671E17BD3DC861238C1ED8B1C0E3E89EA0535D63036FADF018
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{C93D17FA-EDA4-4D3C-B9E4-AC945B932AA5}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{C17314AF-495C-5A26-8402-79B3B6FDE728}'
ManifestType: installer
ManifestVersion: 1.12.0
