# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ruben2776.PicView
PackageVersion: 5.1.2
InstallerType: inno
Scope: machine
UpgradeBehavior: install
FileExtensions:
- 3fr
- arw
- bmp
- cr2
- crw
- cut
- dcr
- dds
- dib
- dng
- emf
- erf
- exr
- gif
- hdr
- heic
- ico
- jfif
- jpe
- jpeg
- jpg
- kdc
- mdc
- mef
- mos
- mrw
- nef
- nrw
- orf
- pcx
- pef
- pgm
- png
- psb
- psd
- raf
- raw
- rw2
- srf
- svg
- tga
- tif
- tiff
- wbmp
- webp
- wmf
- wpg
- x3f
- xbm
- xcf
- xpm
ProductCode: '{F102E394-0FA6-4AEA-826D-9FE699115BAB}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ruben2776/PicView/releases/download/5.1.2/Setup-PicView-v5.1.2-win-x64.exe
  InstallerSha256: 4B303D0B4250969253B92D45C28967B8C3E06D16306BB32274C18C25ABD38C58
- Architecture: arm64
  InstallerUrl: https://github.com/Ruben2776/PicView/releases/download/5.1.2/Setup-PicView-v5.1.2-win-arm64.exe
  InstallerSha256: 09886BB45D5AC1DC7F8BC4AD52137DB582E08091382E8D3389FFD7704CB235C2
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-22
