# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nginxinc.nginx
PackageVersion: 1.31.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: nginx-1.31.3/nginx.exe
ReleaseDate: 2026-07-15
Installers:
- Architecture: x64
  InstallerUrl: https://nginx.org/download/nginx-1.31.3.zip
  InstallerSha256: 934A8FEDD91646A4D7C51079AC9B71397D1CAF7A6AEB81CCFD361250C04ACE2C
ManifestType: installer
ManifestVersion: 1.12.0
