# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Keboola.KeboolaCLI
PackageVersion: 2.44.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
ProductCode: '{4BFBB281-F57E-4CD8-A975-5292E674BF1E}'
Installers:
- Architecture: x64
  InstallerUrl: https://cli-dist.keboola.com/msi/keboola-cli_2.44.2_windows_amd64.msi
  InstallerSha256: 34F69797FF4F75FEDFD69B08211E7D9F1D53C28AC1AAFB8ED31CEA836FCA7655
ManifestType: installer
ManifestVersion: 1.10.0
