# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TailwindLabs.TailwindCSS
PackageVersion: 4.2.4
InstallerType: portable
Commands:
- tailwindcss
ReleaseDate: 2026-04-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tailwindlabs/tailwindcss/releases/download/v4.2.4/tailwindcss-windows-x64.exe
  InstallerSha256: 28075CBA911F978519ED7CD5FA543755B601A85922FE5978097911902DDEEE86
ManifestType: installer
ManifestVersion: 1.12.0
