# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: gg.ai.ggcode-cli
PackageVersion: 1.3.121
Platform:
- Windows.Desktop
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- ggcode
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/topcheer/ggcode/releases/download/v1.3.121/ggcode_1.3.121_windows_x64.msi
  InstallerSha256: 764F70D3844EB24E76CD719A4DBE128CEC4449391D1C5DEFC074D1EFADA1D8DD
  ProductCode: '{2BF8605D-59E3-409C-8DAE-47ED658FCEDF}'
  AppsAndFeaturesEntries:
  - DisplayName: ggcode
    Publisher: GG AI Studio
    ProductCode: '{2BF8605D-59E3-409C-8DAE-47ED658FCEDF}'
    UpgradeCode: '{B3C4D5E6-F7A8-9012-BCDE-F23456789012}'
- Architecture: arm64
  InstallerUrl: https://github.com/topcheer/ggcode/releases/download/v1.3.121/ggcode_1.3.121_windows_arm64.msi
  InstallerSha256: 6642D452EA3562DA226709433BF9B33355EB5D55F03A622FFD08DD43EF51812C
  ProductCode: '{E3BCEE18-32FF-4642-8D4E-908F1B26D50C}'
  AppsAndFeaturesEntries:
  - DisplayName: ggcode
    Publisher: GG AI Studio
    ProductCode: '{E3BCEE18-32FF-4642-8D4E-908F1B26D50C}'
    UpgradeCode: '{B3C4D5E6-F7A8-9012-BCDE-F23456789012}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-07-04
