PackageIdentifier: ContextEngine.ContextEngine
PackageVersion: 0.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: "10.0.17763.0"
Installers:
- Architecture: x64
  InstallerType: zip
  InstallerUrl: "https://github.com/context-engine-app/context-engine-mcp/releases/download/v0.1.0/context-engine-x86_64-pc-windows-msvc.zip"
  InstallerSha256: "b955e0997209062d0d097263c17817a440eb5796c8b2535c652f6c91a2240dfd"
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: context-engine.exe
    PortableCommandAlias: context-engine
  Scope: user
  Commands:
  - context-engine
ManifestType: installer
ManifestVersion: 1.12.0
