# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Breizhzion.Hublot
PackageVersion: 0.1.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
ProductCode: '{3F1A9C2E-6B4D-4F8A-9E3C-1D2B5A7C8E4F}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.breizhzion.com/hublot/Hublot-Setup-x64-0.1.1.exe
  InstallerSha256: F359AAD6C75C68DE01C21D4613B8D301277BEB161F3D08D6CFBBD66A44E376F3
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-07
