# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Opera.Opera.Dev
PackageVersion: 133.0.5910.0
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- operadeveloper
FileExtensions:
- crx
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup.exe
  InstallerSha256: 3A3E01281E5D56846A2964AC863668860176F36EBF7A5F1F23A49A0A98D81858
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup.exe
  InstallerSha256: 3A3E01281E5D56846A2964AC863668860176F36EBF7A5F1F23A49A0A98D81858
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup_x64.exe
  InstallerSha256: BAE61CBB3CFEBA50C0A354503DF06D30334E4B11D6ACCF63071BD9EDCD40AAE7
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup_x64.exe
  InstallerSha256: BAE61CBB3CFEBA50C0A354503DF06D30334E4B11D6ACCF63071BD9EDCD40AAE7
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup_arm64.exe
  InstallerSha256: 159797F9E8E743B1018CCBBE0D0E3716E55AED5426405FEB994BF11BD8C9CCF1
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera-developer/133.0.5910.0/win/Opera_Developer_133.0.5910.0_Setup_arm64.exe
  InstallerSha256: 159797F9E8E743B1018CCBBE0D0E3716E55AED5426405FEB994BF11BD8C9CCF1
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.12.0
