# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.sr
PackageVersion: 140.11.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-05-19
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.11.0esr/win32/sr/Thunderbird%20Setup%20140.11.0esr.exe
  InstallerSha256: CF6C48CB77C7F88D58E20790AA7A7B97F0E479A17C1EF489EC42CD54F0E6B390
  ProductCode: Mozilla Thunderbird 140.11.0 (x86 sr)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 sr)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/140.11.0esr/win64/sr/Thunderbird%20Setup%20140.11.0esr.exe
  InstallerSha256: 09CAC71CD44BCBC5D17695D2D7915EA1613B18CA778EB79DEC0A645DEBEAE348
  ProductCode: Mozilla Thunderbird 140.11.0 (x64 sr)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 sr)
ManifestType: installer
ManifestVersion: 1.12.0
