# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ur
PackageVersion: 151.0.4
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-06-09
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win32/ur/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: 7955E659D0D203DB7C7404C065CAABA0171780718502D229C59A9B6DC467DF85
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win64/ur/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: 48BB1EC7DA104C80DE27D6C7FD2E588E72346877353E88207ED6E379895A5FEE
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/151.0.4/win64-aarch64/ur/Firefox%20Setup%20151.0.4.exe
  InstallerSha256: 59560699C465182FA3632B1854771B24EFC086EB285F4D9D8FEDA10D0DD29AD3
ManifestType: installer
ManifestVersion: 1.12.0
