# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WilsonGlasser.Oryxis
PackageVersion: 0.7.4
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
ProductCode: Oryxis
ReleaseDate: 2026-06-01
AppsAndFeaturesEntries:
- ProductCode: Oryxis
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Oryxis'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wilsonglasser/oryxis/releases/download/v0.7.4/oryxis-setup-x86_64.exe
  InstallerSha256: 0E148111D2DCB1A1BF5B93155FE631BF46F9F091260955044CB3920E1D35AC0C
ManifestType: installer
ManifestVersion: 1.12.0
