# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ej-technologies.JProfiler.16.Agent
PackageVersion: 16.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: jprofiler16\bin\jpcontroller.exe
- RelativeFilePath: jprofiler16\bin\jpdump.exe
- RelativeFilePath: jprofiler16\bin\jpenable.exe
Commands:
- jpcontroller
- jpdump
- jpenable
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://download.ej-technologies.com/jprofiler/jprofiler_agent_windows-x32_16_2_1.zip
  InstallerSha256: 786A0FAAF6ACC0C35F4D200F9B7A6C3F1B6D6A7796348A0A057AC24FF15EFB1D
- Architecture: x64
  InstallerUrl: https://download.ej-technologies.com/jprofiler/jprofiler_agent_windows-x64_16_2_1.zip
  InstallerSha256: 4DB63BD838AFE9BD3DD7B27E9CC239A955CE2A3DA1DC3BEEAB87911D7884DC4B
ManifestType: installer
ManifestVersion: 1.12.0
