# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Dev
PackageVersion: 148.0.7743.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- mms
- tel
- webcal
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
AppsAndFeaturesEntries:
- UpgradeCode: '{4446A051-2887-39AC-BF8C-BD2ED8B703CA}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: 1552DBAE52C5A42AD41A5DAAAB1E9DA09F6FF21B0BD5E099C600AFD195F26B1E
  ProductCode: '{66022778-670F-396D-ACC8-CFE0ABEFC3D4}'
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: AB7EB9A2856442C4BFB120E243DC487899B584EE821DE1200A51E7DE57CB0A5A
  ProductCode: '{8E13E428-5AA2-348F-9808-9F09FED4BD31}'
ManifestType: installer
ManifestVersion: 1.12.0
