# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mr-hunt-007.portlist
PackageVersion: "1.2"
InstallerType: zip
NestedInstallerType: portable
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: portlist-1.2/portlist.cmd
    PortableCommandAlias: portlist
  InstallerUrl: https://github.com/Mr-hunt-007/portlist/releases/download/v1.2/portlist-1.2-windows.zip
  InstallerSha256: B0E554416CA3E93C6B9AA043A19D82379E80BDD03797BAB8EFC707DAEB960DC9
ManifestType: installer
ManifestVersion: 1.12.0
