# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anysphere.Cursor
PackageVersion: 3.7.21
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Protocols:
- cursor
FileExtensions:
- ascx
- asp
- aspx
- bash
- bash_login
- bash_logout
- bash_profile
- bashrc
- bib
- bowerrc
- c
- c++
- cc
- cfg
- cjs
- clj
- cljs
- cljx
- clojure
- cls
- cmake
- code-workspace
- coffee
- config
- containerfile
- cpp
- cs
- cshtml
- csproj
- css
- csv
- csx
- ctp
- cxx
- dart
- diff
- dockerfile
- dot
- dtd
- editorconfig
- edn
- erb
- eyaml
- eyml
- fs
- fsi
- fsscript
- fsx
- gemspec
- gitattributes
- gitconfig
- gitignore
- go
- gradle
- groovy
- h
- h++
- handlebars
- hbs
- hh
- hpp
- hxx
- ini
- ipynb
- jade
- jav
- java
- js
- jscsrc
- jshintrc
- jshtm
- json
- jsp
- jsx
- less
- log
- lua
- m
- makefile
- markdown
- md
- mdoc
- mdown
- mdtext
- mdtxt
- mdwn
- mjs
- mk
- mkd
- mkdn
- ml
- mli
- npmignore
- php
- phtml
- pl
- pl6
- plist
- pm
- pm6
- pod
- pp
- profile
- properties
- ps1
- psd1
- psgi
- psm1
- py
- pyi
- r
- rb
- rhistory
- rprofile
- rs
- rst
- rt
- sass
- scss
- sh
- shtml
- sql
- svgz
- t
- tex
- toml
- ts
- tsx
- txt
- vb
- vue
- wxi
- wxl
- wxs
- xaml
- xhtml
- xml
- yaml
- yml
- zsh
ReleaseDate: 2026-06-05
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/517f696d8ab6c53eb04fbfdaae705cd146bf346e/win32/x64/user-setup/CursorUserSetup-x64-3.7.21.exe
  InstallerSha256: FF1CFD0A4061EB69522FE8E1A1CDF0FC19D191C53D60132BAC86FAC0B9498112
  ProductCode: '{DADADADA-ADAD-ADAD-ADAD-ADADADADADAD}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/517f696d8ab6c53eb04fbfdaae705cd146bf346e/win32/x64/system-setup/CursorSetup-x64-3.7.21.exe
  InstallerSha256: A1914E866A30A7EAE9488E2AEDCEB35D56362BAFE3263ECDF551ED9E31A9B185
  ProductCode: '{D7D7D7D7-7D7D-7D7D-7D7D-7D7D7D7D7D7D}_is1'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.cursor.com/production/517f696d8ab6c53eb04fbfdaae705cd146bf346e/win32/arm64/user-setup/CursorUserSetup-arm64-3.7.21.exe
  InstallerSha256: F67F1BD4E1D0D4B2BCF66214802582A485ADBC3C7BA2BDDA25B5C4497D23173F
  ProductCode: '{DBDBDBDB-BDBD-BDBD-BDBD-BDBDBDBDBDBD}_is1'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.cursor.com/production/517f696d8ab6c53eb04fbfdaae705cd146bf346e/win32/arm64/system-setup/CursorSetup-arm64-3.7.21.exe
  InstallerSha256: 8850DE07C13C84972D41A452C556C3D97B49BEB58CAA6221BF1AA149A7051FE9
  ProductCode: '{D8D8D8D8-8D8D-8D8D-8D8D-8D8D8D8D8D8D}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
