# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Apple.iTunes
PackageVersion: 12.13.10.3
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /passive /norestart
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Log: /log "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
UpgradeBehavior: install
Protocols:
- daap
- itals
- italss
- itls
- itlss
- itms
- itmss
- itpc
- itsradio
- itunes
- itunesradio
- itvls
- itvlss
- pcast
FileExtensions:
- aa
- aax
- aif
- aifc
- aiff
- cda
- cdda
- ipa
- ipg
- ipsw
- itb
- itdb
- ite
- itl
- itlp
- itls
- itms
- itpc
- m3u
- m3u8
- m4a
- m4b
- m4p
- m4r
- mp2
- mp3
- mpeg
- mpg
- pcast
- pls
- rmp
- wav
- wave
ReleaseDate: 2026-03-04
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://secure-appldnld.apple.com/itunes12/047-76418-20260302-4b4a1bfb-56ca-4d04-9d80-f4ab23a9540f/iTunesSetup.exe
  InstallerSha256: 0AD837F1C0E4F2160624D3E0F0DB99EC9D2542B0C351D7303460477B0A36464D
  ProductCode: '{C0E50EBD-FE23-42DE-84C0-D1B593278750}'
  AppsAndFeaturesEntries:
  - ProductCode: '{C0E50EBD-FE23-42DE-84C0-D1B593278750}'
    UpgradeCode: '{0880A3FD-2A1E-43C5-B020-09930E075D34}'
    InstallerType: wix
- Architecture: x64
  InstallerUrl: https://secure-appldnld.apple.com/itunes12/047-76416-20260302-fefe4356-211d-4da1-8bc4-058eb36ea803/iTunes64Setup.exe
  InstallerSha256: CEA2A74CAE3F061EADC11358EEAAE9B40CFDEA9EC1EE037B47DA54A64219E182
  ProductCode: '{F0D2C441-5D79-468A-AAA3-C9A3B629560D}'
  AppsAndFeaturesEntries:
  - ProductCode: '{F0D2C441-5D79-468A-AAA3-C9A3B629560D}'
    UpgradeCode: '{0880A3FD-2A1E-43C5-B020-09930E075D34}'
    InstallerType: wix
ManifestType: installer
ManifestVersion: 1.12.0
