# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.en-CA
PackageVersion: "150.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-04-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0/win32/en-CA/Firefox%20Setup%20150.0.exe
  InstallerSha256: 6851AD5F8F725BD18330A225922F1890097840DF03ACCFD75F8ED7F8256ABA2C
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0/win64/en-CA/Firefox%20Setup%20150.0.exe
  InstallerSha256: FCD348422CA20989B85EC90C63D8ED282787A549CCFED813BEE315AF9BDEA8A9
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0/win64-aarch64/en-CA/Firefox%20Setup%20150.0.exe
  InstallerSha256: 6623CCCB56D754A4E84F3D18026FE43A8BAEDE0615619C9D0BA589E4F27B7F5E
ManifestType: installer
ManifestVersion: 1.12.0
