# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.126.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-09
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.126.0&arch=x86
  InstallerSha256: 27E7B89ABEFBEAA17E0C1CF5FC8BAF3A3B00D2650B3F60566AAD90618AFAA50C
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.126.0&arch=amd64
  InstallerSha256: E19BC2DC30BACAE4455B60F3CA637AD6BCF840AF423EC63C2886D8882454FAA8
ManifestType: installer
ManifestVersion: 1.12.0
