# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: TheWiseMonkey.AzureVPN-CLI
PackageVersion: 0.0.2
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/the-wise-monkey/azure-vpn-cli/releases/download/v0.0.2/AzureVPN-CLI-0.0.2-setup.exe
  InstallerSha256: D4ADBDCFD5461B55E38687BEEC4FFD93F2F09A440284B8AABA0024E9036E5549
ManifestType: installer
ManifestVersion: 1.9.0
