# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Chaoleme.ClipCascadeGo.Server
PackageVersion: "1.10"
InstallerType: portable
Commands:
- clipcascade-server
ReleaseDate: 2026-04-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Chaoleme/ClipCascade_go/releases/download/v1.10/clipcascade-server-windows-amd64.exe
  InstallerSha256: FD47B26BC7A9D296F27684AEEA6FFF2B15FF3F97469708306FE27E906E01D8B5
ManifestType: installer
ManifestVersion: 1.12.0
