# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HaystackSoftware.Arq
PackageVersion: 7.44.0.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{B044B502-E401-46D0-9D75-5E56CDA230BA}'
ReleaseDate: 2026-05-19
AppsAndFeaturesEntries:
- ProductCode: '{B044B502-E401-46D0-9D75-5E56CDA230BA}'
  UpgradeCode: '{A51C8077-BCEF-4206-BC6B-B85B22A9D4B3}'
Installers:
- Architecture: x86
  InstallerUrl: https://www.arqbackup.com/download/arqbackup/Arq7.44.0.0.msi
  InstallerSha256: 6131BEE49E4425CC9EFEDDFF1C13D315D274E77792D789F738E01FFA93684C6B
ManifestType: installer
ManifestVersion: 1.12.0
