# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR.zh-TW
PackageVersion: 140.13.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2026-07-21
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win32/zh-TW/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 286F24FAE166DD1368E6FA6B3C5ABEC399D6AB1B7DBB25A60111FE3F5352D9E7
  ProductCode: Mozilla Firefox 140.13.0 ESR (x86 zh-TW)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win64/zh-TW/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 5B6FAFA58A756725D8A02D96FDD4A03A656DE22FB5D160912893113862EE9952
  ProductCode: Mozilla Firefox 140.13.0 ESR (x64 zh-TW)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.13.0esr/win64-aarch64/zh-TW/Firefox%20Setup%20140.13.0esr.exe
  InstallerSha256: 76D4BA5309BE78E139E3E20BBD030A951AAD377C9A13BFE2D1FFF6438825D592
  ProductCode: Mozilla Firefox 140.13.0 ESR (arm64 zh-TW)
ManifestType: installer
ManifestVersion: 1.12.0
