# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DisplayLink.GraphicsDriver
PackageVersion: 12.2.2204.0
InstallerType: zip
NestedInstallerType: msi
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-03-31
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: PublicSoftware - Displaylink\DisplayLink_Win10RS.msi
  InstallerUrl: https://www.synaptics.com/sites/default/files/msi_files/2026-04/DisplayLink%20USB%20Graphics%20Software%20for%20Windows12.2%20M1-MSI.zip
  InstallerSha256: 0EA4084FAA4D30C4D54AEDD771650EFAAEE8229FCAB28F9758C560820282F43D
  ProductCode: '{246363A6-447A-467C-903A-7157C088A9DD}'
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: PublicSoftware - Displaylink\DisplayLink_arm64.msi
  InstallerUrl: https://www.synaptics.com/sites/default/files/msi_files/2026-04/DisplayLink%20USB%20Graphics%20Software%20for%20Windows12.2%20M1-MSI.zip
  InstallerSha256: 0EA4084FAA4D30C4D54AEDD771650EFAAEE8229FCAB28F9758C560820282F43D
  ProductCode: '{45BC036D-A0E7-4FE5-93B9-2707B65ABCD3}'
ManifestType: installer
ManifestVersion: 1.12.0
