# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Abyss116.IndexSearch
PackageVersion: 0.5.0
PackageLocale: en-US
Publisher: Abyss116
PublisherUrl: https://github.com/Abyss116
PublisherSupportUrl: https://github.com/Abyss116/IndexSearch/issues
PackageName: IndexSearch
PackageUrl: https://github.com/Abyss116/IndexSearch
License: MIT OR Apache-2.0
ShortDescription: Persistent-index rg-like search for large source trees.
Moniker: indexsearch
Tags:
- search
- cli
- ripgrep
- code-search
ReleaseNotesUrl: https://github.com/Abyss116/IndexSearch/releases/tag/v0.5.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
