# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Kaedei.Dandanplay
PackageVersion: 18.1.0
PackageLocale: zh-CN
Publisher: Kaedei
PublisherUrl: https://www.dandanplay.com/
PublisherSupportUrl: https://www.dandanplay.com/contact.html
PrivacyUrl: https://www.dandanplay.com/privacy.html
Author: Kaedei
PackageName: 弹弹play
PackageUrl: https://www.dandanplay.com/
License: 免费软件
Copyright: Copyright © Kaedei 2012-2026
ShortDescription: 全功能“本地视频+弹幕”播放器
Tags:
- 动漫
- 动画
- 多媒体
- 媒体
- 弹幕
- 影音
- 播放器
- 视频
ReleaseNotes: |-
  更新内容：
  1. 首页新增“排行榜”子页面，可以查看多个热门分类的数据排行；
  2. 支持将“在线观看”的剧集加入播放列表，在列表中可以直接切换剧集；
  3. mpv 内核支持串流播放；
  4. 新增支持设置 MonoTorrent v3+ 内核的端口号；
  5. 优化了 mpv 内核高帧率场景下的渲染调度逻辑；
  6. 将嗅探窗口调整为播放开始后不自动关闭；
  7. 优化了图片的加载速度，修复了图片加载中无法点击的问题；
  8. 优化了第三方弹幕窗口的确认逻辑和 UI 布局；
  9. 修复了 mpv 内核渲染阻塞导致的播放器卡死问题；
  10. 修复了媒体库扫描入库时可能触发闪退的问题。
ReleaseNotesUrl: https://www.dandanplay.com/blog.html
ManifestType: locale
ManifestVersion: 1.12.0
