# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NexusMods.Vortex
PackageVersion: 2.0.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: 57979c68-f490-55b8-8fed-8b017a5af2fe
ReleaseDate: 2026-05-12
AppsAndFeaturesEntries:
- ProductCode: 57979c68-f490-55b8-8fed-8b017a5af2fe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Nexus-Mods/Vortex/releases/download/v2.0.1/vortex-setup-2.0.1.exe
  InstallerSha256: E55F28509AA6C6A663054B0FA7725B5F14E7D127923E85BACA006D48FC64564F
ManifestType: installer
ManifestVersion: 1.12.0
