# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ishiimasaki646.gyazo-mcp-server
PackageVersion: 0.6.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gyazo-mcp-server.exe
  PortableCommandAlias: gyazo-mcp-server
ReleaseDate: 2026-04-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ishii-masaki-646/gyazo-mcp-server/releases/download/v0.6.0/gyazo-mcp-server-x86_64-pc-windows-msvc.zip
  InstallerSha256: DA846460680C228BA61064E8A697F5319B73FE7C4746E7216B89DB720DBDE916
ManifestType: installer
ManifestVersion: 1.12.0
