# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.AppInstaller
PackageVersion: 1.29.280.0
PackageLocale: de
PackageName: App-Installer
ShortDescription: Den Windows-Paket-Manager (WinGet), ein leistungsstarkes Befehlszeilentool, mit dem Benutzende Anwendungen auf Windows 10- und Windows 11-Geräten entdecken, installieren, aktualisieren und konfigurieren können.
Tags:
- winget-cli
- wingetcli
- windows-paket-manager
- windowspaketmanager
- desktop-app-installer
- desktopappinstaller
- windows-package-manager
- windowspackagemanager
- 9nblggh4nns1
ManifestType: locale
ManifestVersion: 1.12.0