# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 146.1.90.16
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser-Nightly
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 33324E2B89E5C5E53F46DD3622A7ECCD47D2EA56DFE76283E271ED8434C93468
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 7BAC3D5B1F16FE18DEEDDC9E50B74F82A9BFA1815B63808552B733E62994A26F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 0AFBED76AFDCA704D616670FC3A7CBE70E3A0592608947B03EF3FB38DE230360
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 12505C2AAB3080E66D11A51FE55136856057E6718C8B47623AC641BDE7D50FCC
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 7656336D1355C3F26EC2FB8ECBB7CD93D280AC84703C0A4A4A4BFD2B9B1F6246
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.90.16/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 6A9F232BB8ADA9CFC83E9B5DF4993DB2CCCCF36CDF0AE6D9D485623BC90959F0
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
