# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.LSkat
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: lskat
ReleaseDate: 2026-07-29
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/lskat/master/windows/lskat-master-930-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: C94022CF4B77BA5561FE5F6B5DD38F72D4B81E87511EB28B286A059535D7BF1D
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/lskat/master/windows/lskat-master-930-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: C94022CF4B77BA5561FE5F6B5DD38F72D4B81E87511EB28B286A059535D7BF1D
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
