# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Jellyfin.FFmpeg
PackageVersion: 7.1.3-4
PackageLocale: en-US
Publisher: The Jellyfin Project
PublisherUrl: https://jellyfin.org/contact
PublisherSupportUrl: https://github.com/jellyfin/jellyfin-ffmpeg/issues
PackageName: Jellyfin FFmpeg
PackageUrl: https://github.com/jellyfin/jellyfin-ffmpeg
License: LGPL-2.1
LicenseUrl: https://github.com/jellyfin/jellyfin-ffmpeg/blob/HEAD/LICENSE.md
Copyright: © Jellyfin Contributors
ShortDescription: FFmpeg for Jellyfin with custom extensions and enhancements.
Tags:
- ffmpeg
- ffprobe
- jellyfin-ffmpeg
ReleaseNotes: |-
  What's Changed
  - Add safe bail out for first-vframe ffprobe opt by @gnattu in #673
  - Fix scale_opencl and vpp_rkrga did not attach SAR changes to the frame by @nyanmisaka in #670
  - Fix transpose_cuda flipping SAR for non-90/270 degree rotations by @nyanmisaka in #671
  Full Changelog: v7.1.3-3...v7.1.3-4
ReleaseNotesUrl: https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v7.1.3-4
ManifestType: defaultLocale
ManifestVersion: 1.12.0
