PackageIdentifier: YohanesOkta.OctaCoreUtils
PackageVersion: 1.0
InstallerType: portable
PackageLocale: en-US
Publisher: Yohanes Oktanio
PackageName: OctaCore Utils
License: GNU GPL-3.0
LicenseUrl: https://github.com/yohanesokta/octa_core_utils/blob/main/LICENSE
ShortDescription: CLI utilities for Windows inspired by Unix tools

Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yohanesokta/octa_core_utils/releases/download/1.0/octacore-portable.zip
  InstallerSha256: 7a0f3f56479f6f43e74cfb3d929a7a3b72644b025969cd77966eba5b8cf049ae

Commands:
- ochelp
- octa-init
- cat
- ls
- notify