# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nickknissen.TailscaleCommandPalette
PackageVersion: 1.0.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nickknissen/TailscaleCommandPalet/releases/download/1.0.1/TailscaleCommandPalet-Setup-1.0.1-x64.exe
  InstallerSha256: 66D44AECCAC8A68486391181D03AA2FA4248E5817CCA0EC9B4939351439991AA
- Architecture: arm64
  InstallerUrl: https://github.com/nickknissen/TailscaleCommandPalet/releases/download/1.0.1/TailscaleCommandPalet-Setup-1.0.1-arm64.exe
  InstallerSha256: 2C45D93E691B26E9050A7C477E94FE73E7DF448C9415C31B80F49A98A474F26A
ManifestType: installer
ManifestVersion: 1.12.0
