# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Vivaldi.Vivaldi.Snapshot
PackageVersion: 8.3.4157.3
PackageLocale: en-US
Publisher: Vivaldi Technologies AS.
PublisherUrl: https://vivaldi.com/
PublisherSupportUrl: https://help.vivaldi.com/
PrivacyUrl: https://vivaldi.com/privacy/browser/
Author: Vivaldi Technologies AS.
PackageName: Vivaldi (Snapshot)
PackageUrl: https://vivaldi.com/desktop/
License: Freeware
LicenseUrl: https://vivaldi.com/privacy/vivaldi-end-user-license-agreement/
Copyright: Copyright 2026 Vivaldi Technologies AS. All rights reserved.
ShortDescription: Powerful, Personal and Private web browser
Description: Vivaldi is a web browser. But fun. It comes with a bunch of clever features built-in. It’s super flexible and does not track you.
Tags:
- browser
- chromium
- internet
- web
- webpage
ReleaseNotes: |-
  - [Address bar] Omnibox shortcut is added when entering invalid URL VB-131168
  - [AutoHide] Panel button first click only shows thin line when hovering window VB-131327
  - [Bookmarks] New default bookmarks for India VB-131277
  - [Bookmarks] Policies and extensions can write outside the root bookmark folder VB-125831
  - [Calculator] Precision rounding VB-131340
  - [Calendar] Any successful URL is accepted as a WebCal subscription VB-131197
  - [Calendar] No error for WebCAL subscriptions that stop working VB-131198
  - [Chromium] Update to 152.0.7977.112: includes a fix for CVE-2026-85046 (Type confusion in V8)
  - [Commands][Keyboard] Allow Paste and Go to open multiple URLs from the clipboard VB-131272
  - [Find in Page] Pressing F3 searches the whole page again VB-126693
  - [macOS] Clicking link when browser window is closed does not open the link, just reopens the browser window VB-131362
  - [Mail] Optimize message list rendering VB-128889
  - [Mail] Status/Logs shows no log entries VB-129270
  - [Mail] Use new vivaldi-headers when restoring db from disk VB-129503
  - [Mail][Settings] "When replying, use the same format as the original message" has no effect VB-130968
  - [Panel] Can't move items in "Customize your Sidebar" VB-130009
  - [Panel] History item shifts on click at bottom of list VB-131027
  - [Panel] History panel does not update VB-131035
  - [Reader Mode] Implement reader mode in a better way VB-104993
  - [Settings] Calendar provider buttons unreadable on hover VB-131298
  - [Settings] Page zoom also reset ui zoom VB-131300
  - [Settings] Theme editor warning gives wrong indication VB-127395
  - [Settings] Typing in setting search removes all letters that gets highlighted VB-131473
  - [Speed Dial] Wrong prefs dialog button position VB-131258
  - [Start Page] Click Date widget to open Calendar VB-130979
  - [Tabs] Cut and paste tab appears in the wrong position VB-130893
  - [Tabs] Drag-drop link tab appears in the wrong position VB-130892
  - [Tabs] Pinned tab image wrong on drag after taking out of stack VB-130761
  - [Tabs] Popup for activate tab does not appear on pinned tabs VB-130984
  - [Tabs] Popup thumbnail obstructs pinned tabs if tab bar is on the bottom VB-130970
  - [Tabs] Tiny Tab Thumbnails VB-131318
  - [Tabs] With compact tab grouping, only the bottom half of the close button works VB-130522
  - [Tabs][Vertical Tabs] Auto expand tabs on hover for vertical tabs VB-131036
  - [Tabs][Vertical Tabs] Difficult to initiate drag and drop vertically with different widths VB-130764
  - [Tabs][Vertical Tabs] Flexible spacing doesn't utilize vertical space VB-131200
  - [Tabs][Vertical Tabs][Settings] Add setting to show or hide title of pinned tabs VB-130813
  - [Themes] Pinned tabs have invisible background in unified design VB-130771
  - [Themes] Stronger page edge for unified themes VB-127600
  - [Windows][Crash] While processing a virtual desktop change event VB-129877
ReleaseNotesUrl: https://update.vivaldi.com/update/1.0/relnotes/snapshot/8.3.4157.3.html
ManifestType: defaultLocale
ManifestVersion: 1.12.0
