# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AtomGit.AtomCode
PackageVersion: 4.23.3
InstallerType: portable
Commands:
- atomcode
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-05-28
Installers:
- Architecture: x64
  InstallerUrl: https://atomgit.com/atomgit_atomcode/atomcode/releases/download/v4.23.3/atomcode-v4.23.3-windows-x64.exe
  InstallerSha256: AE7E50ADBE78E51A8C0F1511F77994BE02A9132066781017652AB26151D8B297
ManifestType: installer
ManifestVersion: 1.12.0
