# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Modrinth.ModrinthApp
PackageVersion: 0.14.6
PackageLocale: en-US
Publisher: Modrinth
PublisherUrl: https://modrinth.com/
PublisherSupportUrl: https://support.modrinth.com/en/
PrivacyUrl: https://modrinth.com/legal/privacy
Author: Modrinth
PackageName: Modrinth App
PackageUrl: https://modrinth.com/app
License: GPL-3.0
LicenseUrl: https://github.com/modrinth/code/blob/main/apps/app/LICENSE
ShortDescription: The Modrinth App is a unique, open source Minecraft launcher that allows you to play your favorite mods, and keep them up to date, all in one neat little package.
Tags:
- minecraft
- minecraft-launcher
- modrinth
ReleaseNotes: |-
  Added
  - Added the ability to reorder saved skins in the skin selector by dragging and dropping them.
  - Added recovery steps for more Microsoft sign-in and Xbox authentication errors.

  Changed
  - Adding a skin to the skin selector will no longer automatically apply it to your Minecraft account.

  Fixed
  - Fixed issue where the theme would not change automatically if set to "System theme" and the system theme changes.
  - Fixed rate limit issue when adding a skin in the skin selector.
  - Fixed issue with the Skin selector appearing in a broken state when the Minecraft api is unavailable. Now it appears in a read only state, showing the last selected skin or the default skin if it is unable to determine the last selected skin.
  - Fixed issue where skins which had translucency in the outer layer did not correctly render.
  - Fixed issue in Skin selector where the Edit button was not available on skins included within Modrinth App - meaning you could not change the cape of the skin without first applying it.
  - Fixed loading state incorrectly showing briefly in the Skins selector when a saved skin is deleted.
ReleaseNotesUrl: https://github.com/modrinth/code/releases/tag/v0.14.6
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://support.modrinth.com/en/collections/7804910-modrinth-app
ManifestType: defaultLocale
ManifestVersion: 1.12.0
