# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HaiYing.OfficeCLI
PackageVersion: 1.0.95
InstallerType: portable
Commands:
- officecli
ReleaseDate: 2026-05-20
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.95/officecli-win-x64.exe
  InstallerSha256: 755863A486F5925C8F08BCA023261DA91CD8FE408A053B4C245443AF2CF25185
- Architecture: arm64
  InstallerUrl: https://github.com/iOfficeAI/OfficeCLI/releases/download/v1.0.95/officecli-win-arm64.exe
  InstallerSha256: 895667B5DE063E18AB590D60F966A9778C94AA1786B0D3B641F776B60679EDF0
ManifestType: installer
ManifestVersion: 1.12.0
