# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: qr243vbi.NekoBox
PackageVersion: 5.10.24
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: NekoBox
ReleaseDate: 2026-03-13
AppsAndFeaturesEntries:
- ProductCode: NekoBox
  DisplayName: NekoBox
  Publisher: qr243vbi
InstallModes:
  - silentWithProgress
  - silent
InstallerSwitches:
  Silent: "/S /NOSCRIPT=1 /WINGET=1"
  SilentWithProgress: "/S /NOSCRIPT=1 /WINGET=1"
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\NekoBox'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/qr243vbi/nekobox/releases/download/5.10.24/nekobox-5.10.24-windows64-installer.exe
  InstallerSha256: 33A1EB8F1B59BAA4D34003CD4147FBB8CE7A224C4206CE0DD7BE6010D167B92A
- Architecture: arm64
  InstallerUrl: https://github.com/qr243vbi/nekobox/releases/download/5.10.24/nekobox-5.10.24-windows-arm64-installer.exe
  InstallerSha256: F7243E36A82F5E7BE6DE7ABF6C5534FF7A55C774C4676D12CBAF9FB0B664650C
ManifestType: installer
ManifestVersion: 1.10.0