# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Devlint.GitWand
PackageVersion: 3.6.3
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{74F47001-D2A1-4641-A305-AB30DD4418C4}'
AppsAndFeaturesEntries:
- UpgradeCode: '{657CFCE3-C37E-57E6-8C49-821826D858E4}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/devlint/GitWand/releases/download/v3.6.3/GitWand_3.6.3_x64_en-US.msi
  InstallerSha256: 9F0975431B38A90DD7162F945E56DE44F845128713BCCA9C04369BFC06906A94
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-08-13
