# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Y-ASLant.ElegantClipboard
PackageVersion: 0.9.3
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Y-ASLant/ElegantClipboard/releases/download/v0.9.3/ElegantClipboard_0.9.3_x64-setup.exe
  InstallerSha256: 52028EA8123E09BF5BEF129AF92A808DE88AF10C1D309AC5BE22F8992FCC6DD8
- Architecture: arm64
  InstallerUrl: https://github.com/Y-ASLant/ElegantClipboard/releases/download/v0.9.3/ElegantClipboard_0.9.3_arm64-setup.exe
  InstallerSha256: 92266F29B4B4848E29E3B5391966A3F41A6BF9C90C57CA7D8FCEC4C5C1525DAE
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-03-07
