# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Hugo.Hugo.Deploy
PackageVersion: 0.162.1
PackageLocale: en-US
Publisher: The Hugo Authors
PublisherUrl: https://gohugo.io/
PublisherSupportUrl: https://discourse.gohugo.io/
Author: The Hugo Authors
PackageName: Hugo (Deploy)
PackageUrl: https://gohugo.io/
License: Apache-2.0
LicenseUrl: https://github.com/gohugoio/hugo/blob/HEAD/LICENSE
Copyright: Copyright 2025 The Hugo Authors.
ShortDescription: The world's fastest framework for building websites (with WebP encoding, Sass transpiling and Deploy website support)
Tags:
- blog-engine
- cms
- content-management-system
- documentation-tool
- go
- hugo
- static-site-generator
ReleaseNotes: |-
  What's Changed
  - modules/npm: Fix false stale warning after npm pack 59f35cd @jmooring #14959
  - Revert "tpl/collections: Make dict return nil when no values are provided" c270975 @bep #14958
  - tpl/time: Fix locale-specific month abbreviations ea8b48a @jmooring #14948
ReleaseNotesUrl: https://github.com/gohugoio/hugo/releases/tag/v0.162.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
