# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 33.0.7
PackageLocale: en-US
Publisher: Nextcloud GmbH
PublisherUrl: https://nextcloud.com/
PublisherSupportUrl: https://github.com/nextcloud/desktop/issues
PrivacyUrl: https://nextcloud.com/privacy
Author: Nextcloud GmbH
PackageName: Nextcloud
PackageUrl: https://nextcloud.com/
License: GPL-2.0
LicenseUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
Copyright: © 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
ShortDescription: The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud Server with your computer.
Description: |-
  Use the desktop clients to keep your files synchronized between your Nextcloud server and your desktop.
  Select one or more directories on your local machine and always have access to your latest files wherever you are.
Moniker: nextclouddesktop
Tags:
- cloud
- cloud-sync
- nextcloud-desktop-client
- synchronization
- utility
ReleaseNotes: |-
  What's Changed
  - [stable-33.0] fix: build error with OpenSSL 4.0 by @backportbot[bot] in nextcloud/desktop#10229
  - [stable-33.0] fix(#10216): Prevent app nap and silent kill by @backportbot[bot] in nextcloud/desktop#10232
  - [stable-33.0] fix(UI): read OCC_UPDATE_URL only for dev builds by @backportbot[bot] in nextcloud/desktop#10241
  - [stable-33.0] fix(gui): remove gap after status messages by @backportbot[bot] in nextcloud/desktop#10246
  - [stable-33.0] Bugfix/end to end encryption by @backportbot[bot] in nextcloud/desktop#10248
  - Port #10252 back manually to stable-33.0 by @i2h3 in nextcloud/desktop#10256
  - Confine Enumeration (stable-33.0) by @i2h3 in nextcloud/desktop#10261
ReleaseNotesUrl: https://github.com/nextcloud-releases/desktop/releases/tag/v33.0.7
ManifestType: defaultLocale
ManifestVersion: 1.12.0
