# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: J3n5en.EnsoAI
PackageVersion: 0.2.41
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/J3n5en/EnsoAI/releases/download/v0.2.41/EnsoAI-Setup-0.2.41.exe
    InstallerSha256: 60DDFF289A2A9203A45BB109A684D15395998F35812215CAF9EC1B29EB6C6F00
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
ManifestType: installer
ManifestVersion: 1.12.0
