# Created with automated Bitwig updater
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bitwig.bitwig
PackageVersion: 6.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
FileExtensions:
- bwproject
- bwtemplate
Installers:
- Architecture: x64
  InstallerUrl: https://www.bitwig.com/dl/Bitwig%20Studio/6.1/installer_windows/
  InstallerSha256: 5C332AA970271F047410C4DF93D7203923DDAB389B9B32021903D1CEBCE131B1
  ProductCode: '{AA96494B-2512-4799-8CC6-82C64DEB5371}'
- Architecture: arm64
  InstallerUrl: https://www.bitwig.com/dl/Bitwig%20Studio/6.1/installer_windowsarm/
  InstallerSha256: 735BA31F96609D63EC15E8BFBEFF56B63317A00ED13F2FDA765BA40090E380FD
  ProductCode: '{6B53D769-37FB-4C11-98F8-02DEF9B6A9EF}'
ManifestType: installer
ManifestVersion: 1.12.0
