# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LobeHub.LobeHub
PackageVersion: 2.2.8
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 2076975c-e569-5439-b1ad-ecff760e8dd0
ReleaseDate: 2026-06-22
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/lobehub/lobehub/releases/download/v2.2.8/LobeHub-2.2.8-setup.exe
  InstallerSha256: F05E5CBE6D5187E7F0293F4FE696E43078E0449AF1CA0910597DD84E418117DE
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/lobehub/lobehub/releases/download/v2.2.8/LobeHub-2.2.8-setup.exe
  InstallerSha256: F05E5CBE6D5187E7F0293F4FE696E43078E0449AF1CA0910597DD84E418117DE
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
