# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.Dola
PackageVersion: 2.28.13
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --command=quiet_install
  SilentWithProgress: --command=quiet_install
  InstallLocation: --target_dir="<INSTALLPATH>"
  Log: --log_dir="<LOGPATH>"
UpgradeBehavior: install
Protocols:
- cici
- dola
ProductCode: Cici
ReleaseDate: 2026-09-11
Installers:
- Architecture: x64
  InstallerUrl: https://www.dola.com/download-desktop/cdn_obj/cici_pc/2.28.13/Dola_installer_2.28.13.exe
  InstallerSha256: FF7E00FD9662F23F221CECBFD68953A6AE5CDDE46E234E6FDAC6006BD3BEF413
ManifestType: installer
ManifestVersion: 1.12.0
