# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EmirE.Capsule
PackageVersion: 0.4.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: Capsule
ReleaseDate: 2026-02-22
AppsAndFeaturesEntries:
- ProductCode: Capsule
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\.capsule'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ramazanenescik04/Capsule-Launcher/releases/download/0.4.0/CapsuleSetup.exe
  InstallerSha256: 440A37E030DC10B992685FD5333C76ADFAD9458892CD24339FDA858D9D33F012
ManifestType: installer
ManifestVersion: 1.12.0
