# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SiddharthVaddem.OpenScreen
PackageVersion: 1.3.0
InstallerLocale: en-US
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: 10304380-88f6-588f-8cec-fff11a0cffdf
ReleaseDate: 2026-04-02
AppsAndFeaturesEntries:
- DisplayName: Openscreen 1.3.0
  ProductCode: 10304380-88f6-588f-8cec-fff11a0cffdf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/siddharthvaddem/openscreen/releases/download/v1.3.0/Openscreen.Setup.latest.exe
  InstallerSha256: 4F8E66EE97588E8B7B8505719D1856A8616C85FAB58E18F6206D9B846BBD8542
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/siddharthvaddem/openscreen/releases/download/v1.3.0/Openscreen.Setup.latest.exe
  InstallerSha256: 4F8E66EE97588E8B7B8505719D1856A8616C85FAB58E18F6206D9B846BBD8542
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.10.0
