# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Danfoss.CoolConfig
PackageVersion: 6.0.4.283
InstallerType: inno
Scope: user
FileExtensions:
- ccfd
- ccfg
ProductCode: Danfoss CoolConfig_is1
Installers:
- Architecture: x86
  InstallerUrl: https://coolconfig.danfoss.com/coolconfig/coolconfig.exe
  InstallerSha256: A10FA11761E6D03BBCC69804568444B2AE3D66A7781F36FC4A1F998C80867244
ManifestType: installer
ManifestVersion: 1.12.0
