# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: QIAGEN.CLCServerCommandLineTools
PackageVersion: 26.0.6
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -q -Dinstall4j.suppressUnattendedReboot=true
  SilentWithProgress: -q -splash "" -Dinstall4j.suppressUnattendedReboot=true
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
UpgradeBehavior: install
ProductCode: 0803-8719-3724-8959
ReleaseDate: 2026-09-09
Installers:
- Architecture: x64
  InstallerUrl: https://download.clcbio.com/CLCServerCommandLineTools/26.0.6/CLCServerCommandLineTools_26_0_6.exe
  InstallerSha256: 60FB47A1AB266DDCD65245D578A0BADF05B3AF49FF4BE643E8BE7F3FB8AE869D
ManifestType: installer
ManifestVersion: 1.12.0
