# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Trancy.TrancyAir
PackageVersion: 1.0.7
InstallerType: nullsoft
Scope: user
Protocols:
- trancy-air
ProductCode: Trancy Air
ReleaseDate: 2026-09-11
Installers:
- Architecture: x64
  InstallerUrl: https://static.trancy.org/air/releases/v1.0.7/TrancyAir_1.0.7_x64-setup.exe
  InstallerSha256: 28C57EEDB6B254A2F016586B2BC3A9D683526C9F6A4286BDF77B85AF6E7C90C3
ManifestType: installer
ManifestVersion: 1.12.0
