# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DelphiBlocks.Blocks
PackageVersion: 0.5.1
InstallerType: inno
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/delphi-blocks/blocks/releases/download/v0.5.1/blocks-0.5.1-setup.exe
  InstallerSha256: 195D8F78DAA9354B4B7AE6BBF49B27E1BAE753CEDC3B620E6A2F0014735D440E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-06-06
