# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: endev.aube
PackageVersion: 1.26.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: aube.exe
- RelativeFilePath: aubr.exe
- RelativeFilePath: aubx.exe
ReleaseDate: 2026-07-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/endevco/aube/releases/download/v1.26.0/aube-v1.26.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 1B594095C26C31E90B5E89EF78CF56AC9B903DB83F1CA214DB6732D9DF09409A
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/endevco/aube/releases/download/v1.26.0/aube-v1.26.0-aarch64-pc-windows-msvc.zip
  InstallerSha256: DA2F5F19D8DD7F953A044C7D46349DBE6849CC9D4618A6175681AD1E9D9B9254
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
