# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.APM
PackageVersion: 0.16.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: apm-windows-x86_64/apm.exe
UpgradeBehavior: install
ReleaseDate: 2026-06-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/apm/releases/download/v0.16.1/apm-windows-x86_64.zip
  InstallerSha256: 35CA70B778A5F2D1201F5DC034B183DC46B281E454CCB027CBBE18D1F156FE08
ManifestType: installer
ManifestVersion: 1.12.0
