# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.sbx
PackageVersion: 0.26.1
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{A9992224-803D-4474-9428-01D776241A06}'
AppsAndFeaturesEntries:
- ProductCode: '{A9992224-803D-4474-9428-01D776241A06}'
  UpgradeCode: '{DA546BF6-4342-4335-8A93-DA620CEBA3F4}'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\DockerSandboxes'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/sbx-releases/releases/download/v0.26.1/DockerSandboxes.msi
  InstallerSha256: 963FC6264EC2310FFD540FA8878603C67D7E164FDAC163FD804378D6CEECFAD9
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-04-17
