# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json
PackageIdentifier: reaConverter.reaConverterLite
PackageVersion: 8.0.231
PackageLocale: en-GB
ShortDescription: Our brand-new free edition that brings the power of batch image conversion to everyone. Whether you're resizing, reformatting, or organising your files, Lite delivers smooth performance with support for the most popular formats.
ManifestType: locale
ManifestVersion: 1.12.0