# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Proton.ProtonPass.CLI
PackageVersion: 2.3.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pass-cli.exe
  PortableCommandAlias: pass-cli
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-08-12
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://proton.me/download/pass-cli/2.3.1/pass-cli-windows-x86_64.zip
  InstallerSha256: 77D190BB15EBAF59BE4A6C46B98FC19019329EEE5DC26832A6F823782234F0D6
ManifestType: installer
ManifestVersion: 1.12.0
