# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Myriad-Dreamin.Tinymist
PackageVersion: 0.15.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tinymist.exe
  PortableCommandAlias: tinymist
Commands:
- tinymist
ReleaseDate: 2026-09-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Myriad-Dreamin/tinymist/releases/download/v0.15.6/tinymist-x86_64-pc-windows-msvc.zip
  InstallerSha256: A626CE5E6FFA9A512F3AB05E8BA13D97D9A6CFAC0F5AE5B0582C9041AEB569A3
- Architecture: arm64
  InstallerUrl: https://github.com/Myriad-Dreamin/tinymist/releases/download/v0.15.6/tinymist-aarch64-pc-windows-msvc.zip
  InstallerSha256: 39C7E36CDDDFFCFCDAE427E3EBD3CEBDCE1124AFFB904ADE1DB759E4336A97C8
ManifestType: installer
ManifestVersion: 1.12.0
