# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Proton.ProtonPass
PackageVersion: 1.38.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.14393.0
InstallerType: appx
UpgradeBehavior: install
PackageFamilyName: ProtonPass_158qdr94jw63p
Capabilities:
- internetClient
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-07-06
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/WindowsApps/ProtonPass_1.38.0.0_x64__158qdr94jw63p'
Installers:
- Architecture: x64
  InstallerUrl: https://proton.me/download/pass/windows/ProtonPass_1.38.0.msix
  InstallerSha256: AE9EE88C8C7658B92B77C04640C5FF1F8911B311F524BDBE2F01641B87210260
  SignatureSha256: AB8D00940B8A8CCC6136B5A0C1F8493A409330E975618B58B697545C8CC0C61A
ManifestType: installer
ManifestVersion: 1.12.0
