# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1780774659-gd08a06
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1780774659-gd08a06/amp-windows-x64-baseline.exe
  InstallerSha256: 87427AAAE9FA9354396F27ADF91D23F207F32472717BB9FED8733B48A6B23EFA
ManifestType: installer
ManifestVersion: 1.12.0
