# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EvaLing.dotzmy
PackageVersion: 0.1.8
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/evagelinaling/dotz.my-update/releases/download/v0.1.8/dotz.my_0.1.8_x64-setup.exe
  InstallerSha256: ABF9A6D9BC00809448779EB8F0447110852E057821A553F838CDEC888B8AADB5
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-12
