# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GaoyangZhang.RivonClaw
PackageVersion: 1.9.21
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 51492edb-6d67-582c-a781-6b48bbf5f3bf
ReleaseDate: 2026-09-23
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.9.21/TK-Copilot.Setup.1.9.21.exe
  InstallerSha256: D358F449EABE1DDD42CBB9B7635F94D27C92D260D89F0131668724273D3344E9
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.9.21/TK-Copilot.Setup.1.9.21.exe
  InstallerSha256: D358F449EABE1DDD42CBB9B7635F94D27C92D260D89F0131668724273D3344E9
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
