# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Microsoft.Surface.ITToolkit
PackageVersion: 1.345.139.0
PackageLocale: en
Publisher: Microsoft
PackageName: Surface IT Toolkit
PackageUrl: https://www.microsoft.com/en-us/download/details.aspx?id=46703
License: Proprietary
ShortDescription: Maintenance dashboard for Microsoft Surface devices, aimed at company IT admins.
Description: |-
  Maintenance dashboard for Microsoft Surface devices, aimed at company IT admins.

  Note that the app's download size is pretty big, at around 2.7 GB.
Moniker: surfaceittoolkit
Tags:
- microsoft-surface-it-toolkit-ui
- microsoftsurfaceittoolkitui
- microsoft-surface-tools-for-it
- microsoftsurfacetoolsforit
- data-eraser-usb-builder
- dataeraserusbbuilder
- surface-diagnostics-app-console
- microsoftsurfacediagnosticsappconsole
- microsoft-surface-uefi-configurator
- microsoftsurfaceueficonfigurator
- microsoft.surfaceittoolkit.ui
- surface-pro
- surface-go
- surface-studio
- surface-hub
- surface-book
ManifestType: defaultLocale
ManifestVersion: 1.12.0