# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AppByTroye.KoodoReader
PackageVersion: 2.3.9
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
FileExtensions:
- azw
- azw3
- cb7
- cbr
- cbt
- cbz
- epub
- fb2
- mobi
- pdf
ProductCode: 233610fa-2bda-5a09-a37b-75e0bafa7920
ReleaseDate: 2026-07-06
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://dl.koodoreader.com/v2.3.9/Koodo-Reader-2.3.9-x64.exe
  InstallerSha256: 7A5FBCA583EC83DACF54031D9CBB6656017DBE2D329B968C96A68517FB602812
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://dl.koodoreader.com/v2.3.9/Koodo-Reader-2.3.9-x64.exe
  InstallerSha256: 7A5FBCA583EC83DACF54031D9CBB6656017DBE2D329B968C96A68517FB602812
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://dl.koodoreader.com/v2.3.9/Koodo-Reader-2.3.9-arm64.exe
  InstallerSha256: B698B5FD1AA5512B4F28CABB5A65A9947A23D00C266C4FBCFAB2DC5D0FABCE5D
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://dl.koodoreader.com/v2.3.9/Koodo-Reader-2.3.9-arm64.exe
  InstallerSha256: B698B5FD1AA5512B4F28CABB5A65A9947A23D00C266C4FBCFAB2DC5D0FABCE5D
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
