# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.457.194.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-08-16
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.194.0&arch=x86
  InstallerSha256: 810019D3D26D7D0D9761A4657B45C5195424A35C38EB561F05929BD919E346AB
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.457.194.0&arch=amd64
  InstallerSha256: A119B538203470FEF372533CDC1E51B9B7200931FB6E9A6E7AE560817D7C3A0F
ManifestType: installer
ManifestVersion: 1.12.0
