# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tombi-toml.tombi
PackageVersion: 1.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tombi.exe
  PortableCommandAlias: tombi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.0.0/tombi-cli-1.0.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 945F710543ACDEC1B3973680F32FB3B9EAB32F388CDEF59AD974624BD8F2A268
- Architecture: arm64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.0.0/tombi-cli-1.0.0-aarch64-pc-windows-msvc.zip
  InstallerSha256: 9567264B567821210EEE4AE4932CAFD6622DADCC92E90CBED37823A53ED49F79
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-05-25
