# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Fastfetch-cli.Fastfetch
PackageVersion: 2.69.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fastfetch.exe
- RelativeFilePath: flashfetch.exe
Commands:
- fastfetch
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/fastfetch-cli/fastfetch/releases/download/2.69.0/fastfetch-windows-amd64.zip
  InstallerSha256: ABA011C1C45D1A6BDCF52098DD0B9AFE990FE444180BC491E87F36670F1452EF
- Architecture: arm64
  InstallerUrl: https://github.com/fastfetch-cli/fastfetch/releases/download/2.69.0/fastfetch-windows-aarch64.zip
  InstallerSha256: 454E48B8AA3C25698B9DBF80BA8E9267C64B78D1EE2715AD3276DFE18AC87A82
ManifestType: installer
ManifestVersion: 1.12.0
