# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Whiteknight.Mdq
PackageVersion: 0.0.1.0
PackageLocale: en-US
Publisher: Whiteknight
PackageName: Mdq
License: MIT License
ShortDescription: Markdown selector syntax and line editor
ManifestType: defaultLocale
ManifestVersion: 1.12.0
