# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RigSmith.Rig
PackageVersion: 1.9.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rig.exe
  PortableCommandAlias: rig
Commands:
- rig
ReleaseDate: 2026-08-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/rigsmith/rigsmith/releases/download/v1.9.0/rig_1.9.0_windows_amd64.zip
  InstallerSha256: CA44DFC1636C60E68304D79C09303384DE326B1514D8F2DDD3E29BEB3A80DA24
- Architecture: arm64
  InstallerUrl: https://github.com/rigsmith/rigsmith/releases/download/v1.9.0/rig_1.9.0_windows_arm64.zip
  InstallerSha256: ABF5D82527583FDBB36E97DC751C874BF1B61864F9B18B611881315040442265
ManifestType: installer
ManifestVersion: 1.12.0
