# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NetEase.UURemote
PackageVersion: 4.23.1.7941
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: GameViewer
Installers:
- Architecture: x64
  InstallerUrl: https://a56.gdl.netease.com/UURemote_Setup_4.23.1.7941_0511214049_gwqd.exe
  InstallerSha256: 481D6FD534E7852DCABFF5974E9D11366F803FE566ADB77B0E435223BCBCF4DF
ManifestType: installer
ManifestVersion: 1.12.0
