# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MladenPrajdic.SSMSToolsPack
PackageVersion: 7.2.1.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
  Custom: ADDLOCAL=ALL
UpgradeBehavior: install
ProductCode: '{CCCE26EF-A0FF-4914-AD02-9039C4F0963F}'
ReleaseDate: 2026-06-30
AppsAndFeaturesEntries:
- UpgradeCode: '{9EC95B23-3E72-445E-92BC-1A5C1B197DC9}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.ssmstoolspack.com/Download/STP?v=7.2.1.0
  InstallerSha256: D4CCB652899FF258CBA6CFF3B5D22F439371ADCADB13482C0F3F657A6EF6410C
ManifestType: installer
ManifestVersion: 1.12.0
