# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.157.1354.0
PackageLocale: eu-ES
PackageName: Microsoft Power BI mahaigaina
PackageUrl: https://www.microsoft.com/eu-es/download/details.aspx?id=58494
Description: Analistarako bereziki egina da. Punta-puntako teknologiako bisualizazioak industria-sektore nagusien datu-kontsultekin eta modelizazio barneratuekin konbinatzen ditu. Sortu eta argitaratu zure txostenak Power Bi zerbitzuan. Power BI mahaigainari esker, besteen interesak indartuko dituzu xehetasun garrantzitsuak edonoiz eta edonon hornituz.
Tags:
- microsoft-power-bi-mahaigaina
- microsoftpowerbimahaigaina
- analytics
- business-intelligence
- dashboarding
- data
- data-analysis
- data-visualization
- power-bi-desktop
- powerbidesktop
- reporting
- visualization
- 9ntxr16hnw1t
ManifestType: locale
ManifestVersion: 1.12.0
