# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.gn
PackageVersion: 150.0.2
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-05-07
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.2/win32/gn/Firefox%20Setup%20150.0.2.exe
  InstallerSha256: BB6CE23CCC349CFEBBB32AF581CC2BB7B2D2F36757363D05AF29CB96C0EC6F81
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.2/win64/gn/Firefox%20Setup%20150.0.2.exe
  InstallerSha256: 50259B15F61CBCBB6BF7CA63596A61B707E70DD8F7E2C19425649E7A7847701A
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/150.0.2/win64-aarch64/gn/Firefox%20Setup%20150.0.2.exe
  InstallerSha256: D3194A3DCB3E83EB08AFA1402BC557939C84C40F23DFF46814D5C0DA00395117
ManifestType: installer
ManifestVersion: 1.12.0
