# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sourcegit-scm.SourceGit
PackageVersion: '2026.12'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: SourceGit/SourceGit.exe
  PortableCommandAlias: sourcegit
ReleaseDate: 2026-06-01
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sourcegit-scm/sourcegit/releases/download/v2026.12/sourcegit_2026.12.win-x64.zip
  InstallerSha256: AD14C57BA4E0C2FEA35865E330BD00D18E8D1B7B673D549A9F1B63E2DA69AC3E
- Architecture: arm64
  InstallerUrl: https://github.com/sourcegit-scm/sourcegit/releases/download/v2026.12/sourcegit_2026.12.win-arm64.zip
  InstallerSha256: 82627B1FFFF9902FBA5ABC949A81FFDD223DB26D0676DAFCCCCF6066D41D6821
ManifestType: installer
ManifestVersion: 1.12.0
