PackageIdentifier: emtypyie.cli
PackageVersion: 3.0.3
PackageLocale: en-US
Publisher: emtypyie
PackageName: emtypyie-cli
ShortDescription: Emtypyie CLI - Run emtypyie projects from your terminal with ease
Description: Emtypyie CLI allows you to create, manage, and run emtypyie projects directly from your terminal.
License: Proprietary
ManifestType: defaultLocale
ManifestVersion: 1.9.0